{{/*
The Kubernetes object-name stem — `ApplicationGateways.ObjectNameOf`, `{network}-{name}`, computed by
the reconciler. Namespaced objects, so the subscription and resource group are already in the
namespace; two networks in one resource group are what the network component keeps apart.
*/}}
{{- define "appgw.objectName" -}}
{{- default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
The Kube-OVN Subnet the pod joins — `{namespace}-{network}-{subnet}`, NetworkSubnets.ObjectNameOf's
spelling. The namespace and network come from `platform`, which the reconciler writes from the
resource's address, so a body cannot place the gateway on another network's subnet.
*/}}
{{- define "appgw.logicalSwitch" -}}
{{- printf "%s-%s-%s" .Values.platform.namespace .Values.platform.virtualNetwork .Values.subnet -}}
{{- end -}}

{{/*
The frontend address as Kube-OVN's `ip_pool` annotation wants it: comma-joined into ONE dual-stack
address — charts/managed/haproxy's `haproxy.addressPool`, for its reason.
*/}}
{{- define "appgw.addressPool" -}}
{{- if .Values.frontend.v6 -}}
{{- printf "%s,%s" .Values.frontend.v4 .Values.frontend.v6 -}}
{{- else -}}
{{- .Values.frontend.v4 -}}
{{- end -}}
{{- end -}}

{{/*
The two images, each by tag AND digest.

⚠ THE SAME TWO STRINGS ARE `ApplicationGateways.ProxyImage` AND `.WafImage`, and
NetworkApplicationGatewayTests reads this file for both. A digest rather than charts/managed/haproxy's
moving tag because the proxy and the agent are a PAIR — coraza-spoa's CI runs the CRS regression suite
against named HAProxy lines — and a moving tag on either side is an untested pair on the next restart.
*/}}
{{- define "appgw.proxyImage" -}}
docker.io/library/haproxy:3.2.23-alpine@sha256:5961c68bc8a81c5124d0a98ab20f81b74717d6afe596e805977d9cf84c126222
{{- end -}}

{{- define "appgw.wafImage" -}}
ghcr.io/corazawaf/coraza-spoa:0.7.3@sha256:2d262d2eb34eb3efa1d2e4a164903c446beeee69877b7e693d46040b3fee38c2
{{- end -}}

{{/*
What one container costs — `ApplicationGateways.Presets`, row for row, and the proxy and the agent
each get it. NetworkApplicationGatewayTests compares the two tables.
*/}}
{{- define "appgw.resources" -}}
{{- $presets := dict
  "c1.small"  (dict "cpu" "250m" "memory" "256Mi")
  "c1.medium" (dict "cpu" "500m" "memory" "512Mi")
  "c1.large"  (dict "cpu" "1"    "memory" "1Gi") -}}
{{- $chosen := get $presets .Values.sizing.preset | default (get $presets "c1.small") -}}
requests:
  cpu: {{ $chosen.cpu | quote }}
  memory: {{ $chosen.memory | quote }}
limits:
  cpu: {{ $chosen.cpu | quote }}
  memory: {{ $chosen.memory | quote }}
{{- end -}}

{{/*
The pool names, in the order a member first mentions them, as a JSON list.
*/}}
{{- define "appgw.pools" -}}
{{- $pools := list -}}
{{- range .Values.backendPools -}}
{{- $pool := regexFind "^[^=]+" . -}}
{{- if not (has $pool $pools) -}}
{{- $pools = append $pools $pool -}}
{{- end -}}
{{- end -}}
{{- toJson $pools -}}
{{- end -}}

{{/*
HAProxy's configuration — the second spelling of `ApplicationGateways.HaproxyConfig`, line for line.

⚠ BUILT AS A LIST OF LINES AND JOINED, because Go template whitespace control over a document this
shape drifts by one blank line the first time anybody edits it, and the pod template's checksum is
taken over whichever spelling rendered it.

⚠ A MEMBER THAT IS A RESOURCE ID IS A COMMENT HERE. The reconciler resolves a virtual machine to its
address through the cross-resource view; a chart install has no view.
*/}}
{{- define "appgw.haproxyConfig" -}}
{{- $v := .Values -}}
{{- $waf := $v.waf.mode -}}
{{- $l := list
  "# Generated by CyberCloud from CyberCloud.Network/virtualNetworks/applicationGateways."
  "# Edits are overwritten on the next reconcile pass."
  "global"
  "  log stdout format raw local0 info"
  (printf "  maxconn %d" (mul $v.limits.maxConnections 2 | int))
  ""
  "defaults"
  "  mode http"
  "  log global"
  "  option httplog"
  "  option dontlognull"
  "  timeout connect 5s"
  "  timeout client 60s"
  "  timeout server 60s"
  "  timeout http-request 10s"
  ""
  "frontend health"
  "  bind :8405"
  "  monitor-uri /healthz" -}}
{{- if ne $waf "off" -}}
{{- $l = append $l "  monitor fail if { nbsrv(waf) lt 1 }" -}}
{{- end -}}
{{- $l = concat $l (list "" "frontend inbound" (printf "  bind :%d" ($v.listeners.httpPort | int))) -}}
{{- if $v.listeners.certificate -}}
{{- $l = append $l (printf "  bind :%d ssl crt /etc/cybercloud/tls/tls.pem" ($v.listeners.httpsPort | int)) -}}
{{- end -}}
{{- $l = concat $l (list (printf "  maxconn %d" ($v.limits.maxConnections | int)) "  option forwardfor") -}}
{{- if eq $waf "off" -}}
{{- $l = append $l "  log-format \"%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %tsc %{+Q}r host:%[var(txn.host)]\"" -}}
{{- else -}}
{{- $l = append $l "  log-format \"%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %tsc %{+Q}r host:%[var(txn.host)] waf-action:%[var(txn.coraza.action)] waf-score:%[var(txn.coraza.anomaly_score)] waf-rules:%[var(txn.coraza.rule_ids)] waf-error:%[var(txn.coraza.error)]\"" -}}
{{- end -}}
{{- $l = concat $l (list
  "  http-request set-var(txn.host) req.hdr(host),field(1,:),lower"
  "  http-request set-header X-Forwarded-Proto https if { ssl_fc }"
  "  http-request set-header X-Forwarded-Proto http if !{ ssl_fc }") -}}
{{- if ne $waf "off" -}}
{{- $l = concat $l (list
  "  option http-buffer-request"
  "  filter spoe engine coraza config /usr/local/etc/haproxy/coraza.cfg"
  "  http-request send-spoe-group coraza coraza-req") -}}
{{- if eq $waf "prevention" -}}
{{- $l = concat $l (list
  "  http-request deny deny_status 403 hdr waf-block request if { var(txn.coraza.action) -m str deny }"
  "  http-request silent-drop if { var(txn.coraza.action) -m str drop }"
  "  http-request deny deny_status 503 if { var(txn.coraza.error) -m int gt 0 }") -}}
{{- end -}}
{{- end -}}
{{- range $v.routingRules -}}
{{- $host := regexFind "^[^/]+" . -}}
{{- $pool := regexFind "[^=]+$" . -}}
{{- $path := trimSuffix (printf "=%s" $pool) (trimPrefix $host .) -}}
{{- $cond := "" -}}
{{- if eq $host "*" -}}
{{- else if hasPrefix "*." $host -}}
{{- $cond = printf "{ var(txn.host) -m end %s }" (trimPrefix "*" $host) -}}
{{- else -}}
{{- $cond = printf "{ var(txn.host) -m str %s }" $host -}}
{{- end -}}
{{- if eq $path "/" -}}
{{- $l = append $l (printf "  use_backend pool-%s%s" $pool (ternary "" (printf " if %s" $cond) (eq $cond ""))) -}}
{{- else -}}
{{- $prefix := ternary "" (printf "%s " $cond) (eq $cond "") -}}
{{- $l = append $l (printf "  use_backend pool-%s if %s{ path %s } || %s{ path_beg %s/ }" $pool $prefix $path $prefix $path) -}}
{{- end -}}
{{- end -}}
{{- $l = concat $l (list
  "  default_backend no-route"
  ""
  "backend no-route"
  "  http-request return status 404 content-type text/plain string \"no routing rule matched this request\"") -}}
{{- range $pool := (include "appgw.pools" $ | fromJsonArray) -}}
{{- $l = concat $l (list
  ""
  (printf "backend pool-%s" $pool)
  "  balance roundrobin"
  "  option httpchk"
  (printf "  http-check send meth GET uri %s" $v.health.path)
  "  http-check expect status 200-399") -}}
{{- range $i, $m := $v.backendPools -}}
{{- if eq (regexFind "^[^=]+" $m) $pool -}}
{{- $rest := trimPrefix (printf "%s=" $pool) $m -}}
{{- $port := regexFind "[0-9]+$" $rest -}}
{{- $target := trimSuffix "]" (trimPrefix "[" (trimSuffix (printf ":%s" $port) $rest)) -}}
{{- if hasPrefix "/" $target -}}
{{- $l = append $l (printf "  # m%d %s did not resolve to an address" (add1 $i) $target) -}}
{{- else -}}
{{- $address := ternary (printf "[%s]" $target) $target (contains ":" $target) -}}
{{- $l = append $l (printf "  server m%d %s:%s check inter %dms rise %d fall %d maxconn %d" (add1 $i) $address $port (mul $v.health.intervalSeconds 1000 | int) ($v.health.healthyAfter | int) ($v.health.unhealthyAfter | int) ($v.limits.maxConnections | int)) -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if ne $waf "off" -}}
{{- $l = concat $l (list "" "backend waf" "  mode tcp" "  option spop-check" "  server agent 127.0.0.1:9000 check inter 2s") -}}
{{- end -}}
{{- join "\n" $l }}
{{ end -}}

{{/*
The SPOE configuration HAProxy's filter reads — `ApplicationGateways.SpoeConfig`. The message's
arguments are in the order coraza-spoa's example says they are "required to be in".
*/}}
{{- define "appgw.spoeConfig" -}}
# Generated by CyberCloud from CyberCloud.Network/virtualNetworks/applicationGateways.
[coraza]
spoe-agent coraza-agent
    groups      coraza-req
    option      var-prefix      coraza
    option      set-on-error    error
    timeout     hello           2s
    timeout     idle            2m
    timeout     processing      500ms
    use-backend waf

spoe-message coraza-req
    args app=str(gateway) src-ip=src src-port=src_port dst-ip=dst dst-port=dst_port method=method path=path query=query version=req.ver headers=req.hdrs body=req.body exportRuleIDs=bool(true)

spoe-group coraza-req
    messages coraza-req
{{ end -}}

{{/*
The WAF policy as coraza-spoa reads it — `ApplicationGateways.WafConfig`. The agent binds
127.0.0.1:9000 so nothing on the tenant's network can speak SPOP to it: bind 127.0.0.1:9000.

⚠ THE ORDER IS THE POLICY: the mode after the recommended file (which sets DetectionOnly), the
paranoia level after the CRS setup, custom rules before the CRS so an allow skips it, exclusions after
the rules they remove.
*/}}
{{- define "appgw.wafConfig" -}}
{{- $v := .Values -}}
{{- $d := list "Include @coraza.conf-recommended" (ternary "SecRuleEngine On" "SecRuleEngine DetectionOnly" (eq $v.waf.mode "prevention")) "Include @crs-setup.conf.example" (printf "SecAction \"id:900000,phase:1,pass,t:none,nolog,setvar:tx.blocking_paranoia_level=%d\"" ($v.waf.paranoiaLevel | int)) -}}
{{- range $i, $r := $v.waf.customRules -}}
{{- $p := splitn " " 3 $r -}}
{{- $deny := eq $p._0 "deny" -}}
{{- $id := add (ternary 190000 100000 $deny) (add1 $i) -}}
{{- $vars := dict "ip" "REMOTE_ADDR" "path" "REQUEST_FILENAME" "host" "SERVER_NAME" "useragent" "REQUEST_HEADERS:User-Agent" "method" "REQUEST_METHOD" -}}
{{- $ops := dict "ip" (printf "@ipMatch %s" $p._2) "path" (printf "@beginsWith %s" $p._2) "host" (printf "@streq %s" $p._2) "useragent" (printf "@contains %s" (lower $p._2)) "method" (printf "@streq %s" $p._2) -}}
{{- $d = append $d (printf "SecRule %s \"%s\" \"id:%d,phase:1,%s%s,msg:'CyberCloud custom rule %d: %s %s %s'\"" (get $vars $p._1) (get $ops $p._1) ($id | int) (ternary "t:lowercase," "t:none," (eq $p._1 "useragent")) (ternary "deny,status:403,log" "allow,nolog" $deny) (add1 $i) $p._0 $p._1 $p._2) -}}
{{- end -}}
{{- $d = append $d "Include @owasp_crs/*.conf" -}}
{{- range $v.waf.exclusions -}}
{{- if contains ":" . -}}
{{- $e := splitn ":" 2 . -}}
{{- $d = append $d (printf "SecRuleUpdateTargetById %s \"!%s\"" $e._0 $e._1) -}}
{{- else -}}
{{- $d = append $d (printf "SecRuleRemoveById %s" .) -}}
{{- end -}}
{{- end -}}
# Generated by CyberCloud from CyberCloud.Network/virtualNetworks/applicationGateways.
bind: 127.0.0.1:9000
log_level: info
log_file: /dev/stdout
log_format: json
default_application: gateway
applications:
  - name: gateway
    response_check: false
    transaction_ttl_ms: 60000
    log_level: info
    log_file: /dev/stdout
    log_format: json
    directives: |
{{- range $d }}
      {{ . }}
{{- end }}
{{ end -}}

{{/*
The checksum the pod template carries — `ApplicationGateways.ConfigHash`: HAProxy's file, and the two
WAF files after it unless the firewall is off, separated as the C# joins them. `sha256:` + hex, the
KubeLabels.ReconcileHash spelling.
*/}}
{{- define "appgw.configHash" -}}
{{- $rest := "" -}}
{{- if ne .Values.waf.mode "off" -}}
{{- $rest = printf "%s\n---\n%s" (include "appgw.spoeConfig" .) (include "appgw.wafConfig" .) -}}
{{- end -}}
{{- printf "%s\n---\n%s" (include "appgw.haproxyConfig" .) $rest | sha256sum -}}
{{- end -}}

{{/*
The seven cybercloud.io/* labels — docs/plan/02 § ADR-013.
*/}}
{{- define "appgw.platformLabels" -}}
cybercloud.io/tenant-id: {{ .Values.platform.tenantId | quote }}
cybercloud.io/subscription-id: {{ .Values.platform.subscriptionId | quote }}
cybercloud.io/resource-group: {{ .Values.platform.resourceGroup | quote }}
cybercloud.io/resource-id: {{ .Values.platform.resourceId | quote }}
cybercloud.io/resource-type: {{ .Values.platform.resourceType | replace "/" "_" | lower | quote }}
cybercloud.io/api-version: {{ .Values.platform.apiVersion | quote }}
cybercloud.io/managed-by: {{ .Values.platform.managedBy | quote }}
{{- end -}}

{{/*
The two labels the Deployment selects its pods by — not ADR-013's seven, for charts/managed/haproxy's
reason: KubeCommand injects those into the Deployment and not into its pod template.
*/}}
{{- define "appgw.selectorLabels" -}}
app.kubernetes.io/name: application-gateway
app.kubernetes.io/instance: {{ include "appgw.objectName" . | quote }}
{{- end -}}
