// ⚠ For `Result<string>`. `CyberCloud.Core.Resources` is global in this assembly and
// `CyberCloud.Core` itself is not; the `ErrorCode` alias in GlobalUsings still wins over the
// `Orleans.ErrorCode` this import would otherwise put back in play.
using CyberCloud.Core;
using System.Text.Json.Nodes;

namespace CyberCloud.Providers.Cache;

/// <summary>
///     Serves <c>POST …/redis/{name}/listKeys</c>: where to ask for the primary, and the
///     <c>requirepass</c> that gets a client past <c>AUTH</c>.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>IT READS AND DOES NOT MINT, like every other handler in the tree.</b> The password is
///         created by <see cref="ValkeyCacheReconciler" /> at create time, once, under
///         <c>ISecretWriter</c>'s mint-once rule. An action that minted on demand would give the first
///         caller a password and the second caller a different one, and neither would be the value in
///         the <c>Secret</c> the operator started the server from — so every credential this platform
///         handed out would be one the server has never accepted, while every surface reported
///         success.
///     </para>
///     <para>
///         ⚠ <b>What this type does differently is one step earlier, and it is worth knowing here.</b>
///         For every other data provider the credential is generated by the operator at bootstrap and
///         the reconciler reads it; spotahome generates nothing, so this platform mints. The handler is
///         the same either way — <c>ValkeyCaches.PasswordRef</c> is the one address, spelled once, and
///         this reads it.
///     </para>
///     <para>
///         ⚠ <b>A Sentinel endpoint and a master group, not the primary's own address.</b> See
///         <see cref="ValkeyCaches.ListKeysResponse" />: a client connects to the Sentinel service and
///         asks which member is the primary, because that answer changes at every failover. Handing
///         back the primary's address would work until the first one and then point at a replica.
///     </para>
///     <para>
///         ⚠ <b>Everything but the password is a pure function of the address.</b> Nothing here
///         reaches the cluster, which is why an action carries no <c>ObservedState</c> and does not
///         need one — the endpoint is an address rather than a reading, and a cache that has not
///         converged yet gets an endpoint that does not answer rather than an error that says nothing.
///     </para>
///     <para>
///         ⚠ <b>A vault that is unwired refuses here, legibly, and that is the intended answer.</b>
///         <c>UnavailableSecretResolver</c>'s message names the missing <c>AddOpenBaoSecretResolver</c>
///         call and the two configuration keys. A handler that returned an empty <c>password</c>
///         instead would publish a credential that authenticates nothing, against a schema that says
///         the field is required.
///     </para>
///     <para>
///         ⚠ <b>The value goes into the returned JSON and nowhere else.</b> No log line, no operation
///         record, no cache — see <c>ResourceManagerService.ActionAsync</c> for why not starting an
///         operation is what guarantees that rather than remembers it.
///     </para>
/// </remarks>
public sealed class ValkeyCacheListKeysHandler : IResourceActionHandler {
    /// <inheritdoc />
    public ResourceTypeName Type => ValkeyCaches.Type;

    /// <inheritdoc />
    public string Action => ValkeyCaches.ListKeysAction;

    /// <inheritdoc />
    public async Task<Result<string>> InvokeAsync(
        ActionContext context,
        CancellationToken cancellationToken = default
    ) {
        var password = await context.Secrets.ResolveAsync(
            ValkeyCaches.PasswordRef(context.Id),
            cancellationToken
        );

        if (password.TryGetError(out var error)) {
            return Result<string>.Failure(error);
        }

        // ⚠ The property names are the response schema's pointers with the slash removed, and the
        // dispatcher checks that rather than trusting it — ValkeyCaches.ListKeysResponse is what the
        // OpenAPI document, the SDK and the portal form are generated from.
        return Result<string>.Success(
            new JsonObject {
                ["host"] = ValkeyCaches.SentinelHost(context.Namespace, context.Id.Name),
                ["port"] = ValkeyCaches.SentinelPort,
                ["masterName"] = ValkeyCaches.MasterGroup,
                ["password"] = password.GetValueOrThrow()
            }.ToJsonString()
        );
    }
}
