{{/*
The object name the Deployment, the Service and the ConfigMap take — `grafana-{name}`, the C# side's
Grafanas.ObjectNameOf. `nameOverride` is chart plumbing (@internal in values.yaml) and is not part of
the resource body.
*/}}
{{- define "grafana.objectName" -}}
{{- printf "grafana-%s" (default .Release.Name .Values.nameOverride) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
The admin credential's Secret — Grafanas.AdminSecretName.

⚠ THIS CHART DOES NOT RENDER IT. GrafanaReconciler mints the password once into the tenant's vault and
applies the Secret from what the vault returns; the Deployment below names it in two secretKeyRefs, so
the stem is spelled here once and reachable by the template.
*/}}
{{- define "grafana.adminSecretName" -}}
{{- printf "grafana-%s-admin" (default .Release.Name .Values.nameOverride) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
The workspace's own two objects the pod reads its coordinates from — charts/managed/monitor-workspace's
`monitorWorkspace.rowName` and `monitorWorkspace.keySecretName`, spelled again because a chart cannot
include another chart's helper. GrafanaDeclarationTests reads this file as text and compares the stems
with MonitorWorkspaces.RowName and MonitorWorkspaces.KeySecretName.
*/}}
{{- define "grafana.workspaceRow" -}}
{{- printf "monitor-%s" .Values.platform.workspace -}}
{{- end -}}

{{- define "grafana.workspaceKeySecret" -}}
{{- printf "monitor-%s-ingest" .Values.platform.workspace -}}
{{- end -}}

{{/*
The workspace's VMUser name — the basic-auth username both datasources authenticate as.
*/}}
{{- define "grafana.vmUser" -}}
{{- printf "monitor-%s" .Values.platform.workspace -}}
{{- end -}}

{{/*
The labels the Deployment selects its pods by and the Service selects them by. Immutable on a
Deployment, so nothing from the body is in it.
*/}}
{{- define "grafana.selectorLabels" -}}
app.kubernetes.io/name: grafana
app.kubernetes.io/instance: {{ include "grafana.objectName" . }}
{{- end -}}

{{/*
What each preset gives the pod — a second copy of Grafanas.Presets, compared row for row by
GrafanaDeclarationTests.
*/}}
{{- define "grafana.presets" -}}
{{- $presets := dict
  "c1.small"  (dict "cpu" "250m" "memory" "512Mi")
  "c1.medium" (dict "cpu" "500m" "memory" "1Gi")
  "c1.large"  (dict "cpu" "1"    "memory" "2Gi") -}}
{{- $presets | toJson -}}
{{- end -}}

{{- define "grafana.resources" -}}
{{- $presets := include "grafana.presets" . | fromJson -}}
{{- get $presets .Values.sizing.preset | toJson -}}
{{- end -}}

{{/*
The datasource provisioning file — Grafanas.DatasourcesYaml, as a template.

⚠ `$VAR` IS GRAFANA'S OWN PROVISIONING-FILE INTERPOLATION AND IT HAPPENS AT START, so the accountID,
the database and the ingest key never appear in this ConfigMap; the Deployment hands the pod the three
variables from the workspace's row and Secret by reference. Two datasources, both `editable: false`,
both pointing at this workspace and nothing else — docs/plan/16's "and nothing else". Their uids are
fixed so a dashboard exported from one instance imports into another.
*/}}
{{- define "grafana.datasources" -}}
# Generated by CyberCloud from CyberCloud.Dashboard/grafanas.
# Edits are overwritten on the next reconcile pass.
apiVersion: 1
datasources:
  - name: Metrics
    uid: cybercloud-metrics
    type: prometheus
    access: proxy
    isDefault: true
    editable: false
    url: https://telemetry.cybercloud.svc/select/$CYBERCLOUD_ACCOUNT_ID/prometheus
    basicAuth: true
    basicAuthUser: {{ include "grafana.vmUser" . }}
    secureJsonData:
      basicAuthPassword: $CYBERCLOUD_INGEST_KEY
  - name: Logs and traces
    uid: cybercloud-logs
    type: grafana-clickhouse-datasource
    access: proxy
    editable: false
    jsonData:
      host: telemetry.cybercloud.svc
      port: 443
      protocol: http
      secure: true
      path: /sql/$CYBERCLOUD_DATABASE
      defaultDatabase: $CYBERCLOUD_DATABASE
      username: {{ include "grafana.vmUser" . }}
    secureJsonData:
      password: $CYBERCLOUD_INGEST_KEY
{{- end -}}

{{/*
The seven cybercloud.io/* labels — docs/plan/02 § ADR-013. `resource-type` is lower-cased with `/`
replaced by `_`, matching KubeLabels.ResourceTypeValue.
*/}}
{{- define "grafana.platformLabels" -}}
cybercloud.io/tenant-id: {{ .Values.platform.tenantId | quote }}
cybercloud.io/subscription-id: {{ .Values.platform.subscriptionId | quote }}
cybercloud.io/resource-group: {{ .Values.platform.resourceGroup | quote }}
cybercloud.io/resource-id: {{ .Values.platform.resourceId | quote }}
cybercloud.io/resource-type: {{ .Values.platform.resourceType | replace "/" "_" | lower | quote }}
cybercloud.io/api-version: {{ .Values.platform.apiVersion | quote }}
cybercloud.io/managed-by: {{ .Values.platform.managedBy | quote }}
{{- end -}}
