{{/*
The object name all three objects take — `collector-{workspace}-{name}`, the C# side's
MonitorCollectors.ObjectNameOf.

⚠ THE WORKSPACE'S NAME IS IN IT BECAUSE THE NAMESPACE DOES NOT DISTINGUISH THEM. ReconcileDriver.NamespaceFor
is `{subscriptionId:N}-{resourceGroup}`, so two workspaces in one resource group may each hold a
collector called `gateway`, and a stem without the parent would have them fighting over one Deployment.
The `collector-` prefix keeps it clear of the workspace's own `monitor-{workspace}` objects beside it.
`nameOverride` is chart plumbing (@internal in values.yaml) and is not part of the resource body.
*/}}
{{- define "monitorCollector.objectName" -}}
{{- printf "collector-%s-%s" .Values.platform.workspace (default .Release.Name .Values.nameOverride) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
The workspace's own two objects the pod reads its coordinates from — charts/managed/monitor-workspace's
`monitorWorkspace.rowName` and `monitorWorkspace.keySecretName`, spelled again here because a chart
cannot include another chart's helper.

⚠ A SECOND SPELLING OF MonitorWorkspaces.RowName AND MonitorWorkspaces.KeySecretName, and
CollectorDeclarationTests reads this file as text and compares the two stems. A stem that drifted is a
pod held in CreateContainerConfigError naming a ConfigMap that will never appear.
*/}}
{{- define "monitorCollector.workspaceRow" -}}
{{- printf "monitor-%s" .Values.platform.workspace -}}
{{- end -}}

{{- define "monitorCollector.workspaceKeySecret" -}}
{{- printf "monitor-%s-ingest" .Values.platform.workspace -}}
{{- end -}}

{{/*
The workspace's VMUser name — the basic-auth username every export authenticates as. It is the
workspace's row name, because MonitorWorkspaces.VmUserName and MonitorWorkspaces.RowName are both
`monitor-{workspace}`.
*/}}
{{- define "monitorCollector.vmUser" -}}
{{- printf "monitor-%s" .Values.platform.workspace -}}
{{- end -}}

{{/*
The labels the Deployment selects its pods by and the Service selects them by.

⚠ IMMUTABLE ON A DEPLOYMENT — the API server refuses an update that changes spec.selector — so
nothing from the body is in it: the name is derived from the address, and the address cannot change.
*/}}
{{- define "monitorCollector.selectorLabels" -}}
app.kubernetes.io/name: opentelemetry-collector
app.kubernetes.io/instance: {{ include "monitorCollector.objectName" . }}
{{- end -}}

{{/*
What each preset gives the pod.

⚠ A SECOND COPY OF MonitorCollectors.Presets, and CollectorDeclarationTests compares it row for row —
two spellings of a sizing table is a resource that reserves one quantity and runs another.
*/}}
{{- define "monitorCollector.presets" -}}
{{- $presets := dict
  "c1.small"  (dict "cpu" "250m" "memory" "256Mi")
  "c1.medium" (dict "cpu" "500m" "memory" "512Mi")
  "c1.large"  (dict "cpu" "1"    "memory" "1Gi") -}}
{{- $presets | toJson -}}
{{- end -}}

{{- define "monitorCollector.resources" -}}
{{- $presets := include "monitorCollector.presets" . | fromJson -}}
{{- get $presets .Values.sizing.preset | toJson -}}
{{- end -}}

{{/*
The collector's configuration — MonitorCollectors.CollectorConfig, as a template.

⚠ `${env:…}` IS THE COLLECTOR'S OWN SUBSTITUTION SYNTAX AND IT HAPPENS AT START, so the accountID, the
database and the ingest key never appear in this ConfigMap. The Deployment below hands the pod those
three variables from the workspace's row and Secret by reference. The basic-auth username is spelled in
full because it is the workspace's VMUser name, a pure function of the workspace's name.

⚠ memory_limiter FIRST, batch SECOND, IN EVERY PIPELINE. Upstream: a limiter that is not the first
processor protects nothing. The batch is what makes an export failure asynchronous — a receiver in
front of a failing exporter with no batch answers the client with the exporter's error.

⚠ THE CLICKHOUSE EXPORTER GETS THE QUERY HOST AND THE DATABASE AS TWO SETTINGS, NOT ONE URL — measured
against the real image (SOURCE): clickhouse-go reads a DSN's path as the database name, so the
workspace's `/sql/{database}` SQL endpoint became `database=sql%2Fws_x` in the first request. The host is
MonitorWorkspaces.QueryHost; the database is the workspace's.

⚠ create_schema: false ON THE CLICKHOUSE EXPORTER. The database is the workspace's tenancy and the
platform owns its tables; conformance.yaml § owed says what the exporter expects to find there.
*/}}
{{- define "monitorCollector.config" -}}
# Generated by CyberCloud from CyberCloud.Monitor/workspaces/collectors.
# Edits are overwritten on the next reconcile pass.
receivers:
  otlp:
    protocols:
{{- if .Values.receivers.otlpGrpc }}
      grpc:
        endpoint: 0.0.0.0:4317
{{- end }}
{{- if .Values.receivers.otlpHttp }}
      http:
        endpoint: 0.0.0.0:4318
{{- end }}
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20
  batch:
    timeout: 5s
    send_batch_size: 8192
exporters:
  prometheus_remote_write:
    endpoint: https://ingest.cybercloud.svc/insert/${env:CYBERCLOUD_ACCOUNT_ID}/prometheus/api/v1/write
    auth:
      authenticator: basicauth/workspace
  clickhouse:
    endpoint: https://telemetry.cybercloud.svc
    database: ${env:CYBERCLOUD_DATABASE}
    username: {{ include "monitorCollector.vmUser" . }}
    password: ${env:CYBERCLOUD_INGEST_KEY}
    create_schema: false
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  basicauth/workspace:
    client_auth:
      username: {{ include "monitorCollector.vmUser" . }}
      password: ${env:CYBERCLOUD_INGEST_KEY}
service:
  extensions: [health_check, basicauth/workspace]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus_remote_write]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
{{- end -}}

{{/*
The seven cybercloud.io/* labels — docs/plan/02 § ADR-013.

⚠ `resource-type` is lower-cased with `/` replaced by `_`, matching KubeLabels.ResourceTypeValue. A `/`
is not a legal label value character, so the verbatim type would be an object the API server refuses.
*/}}
{{- define "monitorCollector.platformLabels" -}}
cybercloud.io/tenant-id: {{ .Values.platform.tenantId | quote }}
cybercloud.io/subscription-id: {{ .Values.platform.subscriptionId | quote }}
cybercloud.io/resource-group: {{ .Values.platform.resourceGroup | quote }}
cybercloud.io/resource-id: {{ .Values.platform.resourceId | quote }}
cybercloud.io/resource-type: {{ .Values.platform.resourceType | replace "/" "_" | lower | quote }}
cybercloud.io/api-version: {{ .Values.platform.apiVersion | quote }}
cybercloud.io/managed-by: {{ .Values.platform.managedBy | quote }}
{{- end -}}
