// @generated by CyberCloud.ResourceManager.Contracts.Generation.TypeScriptEmitter — DO NOT EDIT.
// Generated from the published OpenAPI document — docs/plan/21 § Generation's one hop.
// ./build.sh Generate overwrites this file and ./build.sh Architecture fails on a
// difference. docs/plan/03 § Assembly graph rules, rule 6.

import type { ApiResponse, ApiTransport, Page, PageRequest } from './transport';
import type {
  AnalyticsClickhouseClustersData,
  AnalyticsClickhouseClustersListKeysResult,
  AnalyticsClickhouseClustersResource,
  CacheRedisData,
  CacheRedisListKeysResult,
  CacheRedisResource,
  ContainerRegistryRegistriesData,
  ContainerRegistryRegistriesListCredentialsResult,
  ContainerRegistryRegistriesResource,
  ContainerServiceManagedClustersAgentPoolsData,
  ContainerServiceManagedClustersAgentPoolsResource,
  ContainerServiceManagedClustersData,
  ContainerServiceManagedClustersListCredentialsResult,
  ContainerServiceManagedClustersResource,
  DBforMySQLServersData,
  DBforMySQLServersListKeysResult,
  DBforMySQLServersResource,
  DBforPostgreSQLServersData,
  DBforPostgreSQLServersListKeysResult,
  DBforPostgreSQLServersResource,
  DocumentDBAccountsData,
  DocumentDBAccountsListKeysResult,
  DocumentDBAccountsResource,
  MessagingKafkaClustersData,
  MessagingKafkaClustersListKeysResult,
  MessagingKafkaClustersResource,
  MessagingNatsClustersData,
  MessagingNatsClustersListKeysResult,
  MessagingNatsClustersResource,
  MessagingRabbitmqClustersData,
  MessagingRabbitmqClustersListKeysResult,
  MessagingRabbitmqClustersResource,
  MonitorWorkspacesData,
  MonitorWorkspacesListKeysResult,
  MonitorWorkspacesResource,
  NetworkPublicIpAddressesData,
  NetworkPublicIpAddressesResource,
  NetworkPublicIpAddressesShowAllocationResult,
  NetworkVirtualNetworksData,
  NetworkVirtualNetworksLoadBalancersData,
  NetworkVirtualNetworksLoadBalancersResource,
  NetworkVirtualNetworksLoadBalancersShowBackendsResult,
  NetworkVirtualNetworksResource,
  NetworkVirtualNetworksSecurityGroupsData,
  NetworkVirtualNetworksSecurityGroupsResource,
  NetworkVirtualNetworksSecurityGroupsShowEffectiveRulesResult,
  NetworkVirtualNetworksShowIsolationResult,
  NetworkVirtualNetworksSubnetsData,
  NetworkVirtualNetworksSubnetsListAddressUsageResult,
  NetworkVirtualNetworksSubnetsResource,
  ResourceGroupCreateContent,
  SampleWidgetsData,
  SampleWidgetsPingContent,
  SampleWidgetsPingResult,
  SampleWidgetsResource,
  ScopeResource,
  SearchServicesData,
  SearchServicesListKeysResult,
  SearchServicesResource,
  StorageAccountsBucketsData,
  StorageAccountsBucketsResource,
  StorageAccountsBucketsStatsResult,
  StorageAccountsData,
  StorageAccountsListKeysResult,
  StorageAccountsResource,
  SubscriptionCreateContent,
  TerminalConsolesConnectResult,
  TerminalConsolesData,
  TerminalConsolesResource,
  TerminalConsolesTerminateResult,
} from './models';

/** The api-version this client was generated at. */
export const generatedApiVersion = '2026-08-01' as const;

/**
 * The public REST API, typed.
 *
 * ⚠ Every method builds a path and hands it to the transport. Authentication, retries and
 * error mapping are the transport's, which is the portal's — portal/README.md § Rules:
 * "The portal has no privileged path. It calls the same public REST API as the CLI, with
 * the same token."
 */
export class CyberCloudApi {
  constructor(private readonly transport: ApiTransport) {}
  /** Reads one tenant. */
  getTenant(tenantId: string): Promise<ApiResponse<ScopeResource>> {
    return this.transport.send<ScopeResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}` });
  }

  // ⚠ There is no createTenant, and the absence is the contract. A request's tenant
  // is resolved from its token, so a call creating another tenant carries a token
  // that is not that tenant's and is refused before routing runs.

  /** Reads one subscription. */
  getSubscription(tenantId: string, subscriptionId: string): Promise<ApiResponse<ScopeResource>> {
    return this.transport.send<ScopeResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}` });
  }

  /** Creates one subscription, or returns the existing one unchanged. */
  /** ⚠ 201 the first time and 200 on a repeat, and no operation to poll. */
  createSubscription(tenantId: string, subscriptionId: string, content: SubscriptionCreateContent): Promise<ApiResponse<ScopeResource>> {
    return this.transport.send<ScopeResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}`, body: content });
  }

  /** Reads one resource group. */
  getResourceGroup(tenantId: string, subscriptionId: string, resourceGroupName: string): Promise<ApiResponse<ScopeResource>> {
    return this.transport.send<ScopeResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}` });
  }

  /** Creates one resource group, or returns the existing one unchanged. */
  /** ⚠ 201 the first time and 200 on a repeat, and no operation to poll. */
  createResourceGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, content: ResourceGroupCreateContent): Promise<ApiResponse<ScopeResource>> {
    return this.transport.send<ScopeResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}`, body: content });
  }

  /** Reads one ClickHouse cluster. */
  getClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<AnalyticsClickhouseClustersResource>> {
    return this.transport.send<AnalyticsClickhouseClustersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one ClickHouse cluster. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: AnalyticsClickhouseClustersData): Promise<ApiResponse<AnalyticsClickhouseClustersResource>> {
    return this.transport.send<AnalyticsClickhouseClustersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one ClickHouse cluster. A merge patch: what is not set is not changed. */
  updateClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<AnalyticsClickhouseClustersData>): Promise<ApiResponse<AnalyticsClickhouseClustersResource>> {
    return this.transport.send<AnalyticsClickhouseClustersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one ClickHouse cluster. ⚠ Permanent: this type declares no soft-delete window. */
  deleteClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the ClickHouse clusters in a resource group. ⚠ A short page never means "that is all there is". */
  listClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<AnalyticsClickhouseClustersResource>>> {
    return this.transport.send<Page<AnalyticsClickhouseClustersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysClickHouseCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<AnalyticsClickhouseClustersListKeysResult>> {
    return this.transport.send<AnalyticsClickhouseClustersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Analytics/clickhouseClusters/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one Valkey cache. */
  getValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<CacheRedisResource>> {
    return this.transport.send<CacheRedisResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Valkey cache. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: CacheRedisData): Promise<ApiResponse<CacheRedisResource>> {
    return this.transport.send<CacheRedisResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Valkey cache. A merge patch: what is not set is not changed. */
  updateValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<CacheRedisData>): Promise<ApiResponse<CacheRedisResource>> {
    return this.transport.send<CacheRedisResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Valkey cache. ⚠ Permanent: this type declares no soft-delete window. */
  deleteValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Valkey caches in a resource group. ⚠ A short page never means "that is all there is". */
  listValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<CacheRedisResource>>> {
    return this.transport.send<Page<CacheRedisResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysValkeyCache(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<CacheRedisListKeysResult>> {
    return this.transport.send<CacheRedisListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Cache/redis/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one Container registry. */
  getContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<ContainerRegistryRegistriesResource>> {
    return this.transport.send<ContainerRegistryRegistriesResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Container registry. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: ContainerRegistryRegistriesData): Promise<ApiResponse<ContainerRegistryRegistriesResource>> {
    return this.transport.send<ContainerRegistryRegistriesResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Container registry. A merge patch: what is not set is not changed. */
  updateContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<ContainerRegistryRegistriesData>): Promise<ApiResponse<ContainerRegistryRegistriesResource>> {
    return this.transport.send<ContainerRegistryRegistriesResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Container registry. ⚠ Recoverable for 7 day(s). */
  deleteContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Container registries in a resource group. ⚠ A short page never means "that is all there is". */
  listContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<ContainerRegistryRegistriesResource>>> {
    return this.transport.send<Page<ContainerRegistryRegistriesResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listCredentials — permission 'listCredentials'. ⚠ The response carries secret material. */
  listCredentialsContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<ContainerRegistryRegistriesListCredentialsResult>> {
    return this.transport.send<ContainerRegistryRegistriesListCredentialsResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}/listCredentials` });
  }

  /** purge — permission 'purge'. ⚠ Long-running. */
  purgeContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}/purge` });
  }

  /** restore — permission 'write'. ⚠ Long-running. */
  restoreContainerRegistry(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerRegistry/registries/${CyberCloudApi.segment(resourceName)}/restore` });
  }

  /** Reads one Managed Kubernetes cluster. */
  getManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<ContainerServiceManagedClustersResource>> {
    return this.transport.send<ContainerServiceManagedClustersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Managed Kubernetes cluster. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: ContainerServiceManagedClustersData): Promise<ApiResponse<ContainerServiceManagedClustersResource>> {
    return this.transport.send<ContainerServiceManagedClustersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Managed Kubernetes cluster. A merge patch: what is not set is not changed. */
  updateManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<ContainerServiceManagedClustersData>): Promise<ApiResponse<ContainerServiceManagedClustersResource>> {
    return this.transport.send<ContainerServiceManagedClustersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Managed Kubernetes cluster. ⚠ Permanent: this type declares no soft-delete window. */
  deleteManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Managed Kubernetes clusters in a resource group. ⚠ A short page never means "that is all there is". */
  listManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<ContainerServiceManagedClustersResource>>> {
    return this.transport.send<Page<ContainerServiceManagedClustersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listCredentials — permission 'listCredentials'. ⚠ The response carries secret material. */
  listCredentialsManagedKubernetesCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<ContainerServiceManagedClustersListCredentialsResult>> {
    return this.transport.send<ContainerServiceManagedClustersListCredentialsResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(resourceName)}/listCredentials` });
  }

  /** Reads one Node pool. */
  getNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, resourceName: string): Promise<ApiResponse<ContainerServiceManagedClustersAgentPoolsResource>> {
    return this.transport.send<ContainerServiceManagedClustersAgentPoolsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Node pool. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, resourceName: string, data: ContainerServiceManagedClustersAgentPoolsData): Promise<ApiResponse<ContainerServiceManagedClustersAgentPoolsResource>> {
    return this.transport.send<ContainerServiceManagedClustersAgentPoolsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Node pool. A merge patch: what is not set is not changed. */
  updateNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, resourceName: string, data: Partial<ContainerServiceManagedClustersAgentPoolsData>): Promise<ApiResponse<ContainerServiceManagedClustersAgentPoolsResource>> {
    return this.transport.send<ContainerServiceManagedClustersAgentPoolsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Node pool. ⚠ Permanent: this type declares no soft-delete window. */
  deleteNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Node pools in a resource group. ⚠ A short page never means "that is all there is". */
  listNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, page: PageRequest = {}): Promise<ApiResponse<Page<ContainerServiceManagedClustersAgentPoolsResource>>> {
    return this.transport.send<Page<ContainerServiceManagedClustersAgentPoolsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools`, query: CyberCloudApi.pageQuery(page) });
  }

  /** upgradeNodeImage — permission 'write'. ⚠ Long-running. */
  upgradeNodeImageNodePool(tenantId: string, subscriptionId: string, resourceGroupName: string, managedClustersName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.ContainerService/managedClusters/${CyberCloudApi.segment(managedClustersName)}/agentPools/${CyberCloudApi.segment(resourceName)}/upgradeNodeImage` });
  }

  /** Reads one MariaDB server. */
  getMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DBforMySQLServersResource>> {
    return this.transport.send<DBforMySQLServersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one MariaDB server. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: DBforMySQLServersData): Promise<ApiResponse<DBforMySQLServersResource>> {
    return this.transport.send<DBforMySQLServersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one MariaDB server. A merge patch: what is not set is not changed. */
  updateMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<DBforMySQLServersData>): Promise<ApiResponse<DBforMySQLServersResource>> {
    return this.transport.send<DBforMySQLServersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one MariaDB server. ⚠ Recoverable for 7 day(s). */
  deleteMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the MariaDB servers in a resource group. ⚠ A short page never means "that is all there is". */
  listMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<DBforMySQLServersResource>>> {
    return this.transport.send<Page<DBforMySQLServersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DBforMySQLServersListKeysResult>> {
    return this.transport.send<DBforMySQLServersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** purge — permission 'purge'. ⚠ Long-running. */
  purgeMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}/purge` });
  }

  /** restore — permission 'write'. ⚠ Long-running. */
  restoreMariaDBServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforMySQL/servers/${CyberCloudApi.segment(resourceName)}/restore` });
  }

  /** Reads one PostgreSQL server. */
  getPostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DBforPostgreSQLServersResource>> {
    return this.transport.send<DBforPostgreSQLServersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one PostgreSQL server. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdatePostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: DBforPostgreSQLServersData): Promise<ApiResponse<DBforPostgreSQLServersResource>> {
    return this.transport.send<DBforPostgreSQLServersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one PostgreSQL server. A merge patch: what is not set is not changed. */
  updatePostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<DBforPostgreSQLServersData>): Promise<ApiResponse<DBforPostgreSQLServersResource>> {
    return this.transport.send<DBforPostgreSQLServersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one PostgreSQL server. ⚠ Recoverable for 7 day(s). */
  deletePostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the PostgreSQL servers in a resource group. ⚠ A short page never means "that is all there is". */
  listPostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<DBforPostgreSQLServersResource>>> {
    return this.transport.send<Page<DBforPostgreSQLServersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysPostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DBforPostgreSQLServersListKeysResult>> {
    return this.transport.send<DBforPostgreSQLServersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** purge — permission 'purge'. ⚠ Long-running. */
  purgePostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}/purge` });
  }

  /** restore — permission 'write'. ⚠ Long-running. */
  restorePostgreSQLServer(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DBforPostgreSQL/servers/${CyberCloudApi.segment(resourceName)}/restore` });
  }

  /** Reads one Document database account. */
  getDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DocumentDBAccountsResource>> {
    return this.transport.send<DocumentDBAccountsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Document database account. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: DocumentDBAccountsData): Promise<ApiResponse<DocumentDBAccountsResource>> {
    return this.transport.send<DocumentDBAccountsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Document database account. A merge patch: what is not set is not changed. */
  updateDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<DocumentDBAccountsData>): Promise<ApiResponse<DocumentDBAccountsResource>> {
    return this.transport.send<DocumentDBAccountsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Document database account. ⚠ Permanent: this type declares no soft-delete window. */
  deleteDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Document database accounts in a resource group. ⚠ A short page never means "that is all there is". */
  listDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<DocumentDBAccountsResource>>> {
    return this.transport.send<Page<DocumentDBAccountsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysDocumentDatabaseAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<DocumentDBAccountsListKeysResult>> {
    return this.transport.send<DocumentDBAccountsListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.DocumentDB/accounts/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one Kafka cluster. */
  getKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingKafkaClustersResource>> {
    return this.transport.send<MessagingKafkaClustersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Kafka cluster. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: MessagingKafkaClustersData): Promise<ApiResponse<MessagingKafkaClustersResource>> {
    return this.transport.send<MessagingKafkaClustersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Kafka cluster. A merge patch: what is not set is not changed. */
  updateKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<MessagingKafkaClustersData>): Promise<ApiResponse<MessagingKafkaClustersResource>> {
    return this.transport.send<MessagingKafkaClustersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Kafka cluster. ⚠ Permanent: this type declares no soft-delete window. */
  deleteKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Kafka clusters in a resource group. ⚠ A short page never means "that is all there is". */
  listKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<MessagingKafkaClustersResource>>> {
    return this.transport.send<Page<MessagingKafkaClustersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysKafkaCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingKafkaClustersListKeysResult>> {
    return this.transport.send<MessagingKafkaClustersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/kafkaClusters/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one NATS cluster. */
  getNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingNatsClustersResource>> {
    return this.transport.send<MessagingNatsClustersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one NATS cluster. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: MessagingNatsClustersData): Promise<ApiResponse<MessagingNatsClustersResource>> {
    return this.transport.send<MessagingNatsClustersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one NATS cluster. A merge patch: what is not set is not changed. */
  updateNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<MessagingNatsClustersData>): Promise<ApiResponse<MessagingNatsClustersResource>> {
    return this.transport.send<MessagingNatsClustersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one NATS cluster. ⚠ Permanent: this type declares no soft-delete window. */
  deleteNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the NATS clusters in a resource group. ⚠ A short page never means "that is all there is". */
  listNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<MessagingNatsClustersResource>>> {
    return this.transport.send<Page<MessagingNatsClustersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysNATSCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingNatsClustersListKeysResult>> {
    return this.transport.send<MessagingNatsClustersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/natsClusters/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one RabbitMQ cluster. */
  getRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingRabbitmqClustersResource>> {
    return this.transport.send<MessagingRabbitmqClustersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one RabbitMQ cluster. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: MessagingRabbitmqClustersData): Promise<ApiResponse<MessagingRabbitmqClustersResource>> {
    return this.transport.send<MessagingRabbitmqClustersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one RabbitMQ cluster. A merge patch: what is not set is not changed. */
  updateRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<MessagingRabbitmqClustersData>): Promise<ApiResponse<MessagingRabbitmqClustersResource>> {
    return this.transport.send<MessagingRabbitmqClustersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one RabbitMQ cluster. ⚠ Permanent: this type declares no soft-delete window. */
  deleteRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the RabbitMQ clusters in a resource group. ⚠ A short page never means "that is all there is". */
  listRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<MessagingRabbitmqClustersResource>>> {
    return this.transport.send<Page<MessagingRabbitmqClustersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysRabbitMQCluster(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MessagingRabbitmqClustersListKeysResult>> {
    return this.transport.send<MessagingRabbitmqClustersListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Messaging/rabbitmqClusters/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one Monitor workspace. */
  getMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MonitorWorkspacesResource>> {
    return this.transport.send<MonitorWorkspacesResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Monitor workspace. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: MonitorWorkspacesData): Promise<ApiResponse<MonitorWorkspacesResource>> {
    return this.transport.send<MonitorWorkspacesResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Monitor workspace. A merge patch: what is not set is not changed. */
  updateMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<MonitorWorkspacesData>): Promise<ApiResponse<MonitorWorkspacesResource>> {
    return this.transport.send<MonitorWorkspacesResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Monitor workspace. ⚠ Recoverable for 7 day(s). */
  deleteMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Monitor workspaces in a resource group. ⚠ A short page never means "that is all there is". */
  listMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<MonitorWorkspacesResource>>> {
    return this.transport.send<Page<MonitorWorkspacesResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<MonitorWorkspacesListKeysResult>> {
    return this.transport.send<MonitorWorkspacesListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** purge — permission 'purge'. ⚠ Long-running. */
  purgeMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}/purge` });
  }

  /** restore — permission 'write'. ⚠ Long-running. */
  restoreMonitorWorkspace(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Monitor/workspaces/${CyberCloudApi.segment(resourceName)}/restore` });
  }

  /** Reads one Public IP address. */
  getPublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<NetworkPublicIpAddressesResource>> {
    return this.transport.send<NetworkPublicIpAddressesResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Public IP address. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdatePublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: NetworkPublicIpAddressesData): Promise<ApiResponse<NetworkPublicIpAddressesResource>> {
    return this.transport.send<NetworkPublicIpAddressesResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Public IP address. A merge patch: what is not set is not changed. */
  updatePublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<NetworkPublicIpAddressesData>): Promise<ApiResponse<NetworkPublicIpAddressesResource>> {
    return this.transport.send<NetworkPublicIpAddressesResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Public IP address. ⚠ Permanent: this type declares no soft-delete window. */
  deletePublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Public IP addresses in a resource group. ⚠ A short page never means "that is all there is". */
  listPublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<NetworkPublicIpAddressesResource>>> {
    return this.transport.send<Page<NetworkPublicIpAddressesResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses`, query: CyberCloudApi.pageQuery(page) });
  }

  /** showAllocation — permission 'read'. */
  showAllocationPublicIPAddress(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<NetworkPublicIpAddressesShowAllocationResult>> {
    return this.transport.send<NetworkPublicIpAddressesShowAllocationResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/publicIpAddresses/${CyberCloudApi.segment(resourceName)}/showAllocation` });
  }

  /** Reads one Virtual network. */
  getVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksResource>> {
    return this.transport.send<NetworkVirtualNetworksResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Virtual network. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: NetworkVirtualNetworksData): Promise<ApiResponse<NetworkVirtualNetworksResource>> {
    return this.transport.send<NetworkVirtualNetworksResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Virtual network. A merge patch: what is not set is not changed. */
  updateVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<NetworkVirtualNetworksData>): Promise<ApiResponse<NetworkVirtualNetworksResource>> {
    return this.transport.send<NetworkVirtualNetworksResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Virtual network. ⚠ Permanent: this type declares no soft-delete window. */
  deleteVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Virtual networks in a resource group. ⚠ A short page never means "that is all there is". */
  listVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<NetworkVirtualNetworksResource>>> {
    return this.transport.send<Page<NetworkVirtualNetworksResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks`, query: CyberCloudApi.pageQuery(page) });
  }

  /** showIsolation — permission 'read'. */
  showIsolationVirtualNetwork(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksShowIsolationResult>> {
    return this.transport.send<NetworkVirtualNetworksShowIsolationResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(resourceName)}/showIsolation` });
  }

  /** Reads one Load balancer. */
  getLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksLoadBalancersResource>> {
    return this.transport.send<NetworkVirtualNetworksLoadBalancersResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Load balancer. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: NetworkVirtualNetworksLoadBalancersData): Promise<ApiResponse<NetworkVirtualNetworksLoadBalancersResource>> {
    return this.transport.send<NetworkVirtualNetworksLoadBalancersResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Load balancer. A merge patch: what is not set is not changed. */
  updateLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: Partial<NetworkVirtualNetworksLoadBalancersData>): Promise<ApiResponse<NetworkVirtualNetworksLoadBalancersResource>> {
    return this.transport.send<NetworkVirtualNetworksLoadBalancersResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Load balancer. ⚠ Permanent: this type declares no soft-delete window. */
  deleteLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Load balancers in a resource group. ⚠ A short page never means "that is all there is". */
  listLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, page: PageRequest = {}): Promise<ApiResponse<Page<NetworkVirtualNetworksLoadBalancersResource>>> {
    return this.transport.send<Page<NetworkVirtualNetworksLoadBalancersResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers`, query: CyberCloudApi.pageQuery(page) });
  }

  /** showBackends — permission 'read'. */
  showBackendsLoadBalancer(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksLoadBalancersShowBackendsResult>> {
    return this.transport.send<NetworkVirtualNetworksLoadBalancersShowBackendsResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/loadBalancers/${CyberCloudApi.segment(resourceName)}/showBackends` });
  }

  /** Reads one Security group. */
  getSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksSecurityGroupsResource>> {
    return this.transport.send<NetworkVirtualNetworksSecurityGroupsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Security group. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: NetworkVirtualNetworksSecurityGroupsData): Promise<ApiResponse<NetworkVirtualNetworksSecurityGroupsResource>> {
    return this.transport.send<NetworkVirtualNetworksSecurityGroupsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Security group. A merge patch: what is not set is not changed. */
  updateSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: Partial<NetworkVirtualNetworksSecurityGroupsData>): Promise<ApiResponse<NetworkVirtualNetworksSecurityGroupsResource>> {
    return this.transport.send<NetworkVirtualNetworksSecurityGroupsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Security group. ⚠ Permanent: this type declares no soft-delete window. */
  deleteSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Security groups in a resource group. ⚠ A short page never means "that is all there is". */
  listSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, page: PageRequest = {}): Promise<ApiResponse<Page<NetworkVirtualNetworksSecurityGroupsResource>>> {
    return this.transport.send<Page<NetworkVirtualNetworksSecurityGroupsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups`, query: CyberCloudApi.pageQuery(page) });
  }

  /** showEffectiveRules — permission 'read'. */
  showEffectiveRulesSecurityGroup(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksSecurityGroupsShowEffectiveRulesResult>> {
    return this.transport.send<NetworkVirtualNetworksSecurityGroupsShowEffectiveRulesResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/securityGroups/${CyberCloudApi.segment(resourceName)}/showEffectiveRules` });
  }

  /** Reads one Subnet. */
  getSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksSubnetsResource>> {
    return this.transport.send<NetworkVirtualNetworksSubnetsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Subnet. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: NetworkVirtualNetworksSubnetsData): Promise<ApiResponse<NetworkVirtualNetworksSubnetsResource>> {
    return this.transport.send<NetworkVirtualNetworksSubnetsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Subnet. A merge patch: what is not set is not changed. */
  updateSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string, data: Partial<NetworkVirtualNetworksSubnetsData>): Promise<ApiResponse<NetworkVirtualNetworksSubnetsResource>> {
    return this.transport.send<NetworkVirtualNetworksSubnetsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Subnet. ⚠ Permanent: this type declares no soft-delete window. */
  deleteSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Subnets in a resource group. ⚠ A short page never means "that is all there is". */
  listSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, page: PageRequest = {}): Promise<ApiResponse<Page<NetworkVirtualNetworksSubnetsResource>>> {
    return this.transport.send<Page<NetworkVirtualNetworksSubnetsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listAddressUsage — permission 'read'. */
  listAddressUsageSubnet(tenantId: string, subscriptionId: string, resourceGroupName: string, virtualNetworksName: string, resourceName: string): Promise<ApiResponse<NetworkVirtualNetworksSubnetsListAddressUsageResult>> {
    return this.transport.send<NetworkVirtualNetworksSubnetsListAddressUsageResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Network/virtualNetworks/${CyberCloudApi.segment(virtualNetworksName)}/subnets/${CyberCloudApi.segment(resourceName)}/listAddressUsage` });
  }

  /** Reads one Widget. */
  getWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<SampleWidgetsResource>> {
    return this.transport.send<SampleWidgetsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Widget. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: SampleWidgetsData): Promise<ApiResponse<SampleWidgetsResource>> {
    return this.transport.send<SampleWidgetsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Widget. A merge patch: what is not set is not changed. */
  updateWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<SampleWidgetsData>): Promise<ApiResponse<SampleWidgetsResource>> {
    return this.transport.send<SampleWidgetsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Widget. ⚠ Permanent: this type declares no soft-delete window. */
  deleteWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Widgets in a resource group. ⚠ A short page never means "that is all there is". */
  listWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<SampleWidgetsResource>>> {
    return this.transport.send<Page<SampleWidgetsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets`, query: CyberCloudApi.pageQuery(page) });
  }

  /** ping — permission 'write'. */
  pingWidget(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, content: SampleWidgetsPingContent): Promise<ApiResponse<SampleWidgetsPingResult>> {
    return this.transport.send<SampleWidgetsPingResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Sample/widgets/${CyberCloudApi.segment(resourceName)}/ping`, body: content });
  }

  /** Reads one OpenSearch service. */
  getOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<SearchServicesResource>> {
    return this.transport.send<SearchServicesResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one OpenSearch service. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: SearchServicesData): Promise<ApiResponse<SearchServicesResource>> {
    return this.transport.send<SearchServicesResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one OpenSearch service. A merge patch: what is not set is not changed. */
  updateOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<SearchServicesData>): Promise<ApiResponse<SearchServicesResource>> {
    return this.transport.send<SearchServicesResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one OpenSearch service. ⚠ Permanent: this type declares no soft-delete window. */
  deleteOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the OpenSearch services in a resource group. ⚠ A short page never means "that is all there is". */
  listOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<SearchServicesResource>>> {
    return this.transport.send<Page<SearchServicesResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysOpenSearchService(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<SearchServicesListKeysResult>> {
    return this.transport.send<SearchServicesListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Search/services/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** Reads one Storage account. */
  getStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<StorageAccountsResource>> {
    return this.transport.send<StorageAccountsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Storage account. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: StorageAccountsData): Promise<ApiResponse<StorageAccountsResource>> {
    return this.transport.send<StorageAccountsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Storage account. A merge patch: what is not set is not changed. */
  updateStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<StorageAccountsData>): Promise<ApiResponse<StorageAccountsResource>> {
    return this.transport.send<StorageAccountsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Storage account. ⚠ Recoverable for 7 day(s). */
  deleteStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Storage accounts in a resource group. ⚠ A short page never means "that is all there is". */
  listStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<StorageAccountsResource>>> {
    return this.transport.send<Page<StorageAccountsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts`, query: CyberCloudApi.pageQuery(page) });
  }

  /** listKeys — permission 'listKeys'. ⚠ The response carries secret material. */
  listKeysStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<StorageAccountsListKeysResult>> {
    return this.transport.send<StorageAccountsListKeysResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}/listKeys` });
  }

  /** purge — permission 'purge'. ⚠ Long-running. */
  purgeStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}/purge` });
  }

  /** restore — permission 'write'. ⚠ Long-running. */
  restoreStorageAccount(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<unknown>> {
    return this.transport.send<unknown>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(resourceName)}/restore` });
  }

  /** Reads one Bucket. */
  getBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, resourceName: string): Promise<ApiResponse<StorageAccountsBucketsResource>> {
    return this.transport.send<StorageAccountsBucketsResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Bucket. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, resourceName: string, data: StorageAccountsBucketsData): Promise<ApiResponse<StorageAccountsBucketsResource>> {
    return this.transport.send<StorageAccountsBucketsResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Bucket. A merge patch: what is not set is not changed. */
  updateBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, resourceName: string, data: Partial<StorageAccountsBucketsData>): Promise<ApiResponse<StorageAccountsBucketsResource>> {
    return this.transport.send<StorageAccountsBucketsResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Bucket. ⚠ Permanent: this type declares no soft-delete window. */
  deleteBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Buckets in a resource group. ⚠ A short page never means "that is all there is". */
  listBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, page: PageRequest = {}): Promise<ApiResponse<Page<StorageAccountsBucketsResource>>> {
    return this.transport.send<Page<StorageAccountsBucketsResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets`, query: CyberCloudApi.pageQuery(page) });
  }

  /** stats — permission 'read'. */
  statsBucket(tenantId: string, subscriptionId: string, resourceGroupName: string, accountsName: string, resourceName: string): Promise<ApiResponse<StorageAccountsBucketsStatsResult>> {
    return this.transport.send<StorageAccountsBucketsStatsResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Storage/accounts/${CyberCloudApi.segment(accountsName)}/buckets/${CyberCloudApi.segment(resourceName)}/stats` });
  }

  /** Reads one Cloud terminal. */
  getCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<TerminalConsolesResource>> {
    return this.transport.send<TerminalConsolesResource>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}` });
  }

  /** Creates or replaces one Cloud terminal. ⚠ Long-running: the response is a 202 carrying operationUrl. */
  createOrUpdateCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: TerminalConsolesData): Promise<ApiResponse<TerminalConsolesResource>> {
    return this.transport.send<TerminalConsolesResource>({ method: 'PUT', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Amends one Cloud terminal. A merge patch: what is not set is not changed. */
  updateCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string, data: Partial<TerminalConsolesData>): Promise<ApiResponse<TerminalConsolesResource>> {
    return this.transport.send<TerminalConsolesResource>({ method: 'PATCH', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}`, body: data });
  }

  /** Deletes one Cloud terminal. ⚠ Permanent: this type declares no soft-delete window. */
  deleteCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<void>> {
    return this.transport.send<void>({ method: 'DELETE', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}` });
  }

  /** One page of the Cloud terminals in a resource group. ⚠ A short page never means "that is all there is". */
  listCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, page: PageRequest = {}): Promise<ApiResponse<Page<TerminalConsolesResource>>> {
    return this.transport.send<Page<TerminalConsolesResource>>({ method: 'GET', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles`, query: CyberCloudApi.pageQuery(page) });
  }

  /** connect — permission 'connect'. */
  connectCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<TerminalConsolesConnectResult>> {
    return this.transport.send<TerminalConsolesConnectResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}/connect` });
  }

  /** terminate — permission 'connect'. */
  terminateCloudTerminal(tenantId: string, subscriptionId: string, resourceGroupName: string, resourceName: string): Promise<ApiResponse<TerminalConsolesTerminateResult>> {
    return this.transport.send<TerminalConsolesTerminateResult>({ method: 'POST', path: `/tenants/${CyberCloudApi.segment(tenantId)}/subscriptions/${CyberCloudApi.segment(subscriptionId)}/resourceGroups/${CyberCloudApi.segment(resourceGroupName)}/providers/CyberCloud.Terminal/consoles/${CyberCloudApi.segment(resourceName)}/terminate` });
  }

  /** Percent-encodes one path segment. ⚠ A name is caller data and a '/' in one would forge a path. */
  private static segment(value: string): string {
    return encodeURIComponent(value);
  }

  /**
   * The paging query, with only what the caller actually set.
   *
   * ⚠ The names carry their `$`, which is what the gateway reads. A gateway IGNORES a
   * query parameter it does not recognise, so a misspelling here is not an error
   * anywhere — it is a 200 holding page one, for ever.
   */
  private static pageQuery(page: PageRequest): Record<string, string> {
    const query: Record<string, string> = {};

    if (page.top !== undefined) {
      query['$top'] = String(page.top);
    }

    if (page.skipToken !== undefined) {
      query['$skipToken'] = page.skipToken;
    }

    return query;
  }
}
