// @generated by CyberCloud.ResourceManager.Contracts.Generation.TypeScriptEmitter — DO NOT EDIT.
// Generated from the published OpenAPI document — docs/plan/21 § Generation's one hop.
// ./build.sh Generate overwrites this file and ./build.sh Architecture fails on a
// difference. docs/plan/03 § Assembly graph rules, rule 6.

/** One request the client wants made. */
export interface ApiRequest {
  /** The HTTP method. */
  readonly method: 'GET' | 'PUT' | 'PATCH' | 'POST' | 'DELETE';

  /**
   * The path, relative to the platform endpoint, with every placeholder already filled and
   * every segment already encoded.
   */
  readonly path: string;

  /**
   * The query parameters, unencoded. ⚠ `api-version` is NOT here: the transport puts it on
   * every request, exactly as the .NET SDK's ApiVersionHandler does, so no call site can
   * forget it and no two call sites can disagree about it.
   */
  readonly query?: Readonly<Record<string, string>>;

  /** The request body, already a plain object. Absent on a read. */
  readonly body?: unknown;
}

/** What came back. */
export interface ApiResponse<T> {
  /** The HTTP status. ⚠ A scope PUT answers 201 the first time and 200 on a repeat. */
  readonly status: number;

  /** The parsed body. */
  readonly value: T;

  /**
   * The operation URL a 202 returned, from the Azure-AsyncOperation header, or undefined.
   * docs/plan/10 § Long-running operations, over HTTP.
   */
  readonly operationUrl?: string;
}

/**
 * How the client reaches the platform.
 *
 * ⚠ Supplied by the portal rather than generated. The portal calls the same public REST API
 * as `cyc`, with the same token (portal/README.md § Rules), and its bearer token, its
 * interceptors and its error handling belong to the app rather than to a file that is
 * overwritten on every build. Generating the fetch here would put authentication in
 * generated code and give the portal a second HTTP client beside the one it already has.
 */
export interface ApiTransport {
  /** Makes one request. */
  send<T>(request: ApiRequest): Promise<ApiResponse<T>>;
}

/** One page of a collection — docs/plan/08 § The read path. */
export interface Page<T> {
  /** The resources on this page, ordered by id. */
  readonly value: readonly T[];

  /**
   * The absolute URL of the next page, absent on the last one.
   *
   * ⚠ A short page never means "that is all there is". A listing runs a permission check per
   * member and the page is clamped, and the envelope deliberately carries no count — a total
   * would say how many resources exist that the caller may not see. Stop when `nextLink` is
   * absent, never when a page is smaller than you asked for.
   */
  readonly nextLink?: string;
}

/** How many resources a listing may examine, and where to resume. */
export interface PageRequest {
  /**
   * ⚠ A cap the platform clamps and not a promise: the filter runs once per member, so this
   * bounds the work and not the number of results.
   */
  readonly top?: number;

  /** Take it from the previous page's `nextLink` rather than constructing one. */
  readonly skipToken?: string;
}
/** The api-version every request this client makes is sent at. */
export const apiVersion = '2026-08-01' as const;
