using CyberCloud.ResourceManager.Contracts.Registry;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>One chart whose annotation block was regenerated from the registry.</summary>
/// <param name="Chart">The chart, relative to <c>charts/</c> — <c>managed/postgres</c>.</param>
/// <param name="ResourceType">The type it is the configuration surface of.</param>
/// <param name="ApiVersion">Which api-version's body was emitted.</param>
/// <param name="File">The file, relative to <c>charts/</c>. ⚠ Never an absolute path.</param>
/// <param name="Published">Whether the file was already checked in.</param>
/// <param name="Drifted">Whether the regenerated bytes differ from the checked-in ones.</param>
/// <param name="Problems">What could not be described. Normally empty.</param>
/// <param name="PreservedInternalLines">
///     How many lines of <c>@internal</c> region were carried through from the checked-in file
///     untouched. ⚠ Reported so a build log can state the number rather than assert it from memory: the
///     message this feeds used to claim the <c>@internal</c> rows were untouched while the rewrite was
///     deleting one — see the remarks on <see cref="ChartAnnotationEmitter.Rewrite" />.
/// </param>
public sealed record ChartAnnotation(
    string Chart,
    string ResourceType,
    string ApiVersion,
    string File,
    bool Published,
    bool Drifted,
    ImmutableArray<string> Problems,
    int PreservedInternalLines = 0
);

/// <summary>
///     What one chart-annotation run compared.
/// </summary>
/// <param name="Documents">One entry per <i>pair</i> — a registry type and the chart it names.</param>
/// <param name="Unpaired">
///     Managed charts no registry type claims, and registry types naming a chart that is not in the
///     tree. ⚠ Reported rather than counted away: see the remarks on <see cref="ChartSurfaces" />.
/// </param>
/// <param name="ManagedCharts">How many charts sit under <c>charts/managed/</c>.</param>
/// <param name="TypesNamingAChart">How many registry types declare a chart.</param>
public sealed record ChartAnnotationReport(
    ImmutableArray<ChartAnnotation> Documents,
    ImmutableArray<string> Unpaired,
    int ManagedCharts,
    int TypesNamingAChart
) {
    /// <summary>How many registry-to-chart pairs there were to compare.</summary>
    public int Pairs => Documents.Length;

    /// <summary>Whether anything at all is wrong with the pairs that exist.</summary>
    public bool IsClean => Documents.All(x => !x.Drifted && x.Problems.IsEmpty);

    /// <summary>
    ///     Whether the run had nothing to compare — <c>Build.Architecture</c>'s
    ///     <c>GateStatus.Vacuous</c>, in the one form this surface can take it.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>This is the property a caller must not forget to read.</b> A run with no pair is clean
    ///     because it inspected nothing, and <c>build/Build.Charts.cs</c>'s own header says the rule:
    ///     "'Zero charts' and 'zero problems' are not the same news."
    /// </remarks>
    public bool IsVacuous => Documents.IsEmpty;
}

/// <summary>
///     Pairs each registry type with the chart it names, rewrites that chart's annotation block, and
///     says what changed.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>The pairing is <see cref="ResourceTypeRegistration.Chart" />, and today it pairs
///         nothing.</b> One provider is in the tree — <c>CyberCloud.Providers.Sample</c> — and it
///         declares no chart on purpose (its own <c>.csproj</c>: "renders no chart (a ConfigMap is one
///         object, and <c>CyberCloud.Kubernetes.Charts</c> does not exist)"). The one managed chart
///         declares <c>CyberCloud.DBforPostgreSQL/servers</c>, which no C# provider declares — it
///         appears in <c>src/</c> only in test fixtures. So the overlap is zero resource types wide,
///         which is docs/plan/02 § ADR-010's own finding and is exactly why nothing had ever compared
///         the two files.
///     </para>
///     <para>
///         ⚠ <b>Zero pairs is therefore a legitimate state and is reported as
///         <see cref="ChartAnnotationReport.IsVacuous" /> rather than as success.</b> The failure this
///         guards against is the one <c>build/Build.Generate.cs</c> has already had once: a discovery
///         rule that quietly matched nothing, and a target that reported it as a pass with the first
///         provider sitting in the solution. Both halves of the mismatch are named individually in
///         <see cref="ChartAnnotationReport.Unpaired" /> — a chart nothing claims, and a type naming a
///         chart that is not there — so "no pair" always comes with which end is missing.
///     </para>
///     <para>
///         ⚠ <b>Written in place and then reported as drift</b>, the same order and for the same reason
///         as <see cref="OpenApiArtifacts" />: the fix for a red build is <c>git add</c>, and CI, where
///         the checked-in file is the one under test, still goes red on the run that produced the
///         difference.
///     </para>
/// </remarks>
public static class ChartSurfaces {
    /// <summary>The directory, relative to the repository root, the charts are checked in at.</summary>
    public const string DirectoryName = "charts";

    /// <summary>The subtree whose charts are managed services — docs/plan/12 § The pattern, once.</summary>
    public const string ManagedDirectoryName = "managed";

    /// <summary>The <c>Chart.yaml</c> annotation naming the type a chart is the surface of.</summary>
    public const string ResourceTypeAnnotation = "cybercloud.io/resource-type";

    /// <summary>The <c>Chart.yaml</c> annotation naming which api-version's body it carries.</summary>
    public const string ApiVersionAnnotation = "cybercloud.io/api-version";

    /// <summary>
    ///     Regenerates every paired chart's annotation block.
    /// </summary>
    /// <param name="registry">The built provider registry — the single source.</param>
    /// <param name="directory">The repository's <c>charts/</c>.</param>
    /// <param name="write">
    ///     Whether to write. <see langword="false" /> is the check-only mode a gate uses, so that a
    ///     gate never has a side effect on the tree it is inspecting.
    /// </param>
    public static ChartAnnotationReport Generate(
        IProviderRegistry registry,
        string directory,
        bool write
    ) {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentException.ThrowIfNullOrEmpty(directory);

        var produced = new List<ChartAnnotation>();
        var unpaired = new List<string>();
        var claimed = new HashSet<string>(StringComparer.Ordinal);

        var declaring = registry.Types
            .Where(x => x.Chart.Length > 0)
            .OrderBy(x => x.Type.ToString(), StringComparer.Ordinal)
            .ToList();

        foreach (var type in declaring) {
            var chart = type.Chart.Replace('\\', '/').Trim('/');
            var chartDirectory = Path.Combine(directory, chart.Replace('/', Path.DirectorySeparatorChar));
            claimed.Add(chart);

            if (!File.Exists(Path.Combine(chartDirectory, "Chart.yaml"))) {
                unpaired.Add(
                    $"'{type.Type}' names the chart '{chart}' and {DirectoryName}/{chart}/Chart.yaml "
                    + "does not exist. A type that renders a chart nobody can find fails at the first "
                    + "reconcile, and its configuration surface is described nowhere."
                );

                continue;
            }

            produced.Add(Pair(type, chart, chartDirectory, write));
        }

        var managed = ManagedCharts(directory);

        foreach (var chart in managed.Where(x => !claimed.Contains(x))) {
            unpaired.Add(
                $"{DirectoryName}/{chart} is a managed chart and no registry type names it, so its "
                + "@param block is compared against nothing. docs/plan/02 § ADR-010 makes the C# "
                + "ResourceSchema the author of that block; until a provider declares "
                + $"`.Chart(\"{chart}\")`, the file is hand-written and nothing can say whether it "
                + "agrees with any API."
            );
        }

        return new(
            [.. produced.OrderBy(x => x.File, StringComparer.Ordinal)],
            [.. unpaired.OrderBy(x => x, StringComparer.Ordinal)],
            managed.Count,
            declaring.Count
        );
    }

    /// <summary>The report as one line per pair, for a build log.</summary>
    /// <param name="report">The report.</param>
    public static ImmutableArray<string> Describe(ChartAnnotationReport report) {
        ArgumentNullException.ThrowIfNull(report);

        var lines = new List<string> {
            string.Create(
                CultureInfo.InvariantCulture,
                $"{report.ManagedCharts} managed chart(s), {report.TypesNamingAChart} registry type(s) "
                + $"naming a chart, {report.Pairs} pair(s) compared"
            )
        };

        foreach (var annotation in report.Documents) {
            lines.Add(string.Create(
                CultureInfo.InvariantCulture,
                $"  {(annotation.Drifted ? "±" : "=")} {DirectoryName}/{annotation.File} — "
                + $"{annotation.ResourceType} at {annotation.ApiVersion}, "
                + $"{(annotation.Published ? annotation.Drifted ? "differs from the registry" : "unchanged" : "new")}, "
                + $"{annotation.Problems.Length} problem(s)"
            ));
        }

        foreach (var unpaired in report.Unpaired) {
            lines.Add("  ! " + unpaired);
        }

        return [.. lines];
    }

    // ── One pair ──────────────────────────────────────────────────────────────────────────────

    static ChartAnnotation Pair(
        ResourceTypeRegistration type,
        string chart,
        string chartDirectory,
        bool write
    ) {
        var file = chart + "/" + ChartAnnotationEmitter.FileName;
        var path = Path.Combine(chartDirectory, ChartAnnotationEmitter.FileName);
        var annotations = ChartYamlAnnotations(Path.Combine(chartDirectory, "Chart.yaml"));
        var problems = new List<string>();

        annotations.TryGetValue(ResourceTypeAnnotation, out var declaredType);
        annotations.TryGetValue(ApiVersionAnnotation, out var declaredVersion);

        if (!string.Equals(declaredType, type.Type.ToString(), StringComparison.Ordinal)) {
            problems.Add(
                $"{DirectoryName}/{chart}/Chart.yaml says `{ResourceTypeAnnotation}: {declaredType}` and "
                + $"'{type.Type}' is the type that names this chart. The two ends of the pairing "
                + "disagree, so one of them is describing a resource nobody generated."
            );
        }

        var version = type.ApiVersions
            .FirstOrDefault(x => string.Equals(x.Version.Value, declaredVersion, StringComparison.Ordinal));

        if (version.Version.Value.Length == 0) {
            problems.Add(
                $"{DirectoryName}/{chart}/Chart.yaml says `{ApiVersionAnnotation}: {declaredVersion}`, "
                + $"which '{type.Type}' does not declare. An api-version is immutable once published "
                + "(docs/plan/08 § The provider registry), so a chart has to name one that exists — the "
                + $"registry has [{string.Join(", ", type.ApiVersions.Select(x => x.Version.Value))}]."
            );
        }

        if (!File.Exists(path)) {
            problems.Add(
                $"{DirectoryName}/{file} is missing. docs/plan/03 § charts/ makes the annotated "
                + "values.yaml \"the single description of a managed service's configuration surface\", "
                + "and there is nothing to rewrite the block into."
            );
        }

        if (problems.Count > 0) {
            return new(chart, type.Type.ToString(), declaredVersion ?? string.Empty, file, File.Exists(path), false, [.. problems]);
        }

        // ⚠ The registration and not the schema is what says which property is placement. It is empty
        // for a type that declares no RequiresCluster, and this is the only call in the tree that has
        // a ResourceTypeRegistration to read it from — see the remarks on ChartAnnotationEmitter.
        var block = ChartAnnotationEmitter.Emit(version.Schema, type.ClusterIdPointer);

        if (!block.Problems.IsEmpty) {
            return new(chart, type.Type.ToString(), version.Version.Value, file, true, false, block.Problems);
        }

        var existing = File.ReadAllBytes(path);
        var rewrite = ChartAnnotationEmitter.Rewrite(Text(existing), block.Text);

        if (!rewrite.Problems.IsEmpty) {
            return new(
                chart,
                type.Type.ToString(),
                version.Version.Value,
                file,
                true,
                false,
                [.. rewrite.Problems.Select(x => $"{DirectoryName}/{file}:{x}")]
            );
        }

        var bytes = Bytes(rewrite.Text);
        var drifted = !existing.AsSpan().SequenceEqual(bytes);

        if (write && drifted) {
            File.WriteAllBytes(path, bytes);
        }

        return new(
            chart,
            type.Type.ToString(),
            version.Version.Value,
            file,
            true,
            drifted,
            [],
            rewrite.PreservedInternalLines
        );
    }

    // ── The tree ──────────────────────────────────────────────────────────────────────────────

    /// <summary>Every chart under <c>charts/managed/</c>, as a path relative to <c>charts/</c>.</summary>
    /// <remarks>
    ///     ⚠ <b>Matched at any depth, not at a fixed one.</b> <c>build/Build.Generate.cs</c>'s provider
    ///     discovery once tested <c>Parent?.Parent?.Name == "Providers"</c>, found nothing because the
    ///     real layout is one level deeper, and reported success. Depth was the wrong thing to key on
    ///     there and it is the wrong thing to key on here.
    /// </remarks>
    static List<string> ManagedCharts(string directory) {
        var root = Path.Combine(directory, ManagedDirectoryName);

        if (!Directory.Exists(root)) {
            return [];
        }

        return Directory
            .EnumerateFiles(root, "Chart.yaml", SearchOption.AllDirectories)
            .Where(x => !x.Contains(
                Path.DirectorySeparatorChar + "templates" + Path.DirectorySeparatorChar,
                StringComparison.Ordinal
            ))
            .Select(x => Path.GetRelativePath(directory, Path.GetDirectoryName(x)!)
                .Replace(Path.DirectorySeparatorChar, '/'))
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();
    }

    /// <summary>
    ///     The <c>annotations:</c> block of a <c>Chart.yaml</c>.
    /// </summary>
    /// <remarks>
    ///     ⚠ Deliberately the same narrow scan <c>build/Build.Charts.cs</c> uses on this file and not
    ///     the annotated-values reader: a <c>Chart.yaml</c> is Helm's file, it carries block sequences
    ///     the values subset refuses on purpose, and it carries no annotations of ours at all beyond
    ///     these two keys.
    /// </remarks>
    static Dictionary<string, string> ChartYamlAnnotations(string path) {
        var found = new Dictionary<string, string>(StringComparer.Ordinal);
        var section = string.Empty;

        foreach (var line in File.ReadAllLines(path)) {
            if (line.TrimStart().Length == 0 || line.TrimStart()[0] == '#') {
                continue;
            }

            var match = ChartYamlLine.Match(line);

            if (!match.Success) {
                continue;
            }

            var indent = match.Groups["indent"].Value.Length;

            if (indent == 0) {
                section = match.Groups["key"].Value;
                continue;
            }

            if (indent == 2 && string.Equals(section, "annotations", StringComparison.Ordinal)) {
                found[match.Groups["key"].Value] = Unquote(match.Groups["value"].Value.Trim());
            }
        }

        return found;
    }

    static string Unquote(string value) =>
        value.Length >= 2 && (value[0] == '"' || value[0] == '\'') && value[^1] == value[0]
            ? value[1..^1]
            : value;

    static readonly Regex ChartYamlLine =
        new(@"^(?<indent>\s*)(?<key>[A-Za-z0-9._/-]+):[ \t]*(?<value>.*)$", RegexOptions.Compiled);

    // ── Bytes ─────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The one way a values file becomes bytes: UTF-8 with no BOM, LF, one trailing newline.
    /// </summary>
    /// <remarks>
    ///     ⚠ The same three rules <see cref="DerivedSurfaces" /> applies to generated source, and for
    ///     the same reason: this file is byte-compared, so a BOM or a CRLF from a Windows checkout
    ///     would be drift that has nothing to do with the registry.
    /// </remarks>
    static byte[] Bytes(string text) {
        var normalised = text.Replace("\r\n", "\n", StringComparison.Ordinal);

        if (!normalised.EndsWith('\n')) {
            normalised += "\n";
        }

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(normalised);
    }

    static string Text(byte[] bytes) =>
        new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetString(bytes);
}
