using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>What one derived file did.</summary>
/// <param name="Surface">Which of the three — <c>cli</c>, <c>sdk</c> or <c>forms</c>.</param>
/// <param name="FileName">The file, relative to the generated root. ⚠ Never an absolute path.</param>
/// <param name="ApiVersion">The api-version it describes.</param>
/// <param name="Published">Whether a file of that name was already checked in.</param>
/// <param name="Drifted">Whether the regenerated bytes differ from the checked-in ones.</param>
/// <param name="Problems">What the surface's own self-check found. Normally empty.</param>
public sealed record DerivedDocument(
    string Surface,
    string FileName,
    string ApiVersion,
    bool Published,
    bool Drifted,
    ImmutableArray<string> Problems
);

/// <summary>What one derived-surface run produced.</summary>
/// <param name="Documents">One entry per file, ordered by name.</param>
/// <param name="Stale">Checked-in files this run did not produce, ordered by name.</param>
public sealed record DerivedReport(
    ImmutableArray<DerivedDocument> Documents,
    ImmutableArray<string> Stale
) {
    /// <summary>Whether anything at all is wrong.</summary>
    public bool IsClean => Stale.IsEmpty && Documents.All(x => !x.Drifted && x.Problems.IsEmpty);
}

/// <summary>
///     Writes ADR-012's other three surfaces and says what changed.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>Checked in, not under <c>artifacts/</c>, and the reason is the gate.</b>
///         docs/plan/23 § The architecture gates asks that "OpenAPI/CLI/SDK/forms regenerate
///         byte-identically from the registry", and a byte comparison needs a previous copy to
///         compare against. <c>artifacts/</c> is gitignored, so a file written there has no previous
///         copy on a fresh clone and every run would report "new" — a gate that can only ever pass.
///         <see cref="OpenApiArtifacts.DirectoryName" /> is tracked for exactly this reason and these
///         three follow it.
///     </para>
///     <para>
///         <b>A separate root from <c>openapi/</c>, though.</b> docs/plan/10 § Shape makes the gateway
///         serve <c>openapi/</c> as files; the CLI tree, the SDK source and the form schemas are not
///         served to anyone over HTTP, and putting them in the directory the gateway publishes would
///         make the platform's public surface depend on which files a build step happened to leave
///         there.
///     </para>
///     <para>
///         ⚠ <b>No compatibility diff, and that is docs/plan/21 § Generation's design rather than an
///         omission.</b> These are generated <i>from</i> the OpenAPI document, so a breaking change
///         reaches them only through a breaking change to that document — which
///         <see cref="OpenApiCompatibility" /> already fails on. One hop, one gate. A second diff here
///         would re-litigate the same question against a derived artifact whose shape is this
///         repository's business rather than a published contract.
///     </para>
///     <para>
///         ⚠ <b>Nothing is ever deleted</b>, for the same reason <see cref="OpenApiArtifacts" /> never
///         deletes: a file this run did not produce is reported as
///         <see cref="DerivedReport.Stale" /> and left alone.
///     </para>
/// </remarks>
public static class DerivedSurfaces {
    /// <summary>The directory, relative to the repository root, the three surfaces are checked in at.</summary>
    public const string DirectoryName = "generated";

    /// <summary>
    ///     Emits all three surfaces for every document, compares against what is checked in, and
    ///     optionally writes.
    /// </summary>
    /// <param name="documents">The emitted per-version OpenAPI documents, keyed by api-version.</param>
    /// <param name="directory">The generated root.</param>
    /// <param name="write">
    ///     Whether to write. <see langword="false" /> is the check-only mode the <c>Architecture</c>
    ///     gate uses, so a gate never has a side effect on the tree it is inspecting.
    /// </param>
    public static DerivedReport Generate(
        IReadOnlyDictionary<string, JsonObject> documents,
        string directory,
        bool write
    ) {
        ArgumentNullException.ThrowIfNull(documents);
        ArgumentException.ThrowIfNullOrEmpty(directory);

        var produced = new List<DerivedDocument>();
        var expected = new HashSet<string>(StringComparer.Ordinal);

        foreach (var (version, document) in documents.OrderBy(x => x.Key, StringComparer.Ordinal)) {
            var cli = CliEmitter.Emit(document);
            var forms = FormsEmitter.Emit(document);
            var sdk = SdkEmitter.Emit(document);

            produced.Add(Write(
                CliEmitter.DirectoryName,
                CliEmitter.FileNameOf(version),
                version,
                DeterministicJson.ToBytes(cli),
                CliProblems(cli, document),
                directory,
                write,
                expected
            ));

            produced.Add(Write(
                FormsEmitter.DirectoryName,
                FormsEmitter.FileNameOf(version),
                version,
                DeterministicJson.ToBytes(forms),
                FormProblems(forms),
                directory,
                write,
                expected
            ));

            produced.Add(Write(
                SdkEmitter.DirectoryName,
                SdkEmitter.FileNameOf(version),
                version,
                // ⚠ The same byte rules as the JSON surfaces: UTF-8 with no BOM, LF, one trailing
                // newline. A generated .cs file is diffed exactly as a generated .json file is, and a
                // CRLF from Environment.NewLine would make CI red on Windows and green here.
                Text(sdk),
                SdkProblems(sdk),
                directory,
                write,
                expected
            ));
        }

        var root = new DirectoryInfo(directory);

        var stale = root.Exists
            ? root.EnumerateFiles("*", SearchOption.AllDirectories)
                .Select(x => Relative(directory, x.FullName))
                .Where(x => !expected.Contains(x) && !x.EndsWith(".md", StringComparison.Ordinal))
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToImmutableArray()
            : [];

        return new([.. produced.OrderBy(x => x.FileName, StringComparer.Ordinal)], stale);
    }

    /// <summary>The report as one line per file, for a build log.</summary>
    /// <param name="report">The report.</param>
    public static ImmutableArray<string> Describe(DerivedReport report) {
        ArgumentNullException.ThrowIfNull(report);

        var lines = new List<string>();

        foreach (var document in report.Documents) {
            lines.Add(
                $"  {(document.Drifted ? "±" : "=")} {DirectoryName}/{document.FileName} — "
                + $"{(document.Published ? document.Drifted ? "differs from the document" : "unchanged" : "new")}, "
                + $"{document.Problems.Length} problem(s)"
            );
        }

        foreach (var stale in report.Stale) {
            lines.Add($"  ! {DirectoryName}/{stale} — checked in and not produced by this run");
        }

        return [.. lines];
    }

    // ── Writing ────────────────────────────────────────────────────────────────────────────────

    static DerivedDocument Write(
        string surface,
        string fileName,
        string apiVersion,
        byte[] bytes,
        ImmutableArray<string> problems,
        string directory,
        bool write,
        HashSet<string> expected
    ) {
        var relative = surface + "/" + fileName;
        expected.Add(relative);

        var path = Path.Combine(directory, surface, fileName);
        var published = File.Exists(path) ? File.ReadAllBytes(path) : null;
        var drifted = published is null || !published.AsSpan().SequenceEqual(bytes);

        if (write && drifted) {
            Directory.CreateDirectory(Path.Combine(directory, surface));
            File.WriteAllBytes(path, bytes);
        }

        return new(surface, relative, apiVersion, published is not null, drifted, problems);
    }

    /// <summary>The one way generated source text becomes bytes.</summary>
    static byte[] Text(string source) {
        // No BOM: `new UTF8Encoding(false)` rather than Encoding.UTF8, whose default emits one — the
        // same three invisible bytes DeterministicJson's remarks name.
        var normalised = source.Replace("\r\n", "\n", StringComparison.Ordinal);

        if (!normalised.EndsWith('\n')) {
            normalised += "\n";
        }

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(normalised);
    }

    static string Relative(string directory, string full) =>
        Path.GetRelativePath(directory, full).Replace(Path.DirectorySeparatorChar, '/');

    // ── Self-checks ────────────────────────────────────────────────────────────────────────────
    //
    // ⚠ These are the equivalent of OpenApiStructure for the derived surfaces, and they run on every
    // Generate rather than only in a test — a validator that is a test asserts about the artifacts
    // somebody thought to write a test for; one in the pipeline asserts about the artifact being
    // checked in. They check what these emitters can actually get wrong.

    /// <summary>
    ///     A verb tree whose flags collide is a CLI where one of two flags silently wins — and one
    ///     that has fewer commands than the document has resource types is a CLI missing a type.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>The count check is here because the collision it catches is invisible in the tree
    ///     alone.</b> A JSON object cannot hold one key twice, so by the time two resource types have
    ///     kebab-cased to the same command name, one of them is simply not in the file and nothing in
    ///     it records that it ever should have been. The only way to see the loss is to compare
    ///     against the source document — which is why this takes one. <see cref="CliEmitter" /> also
    ///     throws on the collision as it builds; the two catch it at different times, and the checked-in
    ///     tree is the artifact this one is about.
    /// </remarks>
    static ImmutableArray<string> CliProblems(JsonObject tree, JsonObject document) {
        var problems = new List<string>();

        if (tree["groups"] is not JsonObject groups) {
            return [];
        }

        // ⚠ THE SCOPE GROUP IS COUNTED SEPARATELY BECAUSE IT COMES FROM NO PROVIDER — issue #63.
        // Folding it in would make "one command per resource type" off by three and the invariant
        // would have to be relaxed to a range, which is the shape of a check that stops catching the
        // thing it was written for.
        var commandCount = groups
            .Where(x => !string.Equals(x.Key, CliEmitter.ScopeGroupName, StringComparison.Ordinal))
            .Sum(group => group.Value?["commands"] is JsonObject c ? c.Count : 0);

        var typeCount = DocumentReader.TypesOf(document).Length;
        var scopeCount = groups[CliEmitter.ScopeGroupName]?["commands"] is JsonObject scopes ? scopes.Count : 0;
        var declaredScopes = DocumentReader.ScopesOf(document).Length;

        if (scopeCount != declaredScopes) {
            problems.Add(
                $"the verb tree's '{CliEmitter.ScopeGroupName}' group has "
                + $"{scopeCount.ToString(CultureInfo.InvariantCulture)} command(s) and the document "
                + $"declares {declaredScopes.ToString(CultureInfo.InvariantCulture)} scope(s). A scope "
                + "the CLI cannot reach is an address a tenant can only use by hand — issue #63 is "
                + "exactly that state, and this is what stops it coming back one scope at a time."
            );
        }

        if (commandCount != typeCount) {
            problems.Add(
                $"the verb tree has {commandCount.ToString(CultureInfo.InvariantCulture)} command(s) "
                + $"and the document declares {typeCount.ToString(CultureInfo.InvariantCulture)} "
                + "resource type(s). Every type gets exactly one command, so a type has been lost — "
                + "most likely two whose type paths kebab to the same command name, which the "
                + "indexer that used to build this tree resolved by silently replacing one with the "
                + "other."
            );
        }

        foreach (var group in groups) {
            if (group.Value?["commands"] is not JsonObject commands) {
                continue;
            }

            // ⚠ READ OFF THE FILE, NOT OFF THE REGISTRY, WHICH IS THE ONLY REASON THIS IS NOT A
            // DUPLICATE OF THE EMITTER'S CHECK. CliEmitter.Emit refuses a colliding short name as it
            // builds; this one asks whether the tree sitting in `generated/cli/` collides — a
            // question a hand edit, a partial regeneration or a merge can answer differently. Same
            // scope rule, same sentence: CliTokens owns both.
            //
            // ⚠ Not the scope group: its commands carry no `resourceType`, so every one of them
            // would arrive here as the declaration ("", "", "") and collide with itself — three
            // messages naming an empty provider and an empty type, which is worse than no check.
            // Its own count is asserted above, and a JsonObject cannot hold one key twice.
            if (!string.Equals(group.Key, CliEmitter.ScopeGroupName, StringComparison.Ordinal)) {
                problems.AddRange(CliTokens.Collisions(commands.Select(x => Declaration(x.Value))));
            }

            foreach (var command in commands) {
                if (command.Value?["verbs"] is not JsonObject verbs) {
                    continue;
                }

                foreach (var verb in verbs) {
                    if (verb.Value?["flags"] is not JsonArray flags) {
                        continue;
                    }

                    var seen = new HashSet<string>(StringComparer.Ordinal);

                    foreach (var flag in flags) {
                        var name = DocumentReader.Text(flag?["name"]);

                        if (!seen.Add(name)) {
                            problems.Add(
                                $"'{group.Key} {command.Key} {verb.Key}' declares '{name}' twice. One of "
                                + "the two would silently win, and which one would depend on the order "
                                + "the parser happened to register them in."
                            );
                        }

                        var alias = DocumentReader.Text(flag?["alias"]);
                        if (alias.Length > 0 && !seen.Add(alias)) {
                            problems.Add(
                                $"'{group.Key} {command.Key} {verb.Key}' declares the alias '{alias}', "
                                + "which is already a flag on the same verb."
                            );
                        }
                    }
                }
            }
        }

        problems.Sort(StringComparer.Ordinal);
        return [.. problems];
    }

    /// <summary>
    ///     One command in the checked-in tree, as the declaration <see cref="CliTokens" /> compares.
    /// </summary>
    /// <remarks>
    ///     ⚠ Built from <c>resourceType</c> rather than from the group's key and the command's name,
    ///     so the message names the type a reader has to go and change. The group key
    ///     <see cref="CliTokens.GroupOf" /> derives from it is the group the emitter filed it under,
    ///     by construction.
    /// </remarks>
    static CliDeclaration Declaration(JsonNode? command) {
        var resourceType = DocumentReader.Text(command?["resourceType"]);
        var slash = resourceType.IndexOf('/', StringComparison.Ordinal);

        return slash < 0
            ? new(resourceType, string.Empty, DocumentReader.Text(command?["alias"]))
            : new(
                resourceType[..slash],
                resourceType[(slash + 1)..],
                DocumentReader.Text(command?["alias"])
            );
    }

    /// <summary>
    ///     A form field with no control, or a form whose pointers do not cover its own schema, is a
    ///     form that silently drops a property a caller has to set.
    /// </summary>
    static ImmutableArray<string> FormProblems(JsonObject forms) {
        var problems = new List<string>();

        if (forms["forms"] is not JsonObject byType) {
            return [];
        }

        foreach (var form in byType) {
            if (form.Value?["fields"] is not JsonArray fields) {
                continue;
            }

            foreach (var field in fields) {
                var pointer = DocumentReader.Text(field?["jsonPointer"]);

                if (DocumentReader.Text(field?["control"]) is not { Length: > 0 }) {
                    problems.Add(
                        $"'{form.Key}' has a field at '{pointer}' with no control. The renderer would "
                        + "draw nothing and the property would be unsettable from the portal."
                    );
                }

                if (pointer.Length == 0 || pointer[0] != '/') {
                    problems.Add(
                        $"'{form.Key}' has a field whose jsonPointer is '{pointer}'. The pointer is the "
                        + "field's identity and is what an error's target comes back as."
                    );
                }
            }
        }

        problems.Sort(StringComparer.Ordinal);
        return [.. problems];
    }

    /// <summary>
    ///     Source that is not balanced is source nobody can compile, and a generator that produced it
    ///     would be found by whoever opened the file.
    /// </summary>
    /// <remarks>
    ///     ⚠ A brace count is not a parser and does not pretend to be. It catches the one failure this
    ///     emitter can actually have — a branch that opens a type and does not close it — without
    ///     bringing a compiler into a generation step.
    /// </remarks>
    static ImmutableArray<string> SdkProblems(string source) {
        var problems = new List<string>();
        var depth = 0;

        foreach (var current in source) {
            if (current == '{') {
                depth++;
            } else if (current == '}') {
                depth--;

                if (depth < 0) {
                    problems.Add("The generated source closes a brace that was never opened.");
                    break;
                }
            }
        }

        if (depth > 0) {
            problems.Add(
                $"The generated source leaves {depth.ToString(System.Globalization.CultureInfo.InvariantCulture)} "
                + "brace(s) open."
            );
        }

        if (!source.Contains("namespace " + SdkEmitter.Namespace, StringComparison.Ordinal)) {
            problems.Add("The generated source declares no namespace.");
        }

        return [.. problems];
    }
}
