using System.Collections.Immutable;
using System.Text;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>
///     The Go SDK: ADR-012's surfaces, in the language the Terraform provider needs — issue #40.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>Reads the published OpenAPI document, not the registry</b>, for the reason on
///         <see cref="PythonSdkEmitter" /> and <see cref="TypeScriptEmitter" />: docs/plan/21
///         § Generation's one hop puts every client under the compatibility diff over that
///         document, and an emitter that read the registry would be outside it.
///     </para>
///     <para>
///         <b>What is emitted, per api-version</b> — a package <c>api{version}</c> in its own
///         directory: <c>models.go</c> with one struct per schema and one string type per closed
///         set, <c>client.go</c> with one client per resource type grouped under its provider,
///         and <c>runtime.go</c> with the transport seam, a <c>net/http</c> transport, the one
///         error shape, the operation poller, and the <c>$skipToken</c> pager. One <c>go.mod</c>
///         at the root, so <c>go vet ./...</c> over <c>generated/sdk-go</c> compiles every
///         api-version at once.
///     </para>
///     <para>
///         ⚠
///         <b>
///             A container is its own named struct, which is Go's spelling of the #79
///             convention.
///         </b> Go has no nested types, and an anonymous struct type has to be
///         repeated at every place a caller constructs one, so <c>/properties/persistence</c> is
///         <c>{Model}PropertiesPersistence</c>: a name per container, each leaf carrying its own
///         wire name in its <c>json</c> tag at its own depth. The read shape holds the envelope
///         embedded and the body as <c>Data</c>, and reads the same bytes twice — the shape the
///         .NET hand-written half arrived at for the same problem (#85).
///     </para>
///     <para>
///         ⚠ <b>The package directory is <c>api20260801</c>, not <c>v20260801</c>.</b> A path
///         element of the form <c>vN</c> is a major-version suffix to the Go module system, and a
///         directory that looks like one is a directory whose imports resolve differently from
///         the way they read.
///     </para>
///     <para>
///         ⚠ <b>What this cannot check, said plainly.</b> Nothing in the .NET build runs Go.
///         <see cref="Problems" /> is the cheap self-check, and the
///         <c>
/// Generated Go SDK
///         compiles
///         </c> gate in <c>build/Build.Architecture.cs</c> runs <c>go vet</c> over the
///         checked-in module when <c>go</c> is on <c>PATH</c>, reporting ○ with the reason when
///         it is not rather than ✔.
///     </para>
/// </remarks>
public static class GoSdkEmitter {
    /// <summary>The subdirectory of <c>generated/</c> the module is checked in at.</summary>
    public const string DirectoryName = "sdk-go";

    /// <summary>The module path — where the module is checked in, which is the one truthful path.</summary>
    public const string ModulePath = "github.com/Rikarin/CyberCloud/generated/sdk-go";

    /// <summary>
    ///     The Go release the module declares. ⚠ Generics and <c>any</c> need 1.18; <c>slices</c> would need 1.21 and is
    ///     not used.
    /// </summary>
    public const string GoVersion = "1.22";

    /// <summary>
    ///     The banner every emitted file carries in its first line — Go's own convention, which tools such as
    ///     <c>golint</c> honour.
    /// </summary>
    const string Banner =
        "// Code generated by CyberCloud.ResourceManager.Contracts.Generation.GoSdkEmitter. DO NOT EDIT.";

    /// <summary>The package one api-version's client lives in — <c>api20260801</c>.</summary>
    /// <param name="apiVersion">The api-version, as the document spells it.</param>
    public static string PackageOf(string apiVersion) {
        ArgumentNullException.ThrowIfNull(apiVersion);

        return "api" + apiVersion.Replace("-", string.Empty, StringComparison.Ordinal);
    }

    /// <summary>The files every run writes once — the module file.</summary>
    /// <returns>The files, keyed by their path under <c>generated/sdk-go</c>.</returns>
    public static ImmutableSortedDictionary<string, string> Root() =>
        ImmutableSortedDictionary.CreateRange(
            StringComparer.Ordinal,
            new Dictionary<string, string>(StringComparer.Ordinal) {
                ["go.mod"] = Banner
                    + "\n// @generated — ./build.sh Generate overwrites this file and ./build.sh Architecture fails on a difference.\n"
                    + "\n"
                    + "module "
                    + ModulePath
                    + "\n"
                    + "\n"
                    + "go "
                    + GoVersion
                    + "\n"
            }
        );

    /// <summary>Emits one api-version's package, keyed by path under <c>generated/sdk-go</c>.</summary>
    /// <param name="document">An emitted OpenAPI document.</param>
    public static ImmutableSortedDictionary<string, string> Emit(JsonObject document) {
        ArgumentNullException.ThrowIfNull(document);

        var version = DocumentReader.VersionOf(document);
        var types = DocumentReader.TypesOf(document);
        var scopes = DocumentReader.ScopesOf(document);
        var objects = DocumentReader.ScopeObjectsOf(document);
        var names = SdkEmitter.ModelNames(types);
        var package = PackageOf(version);
        var directory = package + "/";

        return ImmutableSortedDictionary.CreateRange(
            StringComparer.Ordinal,
            new Dictionary<string, string>(StringComparer.Ordinal) {
                [directory + "models.go"] = Models(version, package, document, types, scopes, objects, names),
                [directory + "client.go"] = Client(version, package, document, types, scopes, objects, names),
                [directory + "runtime.go"] = Runtime(version, package)
            }
        );
    }

    // ── models.go ──────────────────────────────────────────────────────────────────────────────

    static string Models(
        string version,
        string package,
        JsonObject document,
        ImmutableArray<DocumentType> types,
        ImmutableArray<DocumentScope> scopes,
        ImmutableArray<DocumentScopeObject> objects,
        ImmutableDictionary<string, string> names
    ) {
        var built = new StringBuilder(Head(version));

        built.Append("\n// Package ")
            .Append(package)
            .Append(" is the CyberCloud API at api-version ")
            .Append(version)
            .Append(", typed.\n")
            .Append("//\n// One client per resource type under its provider, one struct per schema nested exactly as\n")
            .Append("// the wire is, Begin* for every long-running verb, and a pager for every collection.\n")
            .Append("package ")
            .Append(package)
            .Append("\n\n")
            .Append("import \"encoding/json\"\n");

        var declared = new Declared();

        AppendErrorModels(built, document, declared);
        AppendOperationModels(built, document, declared);
        AppendScopeModels(built, document, scopes, declared);
        AppendScopeObjectModels(built, objects, declared);
        AppendEnvelope(built, document, declared);

        foreach (var type in types) {
            AppendTypeModels(built, type, names[type.ResourceType], declared);
        }

        // ⚠ encoding/json is imported unconditionally and used by every MarshalJSON and
        // UnmarshalJSON; a document with no resource type would leave it unused, which Go refuses,
        // so a reference is kept alive for that document alone.
        built.Append("\nvar _ = json.Marshal\n");

        return built.ToString();
    }

    /// <summary>The type names one file declares, refused when one is declared twice.</summary>
    sealed class Declared {
        readonly Dictionary<string, string> names = new(StringComparer.Ordinal);

        public void Claim(string name, string origin) {
            if (names.TryGetValue(name, out var other)) {
                throw new InvalidOperationException(
                    $"'{origin}' and '{other}' both generate the Go type '{name}'. Two declarations of one "
                    + "name do not compile, and the error would surface in a consumer's build rather than here."
                );
            }

            names[name] = origin;
        }
    }

    static void AppendErrorModels(StringBuilder built, JsonObject document, Declared declared) {
        var codes = DocumentReader.EnumOf(document["components"]?["schemas"]?["ErrorCode"] as JsonObject ?? []);

        AppendEnum(
            built,
            "ErrorCode",
            "a stable, documented, greppable identifier. ⚠ Part of the API contract.",
            codes,
            "ErrorCode",
            declared
        );

        declared.Claim("Error", "the error shape");

        built.Append("\n// Error is the one error shape — docs/plan/08 § Errors.\n")
            .Append("type Error struct {\n")
            .Append("\tCode    ErrorCode `json:\"code\"`\n")
            .Append("\tMessage string    `json:\"message\"`\n")
            .Append("\t// An RFC 6901 JSON Pointer into the request body, so a form can highlight the field.\n")
            .Append("\tTarget *string `json:\"target,omitempty\"`\n")
            .Append(
                "\t// Every other problem found. A form that has to be fixed one field per round trip is a form nobody finishes.\n"
            )
            .Append("\tDetails []Error `json:\"details,omitempty\"`\n")
            .Append("}\n\n")
            .Append("// Error renders the code and the message, which is what a log line wants.\n")
            .Append("func (e *Error) Error() string {\n")
            .Append("\treturn string(e.Code) + \": \" + e.Message\n")
            .Append("}\n");
    }

    static void AppendOperationModels(StringBuilder built, JsonObject document, Declared declared) {
        var schemas = document["components"]?["schemas"] as JsonObject;

        if (schemas?[OpenApiEmitter.OperationStatusSchema] is not JsonObject status) {
            return;
        }

        var states = DocumentReader.EnumOf(schemas[OpenApiEmitter.OperationStateSchema] as JsonObject ?? []);

        AppendEnum(
            built,
            "OperationState",
            "Azure's status vocabulary. ⚠ Terminal means Succeeded, Failed or Canceled; poll until then.",
            states,
            "OperationState",
            declared
        );

        if (schemas[OpenApiEmitter.OperationProgressSchema] is JsonObject progress) {
            var leaves = DocumentReader.LeavesOf(progress);

            AppendStruct(
                built,
                "OperationProgress",
                DocumentReader.Text(progress["description"]),
                leaves.Where(static x => !x.IsObject)
                    .Select(static x => Field(x, default, "OperationProgress", true))
                    .ToList(),
                declared,
                "OperationProgress"
            );
        }

        // ⚠ The three $ref members written out, as the TypeScript and Python emitters do: LeavesOf
        // reads a $ref as untyped. Present or a pointer as x-cybercloud-read-required says.
        var served = DocumentReader.ReadRequiredOf(status);
        var fields = new List<GoField>();

        foreach (var leaf in DocumentReader.LeavesOf(status)) {
            switch (leaf.Name) {
                case "error":
                    fields.Add(
                        new(
                            "Error",
                            "*Error",
                            "error,omitempty",
                            "Present once the status is Failed, and the reason.",
                            false
                        )
                    );
                    break;

                case "progress":
                    fields.Add(
                        new(
                            "Progress",
                            "[]OperationProgress",
                            served.Contains(leaf.Name) ? "progress" : "progress,omitempty",
                            "Oldest first. What makes a nine-minute cluster creation tolerable — docs/plan/10.",
                            false
                        )
                    );
                    break;

                case "status":
                    fields.Add(new("Status", "OperationState", "status", string.Empty, false));
                    break;

                default:
                    fields.Add(
                        Field(
                            leaf with { Required = leaf.Required || served.Contains(leaf.Name) },
                            default,
                            "OperationStatus",
                            true
                        )
                    );
                    break;
            }
        }

        AppendStruct(
            built,
            "OperationStatus",
            DocumentReader.Text(status["description"]),
            fields,
            declared,
            "OperationStatus"
        );
    }

    static void AppendScopeModels(
        StringBuilder built,
        JsonObject document,
        ImmutableArray<DocumentScope> scopes,
        Declared declared
    ) {
        if (scopes.IsEmpty) {
            return;
        }

        var schema = document["components"]?["schemas"]?[OpenApiEmitter.ScopeSchema] as JsonObject ?? [];
        var leaves = DocumentReader.LeavesOf(schema);
        var naming = EnumNaming.For("Scope", leaves);

        AppendEnums(built, naming, leaves, declared);
        AppendStruct(
            built,
            "ScopeResource",
            "a tenant, a subscription or a resource group, as the API renders it. ⚠ There is no provisioningState: a scope converges before the call returns.",
            leaves.Where(static x => !x.IsObject).Select(x => Field(x, naming, "ScopeResource", true)).ToList(),
            declared,
            "ScopeResource"
        );

        foreach (var scope in scopes.Where(static x => x.Creatable)) {
            var name = ScopeContent(scope);

            AppendObjectStruct(
                built,
                name,
                "the body of a PUT that creates a " + scope.DisplayName.ToLowerInvariant() + ".",
                scope.Body,
                string.Empty,
                EnumNaming.For(name, DocumentReader.LeavesOf(scope.Body)),
                declared,
                name
            );
        }
    }

    /// <summary>
    ///     The objects addressed on a scope — issue #46's policy — one read struct and one write
    ///     struct per object, whatever the number of scopes it sits on.
    /// </summary>
    static void AppendScopeObjectModels(StringBuilder built, ImmutableArray<DocumentScopeObject> objects, Declared declared) {
        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var scoped in objects) {
            if (emitted.Add(scoped.ModelName)) {
                AppendScopeObjectModel(
                    built,
                    scoped.ModelName,
                    scoped.Resource,
                    "a " + Comment(scoped.DisplayName.ToLowerInvariant()) + ", as the API renders it. " + scoped.Summary,
                    declared,
                    scoped.Component
                );
            }

            if (scoped.ContentName.Length > 0 && emitted.Add(scoped.ContentName)) {
                AppendScopeObjectModel(
                    built,
                    scoped.ContentName,
                    scoped.Content,
                    "the body of a PUT that writes a " + scoped.DisplayName.ToLowerInvariant() + ".",
                    declared,
                    scoped.ContentComponent
                );
            }
        }
    }

    static void AppendScopeObjectModel(
        StringBuilder built,
        string name,
        JsonObject schema,
        string doc,
        Declared declared,
        string origin
    ) {
        var leaves = DocumentReader.LeavesOf(schema);
        var naming = EnumNaming.For(name, leaves);

        AppendEnums(built, naming, leaves, declared);
        AppendObjectStruct(built, name, doc, schema, string.Empty, naming, declared, origin);
    }

    /// <summary>
    ///     <c>ProvisioningState</c> and <c>Resource</c> once for the file, from the document's own
    ///     component — the read envelope every type embeds (#85).
    /// </summary>
    static void AppendEnvelope(StringBuilder built, JsonObject document, Declared declared) {
        if (document["components"]?["schemas"]?[OpenApiEmitter.ResourceEnvelopeSchema] is not JsonObject envelope) {
            return;
        }

        var served = DocumentReader.ReadRequiredOf(envelope);
        var leaves = DocumentReader.LeavesOf(envelope);
        var naming = EnumNaming.For(string.Empty, leaves);

        AppendEnums(built, naming, leaves, declared);
        AppendStruct(
            built,
            "Resource",
            DocumentReader.Text(envelope["description"]),
            leaves.Where(static x => !x.IsObject)
                .Select(x => Field(x with { Required = served.Contains(x.Name) }, naming, "Resource", true))
                .ToList(),
            declared,
            "Resource"
        );
    }

    static void AppendTypeModels(StringBuilder built, DocumentType type, string model, Declared declared) {
        var leaves = DocumentReader.LeavesOf(type.Body);
        var naming = EnumNaming.For(model, leaves);

        AppendEnums(built, naming, leaves, declared);
        AppendObjectStruct(
            built,
            model + "Data",
            type.DisplayName + ": the body a caller writes." + Summary(type),
            type.Body,
            string.Empty,
            naming,
            declared,
            model
        );

        // ⚠ THE READ SHAPE IS THE ENVELOPE PLUS THE WRITE BODY — issue #85 — and the same bytes are
        // read twice. Embedding both structs would promote a MarshalJSON from either onto this one,
        // which is a Go trap with no warning: json.Marshal of the resource would silently render
        // the body alone. Holding Data as a named field keeps the two apart.
        var hasEnvelope = !DocumentReader.LeavesOf(type.Envelope).IsEmpty;

        declared.Claim(model + "Resource", type.ResourceType);

        built.Append("\n// ")
            .Append(model)
            .Append("Resource is one ")
            .Append(Comment(type.DisplayName))
            .Append(", as the API returns it: the Resource envelope, then the body. ⚠ Read, never written.\n")
            .Append("type ")
            .Append(model)
            .Append("Resource struct {\n");

        if (hasEnvelope) {
            built.Append("\tResource\n");
        }

        built.Append("\t// The body, as the caller wrote it and the manager holds it.\n")
            .Append("\tData ")
            .Append(model)
            .Append("Data\n")
            .Append("}\n\n")
            .Append("// UnmarshalJSON reads the envelope and the body off one object.\n")
            .Append("func (r *")
            .Append(model)
            .Append("Resource) UnmarshalJSON(data []byte) error {\n");

        if (hasEnvelope) {
            built.Append("\tif err := json.Unmarshal(data, &r.Resource); err != nil {\n\t\treturn err\n\t}\n");
        }

        built.Append("\treturn json.Unmarshal(data, &r.Data)\n")
            .Append("}\n");

        foreach (var action in type.Actions) {
            if (action.Request is { } request) {
                var name = model + SdkEmitter.Pascal(action.Name) + "Content";
                var requestLeaves = DocumentReader.LeavesOf(request);
                var requestNaming = EnumNaming.For(name, requestLeaves);

                AppendEnums(built, requestNaming, requestLeaves, declared);
                AppendObjectStruct(
                    built,
                    name,
                    "the parameters of " + action.Name + ".",
                    request,
                    string.Empty,
                    requestNaming,
                    declared,
                    type.ResourceType + "/" + action.Name
                );
            }

            if (action.Response is { } response) {
                var name = model + SdkEmitter.Pascal(action.Name) + "Result";
                var responseLeaves = DocumentReader.LeavesOf(response);
                var responseNaming = EnumNaming.For(name, responseLeaves);

                AppendEnums(built, responseNaming, responseLeaves, declared);
                AppendObjectStruct(
                    built,
                    name,
                    "what "
                    + action.Name
                    + " returns."
                    + (action.Secret ? " ⚠ Secret material — never log or persist this." : string.Empty),
                    response,
                    string.Empty,
                    responseNaming,
                    declared,
                    type.ResourceType + "/" + action.Name
                );
            }
        }
    }

    /// <summary>One string type per closed set, before the struct that names them.</summary>
    static void AppendEnums(
        StringBuilder built,
        EnumNaming naming,
        ImmutableArray<SchemaLeaf> leaves,
        Declared declared
    ) {
        foreach (var leaf in leaves) {
            var values = DocumentReader.EnumOf(leaf.Schema);

            if (leaf.IsObject || values.IsEmpty) {
                continue;
            }

            AppendEnum(
                built,
                naming.NameOf(leaf),
                "the values "
                + leaf.JsonPointer
                + (DocumentReader.Flag(leaf.Schema["readOnly"])
                        ? " carries. ⚠ Read-only: the server sets it, and a write that carries it is refused."
                        : " accepts. ⚠ Closed: the write path refuses anything else."),
                values,
                leaf.JsonPointer,
                declared
            );
        }
    }

    /// <summary>
    ///     A string type and a constant per value.
    /// </summary>
    /// <remarks>
    ///     ⚠ A string type rather than an <c>int</c> with <c>iota</c>: a value a newer server
    ///     adds to a read-only vocabulary still parses, and a caller can compare against the
    ///     literal. The constant names are <c>{Type}{Value}</c> Pascal-cased, so two values that
    ///     differ only in punctuation — <c>aof</c> and <c>AOF</c> — are one identifier and are
    ///     refused here rather than left as a duplicate declaration.
    /// </remarks>
    static void AppendEnum(
        StringBuilder built,
        string name,
        string doc,
        ImmutableArray<string> values,
        string origin,
        Declared declared
    ) {
        declared.Claim(name, origin);

        built.Append("\n// ")
            .Append(name)
            .Append(" is ")
            .Append(Comment(doc))
            .Append('\n')
            .Append("type ")
            .Append(name)
            .Append(" string\n");

        if (values.IsEmpty) {
            return;
        }

        var taken = new Dictionary<string, string>(StringComparer.Ordinal);
        var constants = new List<(string Constant, string Value)>();

        foreach (var value in values) {
            var constant = name + SdkEmitter.Pascal(value);

            if (taken.TryGetValue(constant, out var other)) {
                throw new InvalidOperationException(
                    $"'{origin}' declares the values '{value}' and '{other}', which are both the Go constant "
                    + $"'{constant}'. Two constants with one name do not compile."
                );
            }

            taken[constant] = value;
            constants.Add((constant, value));
        }

        var width = constants.Max(static x => x.Constant.Length);

        built.Append("\nconst (\n");

        foreach (var (constant, value) in constants) {
            built.Append('\t')
                .Append(constant.PadRight(width))
                .Append(' ')
                .Append(name)
                .Append(" = ")
                .Append(Quote(value))
                .Append('\n');
        }

        built.Append(")\n");
    }

    /// <summary>One struct field.</summary>
    /// <param name="Name">The exported identifier.</param>
    /// <param name="Type">The Go type, pointer and all.</param>
    /// <param name="Tag">The <c>json</c> tag's value.</param>
    /// <param name="Doc">A comment above the field, or empty.</param>
    /// <param name="ReadOnly">Whether <c>MarshalJSON</c> clears it before a write.</param>
    readonly record struct GoField(string Name, string Type, string Tag, string Doc, bool ReadOnly);

    /// <summary>A scalar leaf as a field.</summary>
    /// <param name="leaf">The leaf.</param>
    /// <param name="naming">How the owner's closed sets are named.</param>
    /// <param name="owner">The struct the field is on.</param>
    /// <param name="read">
    ///     Whether the struct is only ever read — the envelope, a scope, an operation. ⚠ Every
    ///     member of the read envelope is <c>readOnly</c> in the document, and on a struct nothing
    ///     writes that is not a reason for a pointer: <c>resource.ID</c> is a <c>string</c>, not a
    ///     <c>*string</c> a caller has to nil-check for a value a read always carries.
    /// </param>
    static GoField Field(SchemaLeaf leaf, EnumNaming naming, string owner, bool read = false) {
        var schema = leaf.Schema;
        var values = DocumentReader.EnumOf(schema);
        var nullable = DocumentReader.IsNullable(schema);
        var readOnly = !read && DocumentReader.Flag(schema["readOnly"]);
        var kind = DocumentReader.TypeOf(schema);

        var bare = !values.IsEmpty && naming.Model is not null && kind != "array"
            ? naming.NameOf(leaf)
            : kind switch {
                "array" => "[]" + Scalar(schema["items"] as JsonObject ?? [], naming, leaf),
                // ⚠ Any JSON value — a policy rule — held as the bytes the wire carried, before the
                // object branch reads it as the tag bag's map.
                "object" when DocumentReader.IsJsonValue(schema) => "json.RawMessage",
                "object" => "map[string]string",
                var scalar => Scalar(schema, naming, leaf, scalar)
            };

        // ⚠ A pointer whenever "absent" and "zero" must stay apart: an optional bool that is
        // false, an optional count that is zero, a nullable string that is null. A required
        // scalar is a value, so a caller cannot construct a body the API refuses by leaving it
        // out — a read-only leaf is a pointer whatever the schema says, so MarshalJSON can clear
        // it. A slice and a map are already nil-able and never take a pointer.
        var reference = kind is "array" or "object";
        var pointer = !reference && (!leaf.Required || nullable || readOnly);
        var omit = !leaf.Required || readOnly;
        var tag = leaf.Name + (omit ? ",omitempty" : string.Empty);

        return new(
            GoName(leaf.Name),
            (pointer ? "*" : string.Empty) + bare,
            tag,
            DocumentReader.Text(schema["description"]),
            readOnly
        );
    }

    static string Scalar(JsonObject schema, EnumNaming naming, SchemaLeaf leaf, string? declared = null) {
        if (!DocumentReader.EnumOf(schema).IsEmpty
            && naming.Model is not null
            && DocumentReader.TypeOf(leaf.Schema) == "array") {
            return naming.NameOf(leaf);
        }

        return (declared ?? DocumentReader.TypeOf(schema)) switch {
            "integer" => "int64",
            "number" => "float64",
            "boolean" => "bool",
            "string" => "string",
            _ => "any"
        };
    }

    /// <summary>
    ///     One object schema as a struct, its containers as further named structs after it.
    ///     <c>origin</c> is what a collision message names.
    /// </summary>
    static void AppendObjectStruct(
        StringBuilder built,
        string name,
        string doc,
        JsonObject schema,
        string pointer,
        EnumNaming naming,
        Declared declared,
        string origin
    ) {
        var fields = new List<GoField>();
        var nested = new List<(string Name, SchemaLeaf Leaf)>();
        var taken = new Dictionary<string, string>(StringComparer.Ordinal);

        if (schema["properties"] is JsonObject properties) {
            var required = schema["required"] is JsonArray names
                ? names.Select(DocumentReader.Text).ToHashSet(StringComparer.Ordinal)
                : [];

            foreach (var member in properties.ToList().OrderBy(static x => x.Key, StringComparer.Ordinal)) {
                if (member.Value is not JsonObject child) {
                    continue;
                }

                var isObject = DocumentReader.TypeOf(child) == "object" && child["properties"] is JsonObject;
                var leaf = new SchemaLeaf(
                    pointer + "/" + member.Key,
                    member.Key,
                    child,
                    required.Contains(member.Key),
                    isObject
                );
                var identifier = GoName(member.Key);

                if (taken.TryGetValue(identifier, out var other)) {
                    throw new InvalidOperationException(
                        $"'{leaf.JsonPointer}' and '{other}' would both be the field '{identifier}' on {name}. Two "
                        + "fields with one name do not compile."
                    );
                }

                taken[identifier] = leaf.JsonPointer;

                if (!isObject) {
                    fields.Add(Field(leaf, naming, name));
                    continue;
                }

                var childName = name.EndsWith("Data", StringComparison.Ordinal) && pointer.Length == 0
                    ? name[..^4] + SdkEmitter.Pascal(member.Key)
                    : name + SdkEmitter.Pascal(member.Key);

                nested.Add((childName, leaf));

                fields.Add(
                    new(
                        identifier,
                        (leaf.Required ? string.Empty : "*") + childName,
                        member.Key + (leaf.Required ? string.Empty : ",omitempty"),
                        DocumentReader.Text(child["description"]),
                        false
                    )
                );
            }
        }

        AppendStruct(built, name, doc, fields, declared, origin);

        foreach (var (childName, leaf) in nested) {
            AppendObjectStruct(
                built,
                childName,
                DocumentReader.Text(leaf.Schema["description"]) is { Length: > 0 } text
                    ? text
                    : "the " + leaf.Name + " object of " + name + ".",
                leaf.Schema,
                leaf.JsonPointer,
                naming,
                declared,
                origin + " " + leaf.JsonPointer
            );
        }
    }

    static void AppendStruct(
        StringBuilder built,
        string name,
        string doc,
        List<GoField> fields,
        Declared declared,
        string origin
    ) {
        declared.Claim(name, origin);

        built.Append("\n// ")
            .Append(name)
            .Append(" is ")
            .Append(Comment(doc))
            .Append('\n')
            .Append("type ")
            .Append(name)
            .Append(" struct {\n");

        if (fields.Count == 0) {
            built.Append("\t// The document declares no member.\n");
        }

        // ⚠ Aligned the way gofmt aligns a struct — name, type and tag in columns over each run of
        // fields, a comment line ending the run — so the checked-in file is what gofmt would
        // write and a reader's editor does not reformat a generated file on open.
        foreach (var run in Runs(fields)) {
            var names = run.Max(static x => x.Name.Length);
            var types = run.Max(static x => x.Type.Length);

            foreach (var field in run) {
                if (field.Doc.Length > 0) {
                    built.Append("\t// ").Append(Comment(field.Doc)).Append('\n');
                }

                built.Append('\t')
                    .Append(field.Name.PadRight(names))
                    .Append(' ')
                    .Append(field.Type.PadRight(types))
                    .Append(" `json:\"")
                    .Append(field.Tag)
                    .Append("\"`\n");
            }
        }

        built.Append("}\n");

        var readOnly = fields.Where(static x => x.ReadOnly).ToList();

        if (readOnly.Count == 0) {
            return;
        }

        // ⚠ A read-only member is read and never written: the write path refuses one rather than
        // ignoring it (docs/plan/08 § The write path, end to end), so a body read off a GET and
        // sent back on a PUT would be refused for a member the caller never set. The alias type
        // strips this method so the call does not recurse.
        built.Append("\n// MarshalJSON writes the struct with its read-only members cleared: ")
            .Append(string.Join(", ", readOnly.Select(static x => x.Name)))
            .Append(". The write path refuses a read-only member rather than ignoring it.\n")
            .Append("func (v ")
            .Append(name)
            .Append(") MarshalJSON() ([]byte, error) {\n")
            .Append("\ttype plain ")
            .Append(name)
            .Append('\n')
            .Append("\tstripped := plain(v)\n");

        foreach (var field in readOnly) {
            built.Append("\tstripped.").Append(field.Name).Append(" = nil\n");
        }

        built.Append("\treturn json.Marshal(stripped)\n")
            .Append("}\n");
    }

    /// <summary>
    ///     The fields of one struct split into the runs gofmt aligns separately — a field with a
    ///     comment above it starts a new run, because the comment line has no columns.
    /// </summary>
    static List<List<GoField>> Runs(List<GoField> fields) {
        var runs = new List<List<GoField>>();

        foreach (var field in fields) {
            if (runs.Count == 0 || field.Doc.Length > 0) {
                runs.Add([]);
            }

            runs[^1].Add(field);
        }

        return runs;
    }

    /// <summary>
    ///     How one model's string types are named — the same rule the other clients apply, for
    ///     the same colliding pair.
    /// </summary>
    readonly record struct EnumNaming(string Model, ImmutableHashSet<string> Ambiguous) {
        public static EnumNaming For(string model, ImmutableArray<SchemaLeaf> leaves) {
            var counts = new Dictionary<string, int>(StringComparer.Ordinal);

            foreach (var leaf in leaves) {
                if (leaf.IsObject || DocumentReader.EnumOf(leaf.Schema).IsEmpty) {
                    continue;
                }

                counts[leaf.Name] = counts.GetValueOrDefault(leaf.Name) + 1;
            }

            return new(model, [.. counts.Where(static x => x.Value > 1).Select(static x => x.Key)]);
        }

        public string NameOf(SchemaLeaf leaf) =>
            Model + (Ambiguous.Contains(leaf.Name) ? NestedName(leaf.JsonPointer) : SdkEmitter.Pascal(leaf.Name));
    }

    static string NestedName(string jsonPointer) {
        var segments = jsonPointer.Split('/', StringSplitOptions.RemoveEmptyEntries);

        if (segments.Length > 1 && string.Equals(segments[0], "properties", StringComparison.Ordinal)) {
            segments = segments[1..];
        }

        return string.Concat(segments.Select(SdkEmitter.Pascal));
    }

    // ── client.go ──────────────────────────────────────────────────────────────────────────────

    static string Client(
        string version,
        string package,
        JsonObject document,
        ImmutableArray<DocumentType> types,
        ImmutableArray<DocumentScope> scopes,
        ImmutableArray<DocumentScopeObject> objects,
        ImmutableDictionary<string, string> names
    ) {
        var built = new StringBuilder(Head(version));
        var polls = document["paths"]?[OperationPath] is JsonObject;

        built.Append("\npackage ")
            .Append(package)
            .Append("\n\n")
            .Append("import (\n\t\"context\"\n\t\"net/url\"\n)\n\n")
            .Append(
                "// GeneratedAPIVersion is the api-version this client was generated at. The transport sends it on every request.\n"
            )
            .Append("const GeneratedAPIVersion = ")
            .Append(Quote(version))
            .Append("\n\n")
            .Append(
                "// segment percent-encodes one path segment. ⚠ A name is caller data and a '/' in one would forge a path.\n"
            )
            .Append("func segment(value string) string {\n\treturn url.PathEscape(value)\n}\n");

        var groups = types.GroupBy(static x => x.ProviderNamespace, StringComparer.Ordinal)
            .OrderBy(static x => x.Key, StringComparer.Ordinal)
            .ToList();

        var families = objects.GroupBy(static x => x.Group, StringComparer.Ordinal)
            .OrderBy(static x => x.Key, StringComparer.Ordinal)
            .ToList();

        AppendRootClient(built, version, polls, scopes, families.Select(static x => x.Key).ToList(), groups);

        if (polls) {
            AppendOperationsClient(built);
        }

        foreach (var scope in scopes) {
            AppendScopeClient(built, scope);
        }

        foreach (var family in families) {
            AppendScopeObjectClient(built, family.Key, family.ToList());
        }

        foreach (var group in groups) {
            AppendProviderGroup(built, group.Key, group.ToList(), names);

            foreach (var type in group) {
                AppendTypeClient(built, type, names[type.ResourceType]);
            }
        }

        // ⚠ context is used by every method; a document with no path at all would leave it unused,
        // which Go refuses, so a reference is kept alive for that document alone.
        built.Append("\nvar _ = context.Canceled\n");

        return built.ToString();
    }

    const string OperationPath = "/operations/{operationId}";

    static void AppendRootClient(
        StringBuilder built,
        string version,
        bool polls,
        ImmutableArray<DocumentScope> scopes,
        List<string> families,
        List<IGrouping<string, DocumentType>> groups
    ) {
        built.Append("\n// Client is the public REST API at api-version ")
            .Append(version)
            .Append(".\n")
            .Append(
                "//\n// ⚠ Every method builds a path and hands it to the transport. Authentication, the api-version\n"
            )
            .Append("// query parameter and correlation are the transport's; HTTPTransport is the net/http one, and\n")
            .Append("// anything implementing Transport can replace it.\n");

        var members = new List<(string Field, string Type, string Value)>();

        if (polls) {
            members.Add(("Operations", "*OperationsClient", "&OperationsClient{transport: transport}"));
        }

        foreach (var scope in scopes) {
            members.Add(
                (ScopeClientField(scope), "*" + ScopeClientField(scope) + "Client",
                    "&" + ScopeClientField(scope) + "Client{transport: transport}")
            );
        }

        foreach (var family in families) {
            var field = SdkEmitter.Pascal(family);
            members.Add((field, "*" + field + "Client", "&" + field + "Client{transport: transport}"));
        }

        foreach (var group in groups) {
            var segment = SdkEmitter.Pascal(group.Key.Split('.')[^1]);

            if (segment is "Operations" or "Tenants" or "Subscriptions" or "ResourceGroups" or "ManagementGroups"
                || families.Contains(segment, StringComparer.Ordinal)) {
                throw new InvalidOperationException(
                    $"The provider namespace '{group.Key}' would be the field '{segment}' on Client, which the "
                    + "client already declares for the platform's own API."
                );
            }

            members.Add((segment, "*" + segment + "Provider", "new" + segment + "Provider(transport)"));
        }

        AppendHolder(built, "Client", "NewClient", "builds a client over one transport.", members);
    }

    /// <summary>
    ///     A struct of clients and the function that builds it, aligned the way gofmt aligns a
    ///     field list and a keyed composite literal.
    /// </summary>
    static void AppendHolder(
        StringBuilder built,
        string name,
        string constructor,
        string doc,
        List<(string Field, string Type, string Value)> members
    ) {
        var width = members.Count == 0 ? 0 : members.Max(static x => x.Field.Length);

        built.Append("type ").Append(name).Append(" struct {\n");

        foreach (var (field, type, _) in members) {
            built.Append('\t').Append(field.PadRight(width)).Append(' ').Append(type).Append('\n');
        }

        built.Append("}\n\n")
            .Append("// ")
            .Append(constructor)
            .Append(' ')
            .Append(doc)
            .Append('\n')
            .Append("func ")
            .Append(constructor)
            .Append("(transport Transport) *")
            .Append(name)
            .Append(" {\n")
            .Append("\treturn &")
            .Append(name)
            .Append("{\n");

        foreach (var (field, _, value) in members) {
            built.Append("\t\t").Append((field + ":").PadRight(width + 1)).Append(' ').Append(value).Append(",\n");
        }

        built.Append("\t}\n}\n");
    }

    static void AppendOperationsClient(StringBuilder built) =>
        built.Append(
            "\n// OperationsClient polls long-running operations — docs/plan/10 § Long-running operations, over HTTP.\n"
        )
            .Append("type OperationsClient struct {\n\ttransport Transport\n}\n\n")
            .Append(
                "// Get reads one operation. ⚠ The Azure-AsyncOperation header is an absolute URL; the id is its last segment.\n"
            )
            .Append(
                "func (c *OperationsClient) Get(ctx context.Context, operationID string) (*OperationStatus, error) {\n"
            )
            .Append(Read("GET", PathExpression(OperationPath), "nil", "OperationStatus"));

    static void AppendScopeClient(StringBuilder built, DocumentScope scope) {
        var name = ScopeClientField(scope) + "Client";
        var placeholders = DocumentReader.PlaceholdersOf(scope.Path);
        var parameters = Parameters(placeholders);

        built.Append("\n// ")
            .Append(name)
            .Append(" reads ")
            .Append(Comment(scope.DisplayPlural.ToLowerInvariant()))
            .Append(". ")
            .Append(Comment(scope.Summary))
            .Append('\n')
            .Append("type ")
            .Append(name)
            .Append(" struct {\n\ttransport Transport\n}\n\n")
            .Append("// Get reads one ")
            .Append(Comment(scope.DisplayName.ToLowerInvariant()))
            .Append(".\n")
            .Append("func (c *")
            .Append(name)
            .Append(") Get(ctx context.Context")
            .Append(parameters)
            .Append(") (*ScopeResource, error) {\n")
            .Append(Read("GET", PathExpression(scope.Path), "nil", "ScopeResource"));

        if (scope.CollectionPath.Length > 0) {
            // Emitted only when the document declares the collection, as a resource type's List is
            // — the tenant has none. The same Pager a resource listing walks, over ScopeResource.
            var collectionParameters = Parameters(DocumentReader.PlaceholdersOf(scope.CollectionPath));

            built.Append("\n// List pages through the ")
                .Append(Comment(scope.DisplayPlural.ToLowerInvariant()))
                .Append(" the caller may read. ⚠ A short page never means \"that is all there is\".\n")
                .Append("func (c *")
                .Append(name)
                .Append(") List(")
                .Append(collectionParameters.TrimStart(',', ' '))
                .Append(collectionParameters.Length > 0 ? ", " : string.Empty)
                .Append("options *ListOptions) *Pager[ScopeResource] {\n")
                .Append("\tpath := ")
                .Append(PathExpression(scope.CollectionPath))
                .Append('\n')
                .Append("\treturn newPager[ScopeResource](c.transport, path, options)\n}\n");
        }

        if (!scope.Creatable) {
            built.Append(
                "\n// ⚠ There is no Create, and the absence is the contract: a request's tenant is resolved from its\n"
            )
                .Append("// token, so a call creating another tenant is refused before routing runs.\n");

            return;
        }

        built.Append("\n// Create creates one ")
            .Append(Comment(scope.DisplayName.ToLowerInvariant()))
            .Append(
                ", or returns the existing one unchanged. ⚠ 201 the first time and 200 on a repeat, and no operation to poll.\n"
            )
            .Append("func (c *")
            .Append(name)
            .Append(") Create(ctx context.Context")
            .Append(parameters)
            .Append(", content ")
            .Append(ScopeContent(scope))
            .Append(") (*ScopeResource, error) {\n")
            .Append(Read("PUT", PathExpression(scope.Path), "content", "ScopeResource"));
    }

    /// <summary>
    ///     One client per namespace of scope objects — <c>PolicyClient</c> — with a method per object,
    ///     scope and verb.
    /// </summary>
    /// <remarks>
    ///     ⚠ No <c>Begin*</c> and no <c>Operation</c>: a write converges before the call returns — the
    ///     scope client's rule, for the scope client's reason.
    /// </remarks>
    static void AppendScopeObjectClient(StringBuilder built, string group, List<DocumentScopeObject> objects) {
        var name = SdkEmitter.Pascal(group) + "Client";

        built.Append("\n// ")
            .Append(name)
            .Append(" reads and writes the objects under ")
            .Append(objects[0].ProviderNamespace)
            .Append(", on every scope that takes them — docs/plan/08 § Policy.\n")
            .Append("type ")
            .Append(name)
            .Append(" struct {\n\ttransport Transport\n}\n");

        foreach (var scoped in objects) {
            var on = Comment(scoped.DisplayName.ToLowerInvariant()) + " on a " + CliEmitter.Kebab(scoped.Scope).Replace('-', ' ');
            var collectionParameters = Parameters(DocumentReader.PlaceholdersOf(scoped.CollectionPath));

            built.Append("\n// List")
                .Append(scoped.PluralStem)
                .Append(" pages through the ")
                .Append(Comment(scoped.DisplayPlural.ToLowerInvariant()))
                .Append(" on a ")
                .Append(CliEmitter.Kebab(scoped.Scope).Replace('-', ' '))
                .Append(". ⚠ A short page never means \"that is all there is\".\n")
                .Append("func (c *")
                .Append(name)
                .Append(") List")
                .Append(scoped.PluralStem)
                .Append('(')
                .Append(collectionParameters.TrimStart(',', ' '))
                .Append(collectionParameters.Length > 0 ? ", " : string.Empty)
                .Append("options *ListOptions) *Pager[")
                .Append(scoped.ModelName)
                .Append("] {\n")
                .Append("\tpath := ")
                .Append(PathExpression(scoped.CollectionPath))
                .Append('\n')
                .Append("\treturn newPager[")
                .Append(scoped.ModelName)
                .Append("](c.transport, path, options)\n}\n");

            if (scoped.Path.Length == 0) {
                continue;
            }

            var parameters = Parameters(DocumentReader.PlaceholdersOf(scoped.Path));
            var path = PathExpression(scoped.Path);

            built.Append("\n// Get")
                .Append(scoped.SingularStem)
                .Append(" reads one ")
                .Append(on)
                .Append(".\n")
                .Append("func (c *")
                .Append(name)
                .Append(") Get")
                .Append(scoped.SingularStem)
                .Append("(ctx context.Context")
                .Append(parameters)
                .Append(") (*")
                .Append(scoped.ModelName)
                .Append(", error) {\n")
                .Append(Read("GET", path, "nil", scoped.ModelName));

            if (!scoped.Writable) {
                continue;
            }

            built.Append("\n// CreateOrUpdate")
                .Append(scoped.SingularStem)
                .Append(" creates or replaces one ")
                .Append(on)
                .Append(", written whole. ⚠ 201 the first time and 200 after, and no operation to poll.\n")
                .Append("func (c *")
                .Append(name)
                .Append(") CreateOrUpdate")
                .Append(scoped.SingularStem)
                .Append("(ctx context.Context")
                .Append(parameters)
                .Append(", content ")
                .Append(scoped.ContentName)
                .Append(") (*")
                .Append(scoped.ModelName)
                .Append(", error) {\n")
                .Append(Read("PUT", path, "content", scoped.ModelName))
                .Append("\n// Delete")
                .Append(scoped.SingularStem)
                .Append(" deletes one ")
                .Append(on)
                .Append(". An object already gone is a success.\n")
                .Append("func (c *")
                .Append(name)
                .Append(") Delete")
                .Append(scoped.SingularStem)
                .Append("(ctx context.Context")
                .Append(parameters)
                .Append(") error {\n")
                .Append("\tpath := ")
                .Append(path)
                .Append('\n')
                .Append("\treturn call(ctx, c.transport, \"DELETE\", path, nil, nil)\n}\n");
        }
    }

    static void AppendProviderGroup(
        StringBuilder built,
        string providerNamespace,
        List<DocumentType> types,
        ImmutableDictionary<string, string> names
    ) {
        var segment = SdkEmitter.Pascal(providerNamespace.Split('.')[^1]);
        var taken = new Dictionary<string, string>(StringComparer.Ordinal);
        var ordered = types.OrderBy(static x => x.TypePath, StringComparer.Ordinal).ToList();

        var members = new List<(string Field, string Type, string Value)>();

        foreach (var type in ordered) {
            var field = TypeField(type.TypePath);

            if (taken.TryGetValue(field, out var other)) {
                throw new InvalidOperationException(
                    $"'{type.ResourceType}' and '{other}' both generate the Go field '{field}' on {segment}Provider. "
                    + "Two type paths that differ only in case or punctuation are one Go name."
                );
            }

            taken[field] = type.ResourceType;
            members.Add(
                (field, "*" + names[type.ResourceType] + "Client",
                    "&" + names[type.ResourceType] + "Client{transport: transport}")
            );
        }

        built.Append("\n// ")
            .Append(segment)
            .Append("Provider holds the resource types of ")
            .Append(Comment(providerNamespace))
            .Append(".\n");

        AppendHolder(
            built,
            segment + "Provider",
            "new" + segment + "Provider",
            "builds the group's clients over one transport.",
            members
        );
    }

    static void AppendTypeClient(StringBuilder built, DocumentType type, string model) {
        var placeholders = DocumentReader.PlaceholdersOf(type.Path);
        var parameters = Parameters(placeholders);
        var path = PathExpression(type.Path);
        var client = model + "Client";

        built.Append("\n// ")
            .Append(client)
            .Append(" is ")
            .Append(Comment(type.DisplayPlural.ToLowerInvariant()))
            .Append(" — ")
            .Append(type.ResourceType)
            .Append('.')
            .Append(Summary(type))
            .Append('\n')
            .Append("type ")
            .Append(client)
            .Append(" struct {\n\ttransport Transport\n}\n");

        built.Append("\n// Get reads one ")
            .Append(Comment(type.DisplayName))
            .Append(".\n")
            .Append("func (c *")
            .Append(client)
            .Append(") Get(ctx context.Context")
            .Append(parameters)
            .Append(") (*")
            .Append(model)
            .Append("Resource, error) {\n")
            .Append(Read("GET", path, "nil", model + "Resource"));

        built.Append("\n// BeginCreateOrUpdate creates or replaces one ")
            .Append(Comment(type.DisplayName))
            .Append(". ⚠ Long-running: Wait on the result.\n")
            .Append("func (c *")
            .Append(client)
            .Append(") BeginCreateOrUpdate(ctx context.Context")
            .Append(parameters)
            .Append(", data ")
            .Append(model)
            .Append("Data) (*Operation[")
            .Append(model)
            .Append("Resource], error) {\n")
            .Append("\tpath := ")
            .Append(path)
            .Append('\n')
            .Append("\treturn begin[")
            .Append(model)
            .Append("Resource](ctx, c.transport, \"PUT\", path, data, path)\n}\n");

        built.Append("\n// BeginUpdate amends one ")
            .Append(Comment(type.DisplayName))
            .Append(". A merge patch: what is not set is not changed.\n")
            .Append("func (c *")
            .Append(client)
            .Append(") BeginUpdate(ctx context.Context")
            .Append(parameters)
            .Append(", data ")
            .Append(model)
            .Append("Data) (*Operation[")
            .Append(model)
            .Append("Resource], error) {\n")
            .Append("\tpath := ")
            .Append(path)
            .Append('\n')
            .Append("\treturn begin[")
            .Append(model)
            .Append("Resource](ctx, c.transport, \"PATCH\", path, data, path)\n}\n");

        built.Append("\n// BeginDelete deletes one ")
            .Append(Comment(type.DisplayName))
            .Append('.')
            .Append(
                type.SoftDeleteDays > 0
                    ? " ⚠ Recoverable for " + DocumentReader.Count(type.SoftDeleteDays) + " day(s)."
                    : " ⚠ Permanent: this type declares no soft-delete window."
            )
            .Append('\n')
            .Append("func (c *")
            .Append(client)
            .Append(") BeginDelete(ctx context.Context")
            .Append(parameters)
            .Append(") (*Operation[struct{}], error) {\n")
            .Append("\tpath := ")
            .Append(path)
            .Append('\n')
            .Append("\treturn begin[struct{}](ctx, c.transport, \"DELETE\", path, nil, \"\")\n}\n");

        if (type.CollectionPath.Length > 0) {
            var collectionParameters = Parameters(DocumentReader.PlaceholdersOf(type.CollectionPath));

            built.Append("\n// List pages through the ")
                .Append(Comment(type.DisplayPlural))
                .Append(" in a resource group. ⚠ A short page never means \"that is all there is\".\n")
                .Append("func (c *")
                .Append(client)
                .Append(") List(")
                .Append(collectionParameters.TrimStart(',', ' '))
                .Append(collectionParameters.Length > 0 ? ", " : string.Empty)
                .Append("options *ListOptions) *Pager[")
                .Append(model)
                .Append("Resource] {\n")
                .Append("\tpath := ")
                .Append(PathExpression(type.CollectionPath))
                .Append('\n')
                .Append("\treturn newPager[")
                .Append(model)
                .Append("Resource](c.transport, path, options)\n}\n");
        }

        foreach (var action in type.Actions) {
            var method = SdkEmitter.Pascal(action.Name);
            var content = action.Request is null ? string.Empty : ", content " + model + method + "Content";
            var body = action.Request is null ? "nil" : "content";
            var actionPath = PathExpression(type.Path + "/" + action.Name);
            var doc = Comment(action.Name)
                + " — permission '"
                + Comment(action.Permission)
                + "'."
                + (action.Secret ? " ⚠ The response carries secret material." : string.Empty);

            // ⚠ A purge ends the resource, so its Operation is BeginDelete's: Wait reads nothing, because
            // the GET the resource-returning shape sends afterwards is a 404 for a purge that worked.
            // Read off the document (DocumentAction.RemovesResource), never off the name here.
            if (action is { LongRunning: true, RemovesResource: true }) {
                built.Append("\n// Begin")
                    .Append(method)
                    .Append(" runs ")
                    .Append(doc)
                    .Append(
                        " ⚠ Long-running, and it removes the resource: Wait reads nothing afterwards, because there is nothing left to read.\n"
                    )
                    .Append("func (c *")
                    .Append(client)
                    .Append(") Begin")
                    .Append(method)
                    .Append("(ctx context.Context")
                    .Append(parameters)
                    .Append(content)
                    .Append(") (*Operation[struct{}], error) {\n")
                    .Append("\tpath := ")
                    .Append(actionPath)
                    .Append('\n')
                    .Append("\treturn begin[struct{}](ctx, c.transport, \"POST\", path, ")
                    .Append(body)
                    .Append(", \"\")\n}\n");

                continue;
            }

            if (action.LongRunning) {
                built.Append("\n// Begin")
                    .Append(method)
                    .Append(" runs ")
                    .Append(doc)
                    .Append(" ⚠ Long-running: Wait resolves to the resource afterwards.\n")
                    .Append("func (c *")
                    .Append(client)
                    .Append(") Begin")
                    .Append(method)
                    .Append("(ctx context.Context")
                    .Append(parameters)
                    .Append(content)
                    .Append(") (*Operation[")
                    .Append(model)
                    .Append("Resource], error) {\n")
                    .Append("\tpath := ")
                    .Append(path)
                    .Append('\n')
                    .Append("\treturn begin[")
                    .Append(model)
                    .Append("""Resource](ctx, c.transport, "POST", path+""")
                    .Append(Quote("/" + action.Name))
                    .Append(", ")
                    .Append(body)
                    .Append(", path)\n}\n");

                continue;
            }

            if (action.Response is null) {
                built.Append("\n// ")
                    .Append(method)
                    .Append(" runs ")
                    .Append(doc)
                    .Append('\n')
                    .Append("func (c *")
                    .Append(client)
                    .Append(") ")
                    .Append(method)
                    .Append("(ctx context.Context")
                    .Append(parameters)
                    .Append(content)
                    .Append(") error {\n")
                    .Append("\tpath := ")
                    .Append(actionPath)
                    .Append('\n')
                    .Append("\treturn call(ctx, c.transport, \"POST\", path, ")
                    .Append(body)
                    .Append(", nil)\n}\n");

                continue;
            }

            built.Append("\n// ")
                .Append(method)
                .Append(" runs ")
                .Append(doc)
                .Append('\n')
                .Append("func (c *")
                .Append(client)
                .Append(") ")
                .Append(method)
                .Append("(ctx context.Context")
                .Append(parameters)
                .Append(content)
                .Append(") (*")
                .Append(model)
                .Append(method)
                .Append("Result, error) {\n")
                .Append(Read("POST", actionPath, body, model + method + "Result"));
        }
    }

    /// <summary>
    ///     The body of a method that reads one typed result: the path, the call, the checked error.
    /// </summary>
    /// <remarks>
    ///     ⚠ The path goes into a local first, on every method, because gofmt spaces a binary
    ///     <c>+</c> at statement level and compacts it inside a call's argument list — and a
    ///     checked-in file that gofmt would rewrite is one a reader's editor rewrites on open.
    /// </remarks>
    static string Read(string method, string pathExpression, string body, string result) =>
        "\tpath := "
        + pathExpression
        + "\n"
        + "\tvar result "
        + result
        + "\n"
        + "\tif err := call(ctx, c.transport, "
        + Quote(method)
        + ", path, "
        + body
        + ", &result); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\treturn &result, nil\n"
        + "}\n";

    /// <summary>The parameter list a path's placeholders need, each a <c>string</c>, with a leading comma.</summary>
    static string Parameters(ImmutableArray<string> placeholders) =>
        placeholders.IsEmpty ? string.Empty : ", " + string.Join(", ", placeholders.Select(Parameter)) + " string";

    /// <summary>A path template as a Go expression with each placeholder encoded.</summary>
    static string PathExpression(string path) {
        var built = new StringBuilder("\"");

        for (var i = 0; i < path.Length; i++) {
            if (path[i] != '{') {
                if (path[i] is '"' or '\\') {
                    built.Append('\\');
                }

                built.Append(path[i]);
                continue;
            }

            var close = path.IndexOf('}', i + 1);

            if (close < 0) {
                built.Append(path[i]);
                continue;
            }

            built.Append("\" + segment(").Append(Parameter(path[(i + 1)..close])).Append(") + \"");
            i = close;
        }

        return built.Append('"').ToString().Replace(" + \"\"", string.Empty, StringComparison.Ordinal);
    }

    // ── runtime.go ─────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The transport seam, a <c>net/http</c> transport, the error shape, the poller and the
    ///     pager — <see cref="PythonSdkEmitter" />'s <c>_runtime.py</c>, in Go.
    /// </summary>
    static string Runtime(string version, string package) =>
        Head(version)
        + "\npackage "
        + package
        + "\n"
        + "\n"
        + "import (\n"
        + "\t\"bytes\"\n"
        + "\t\"context\"\n"
        + "\t\"crypto/rand\"\n"
        + "\t\"encoding/json\"\n"
        + "\t\"fmt\"\n"
        + "\t\"io\"\n"
        + "\t\"net/http\"\n"
        + "\t\"net/url\"\n"
        + "\t\"strconv\"\n"
        + "\t\"strings\"\n"
        + "\t\"time\"\n"
        + ")\n"
        + "\n"
        + "// APIVersion is the api-version every request this package makes is sent at.\n"
        + "const APIVersion = "
        + Quote(version)
        + "\n"
        + "\n"
        + "// Request is one request the client wants made. The path has every placeholder filled and every\n"
        + "// segment encoded. ⚠ api-version is NOT in Query: the transport puts it on every request, so no\n"
        + "// call site can forget it.\n"
        + "type Request struct {\n"
        + "\tMethod string\n"
        + "\tPath   string\n"
        + "\tQuery  url.Values\n"
        + "\t// Marshalled as JSON when non-nil.\n"
        + "\tBody any\n"
        + "}\n"
        + "\n"
        + "// Response is what came back. ⚠ A scope PUT answers 201 the first time and 200 on a repeat.\n"
        + "type Response struct {\n"
        + "\tStatusCode int\n"
        + "\tHeader     http.Header\n"
        + "\tBody       []byte\n"
        + "}\n"
        + "\n"
        + "// RetryAfter reads Retry-After as a delay. Only the delta-seconds form; a date reads as absent.\n"
        + "func (r *Response) RetryAfter() (time.Duration, bool) {\n"
        + "\tseconds, err := strconv.ParseFloat(r.Header.Get(\"Retry-After\"), 64)\n"
        + "\tif err != nil {\n"
        + "\t\treturn 0, false\n"
        + "\t}\n"
        + "\treturn time.Duration(seconds * float64(time.Second)), true\n"
        + "}\n"
        + "\n"
        + "// Transport is how the client reaches the platform. HTTPTransport is the net/http one; a test\n"
        + "// supplies a fake. ⚠ Send never fails on a 4xx or 5xx: the client turns those into the one error\n"
        + "// shape. It fails when no response arrived at all.\n"
        + "type Transport interface {\n"
        + "\tSend(ctx context.Context, request *Request) (*Response, error)\n"
        + "}\n"
        + "\n"
        + "// TokenProvider returns a bearer token. Asked on every request, so a caller that caches and\n"
        + "// refreshes owns that policy.\n"
        + "type TokenProvider func(ctx context.Context) (string, error)\n"
        + "\n"
        + "// HTTPTransport is net/http, a bearer token, and nothing else — no retry, no keychain. docs/plan/21\n"
        + "// § The .NET SDK's credential types are the hand-written half this module does not have yet.\n"
        + "type HTTPTransport struct {\n"
        + "\tEndpoint string\n"
        + "\tToken    TokenProvider\n"
        + "\t// nil means http.DefaultClient.\n"
        + "\tClient *http.Client\n"
        + "}\n"
        + "\n"
        + "// Send makes one request.\n"
        + "func (t *HTTPTransport) Send(ctx context.Context, request *Request) (*Response, error) {\n"
        + "\tquery := url.Values{}\n"
        + "\tfor name, values := range request.Query {\n"
        + "\t\tquery[name] = values\n"
        + "\t}\n"
        + "\tquery.Set(\"api-version\", APIVersion)\n"
        + "\ttarget := strings.TrimRight(t.Endpoint, \"/\") + request.Path + \"?\" + query.Encode()\n"
        + "\tvar body io.Reader\n"
        + "\tif request.Body != nil {\n"
        + "\t\tencoded, err := json.Marshal(request.Body)\n"
        + "\t\tif err != nil {\n"
        + "\t\t\treturn nil, err\n"
        + "\t\t}\n"
        + "\t\tbody = bytes.NewReader(encoded)\n"
        + "\t}\n"
        + "\thttpRequest, err := http.NewRequestWithContext(ctx, request.Method, target, body)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\ttoken, err := t.Token(ctx)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\thttpRequest.Header.Set(\"Authorization\", \"Bearer \"+token)\n"
        + "\thttpRequest.Header.Set(\"Accept\", \"application/json\")\n"
        + "\t// docs/plan/10 § Request pipeline: one correlation id per logical request.\n"
        + "\thttpRequest.Header.Set(\"x-ms-correlation-request-id\", correlationID())\n"
        + "\tif body != nil {\n"
        + "\t\thttpRequest.Header.Set(\"Content-Type\", \"application/json; charset=utf-8\")\n"
        + "\t}\n"
        + "\tclient := t.Client\n"
        + "\tif client == nil {\n"
        + "\t\tclient = http.DefaultClient\n"
        + "\t}\n"
        + "\thttpResponse, err := client.Do(httpRequest)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tdefer httpResponse.Body.Close()\n"
        + "\tcontent, err := io.ReadAll(httpResponse.Body)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\treturn &Response{StatusCode: httpResponse.StatusCode, Header: httpResponse.Header, Body: content}, nil\n"
        + "}\n"
        + "\n"
        + "func correlationID() string {\n"
        + "\tvar random [16]byte\n"
        + "\tif _, err := rand.Read(random[:]); err != nil {\n"
        + "\t\treturn \"\"\n"
        + "\t}\n"
        + "\treturn fmt.Sprintf(\"%x-%x-%x-%x-%x\", random[0:4], random[4:6], random[6:8], random[8:10], random[10:16])\n"
        + "}\n"
        + "\n"
        + "// RequestFailedError is a 4xx or 5xx, carrying the one error shape when the body had it —\n"
        + "// docs/plan/08 § Errors. ⚠ Also returned when a poll reports a Failed or Canceled operation: the\n"
        + "// poll itself was a 200, and the error is the operation's.\n"
        + "type RequestFailedError struct {\n"
        + "\tStatusCode int\n"
        + "\t// nil when the body did not carry the shape.\n"
        + "\tErr *Error\n"
        + "}\n"
        + "\n"
        + "// Error renders the status and, when there is one, the code and the message.\n"
        + "func (e *RequestFailedError) Error() string {\n"
        + "\tif e.Err == nil {\n"
        + "\t\treturn \"HTTP \" + strconv.Itoa(e.StatusCode)\n"
        + "\t}\n"
        + "\treturn e.Err.Error()\n"
        + "}\n"
        + "\n"
        + "// Unwrap exposes the error shape to errors.As.\n"
        + "func (e *RequestFailedError) Unwrap() error {\n"
        + "\tif e.Err == nil {\n"
        + "\t\treturn nil\n"
        + "\t}\n"
        + "\treturn e.Err\n"
        + "}\n"
        + "\n"
        + "// Code is the error code, or \"\" when the body did not carry one.\n"
        + "func (e *RequestFailedError) Code() ErrorCode {\n"
        + "\tif e.Err == nil {\n"
        + "\t\treturn \"\"\n"
        + "\t}\n"
        + "\treturn e.Err.Code\n"
        + "}\n"
        + "\n"
        + "// ParseError reads the error shape off a failed response, or nil when the body does not carry it.\n"
        + "func ParseError(response *Response) *Error {\n"
        + "\tvar envelope struct {\n"
        + "\t\tError *Error `json:\"error\"`\n"
        + "\t}\n"
        + "\tif err := json.Unmarshal(response.Body, &envelope); err != nil || envelope.Error == nil || envelope.Error.Code == \"\" {\n"
        + "\t\treturn nil\n"
        + "\t}\n"
        + "\treturn envelope.Error\n"
        + "}\n"
        + "\n"
        + "// checkStatus is the one place a response becomes an error.\n"
        + "func checkStatus(response *Response) error {\n"
        + "\tif response.StatusCode < 400 {\n"
        + "\t\treturn nil\n"
        + "\t}\n"
        + "\treturn &RequestFailedError{StatusCode: response.StatusCode, Err: ParseError(response)}\n"
        + "}\n"
        + "\n"
        + "// call sends one request, refuses a 4xx or 5xx, and decodes the body into result when one is wanted.\n"
        + "func call(ctx context.Context, transport Transport, method string, path string, body any, result any) error {\n"
        + "\tresponse, err := transport.Send(ctx, &Request{Method: method, Path: path, Body: body})\n"
        + "\tif err != nil {\n"
        + "\t\treturn err\n"
        + "\t}\n"
        + "\tif err := checkStatus(response); err != nil {\n"
        + "\t\treturn err\n"
        + "\t}\n"
        + "\tif result == nil {\n"
        + "\t\treturn nil\n"
        + "\t}\n"
        + "\treturn decode(response, result)\n"
        + "}\n"
        + "\n"
        + "func decode(response *Response, into any) error {\n"
        + "\tif err := json.Unmarshal(response.Body, into); err != nil {\n"
        + "\t\treturn fmt.Errorf(\"the response body is not the shape the document declares: %w\", err)\n"
        + "\t}\n"
        + "\treturn nil\n"
        + "}\n"
        + "\n"
        + "// relative is a GET of an absolute URL's path and query. ⚠ The origin is dropped: a bearer token\n"
        + "// follows the endpoint, never a URL the response chose. The query is parsed into members so the\n"
        + "// transport's own api-version replaces the one the link carried rather than following it.\n"
        + "func relative(raw string) (*Request, error) {\n"
        + "\tparsed, err := url.Parse(raw)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\treturn &Request{Method: \"GET\", Path: parsed.EscapedPath(), Query: parsed.Query()}, nil\n"
        + "}\n"
        + "\n"
        + "// Operation is a long-running operation — docs/plan/10 § Long-running operations, over HTTP. Built\n"
        + "// from the 202: Poll reads the status once; Wait polls until the status is terminal and then reads\n"
        + "// the resource, or returns a RequestFailedError with the operation's error.\n"
        + "//\n"
        + "// ⚠ No goroutine and no timer of its own: every poll is driven by the caller, so nothing keeps\n"
        + "// polling after the caller has walked away.\n"
        + "type Operation[T any] struct {\n"
        + "\t// Interval overrides the server's Retry-After between polls when set. ⚠ The server's number wins\n"
        + "\t// by default: it is back-pressure, and a client that polls a nine-minute operation every 100 ms\n"
        + "\t// spends its rate-limit budget finding out nothing changed.\n"
        + "\tInterval time.Duration\n"
        + "\n"
        + "\ttransport    Transport\n"
        + "\tid           string\n"
        + "\tresourcePath string\n"
        + "\tretryAfter   time.Duration\n"
        + "\tstatus       *OperationStatus\n"
        + "\treported     int\n"
        + "}\n"
        + "\n"
        + "// begin sends a write and wraps its 202. resourcePath is what Wait reads on success, or \"\" for a delete.\n"
        + "func begin[T any](ctx context.Context, transport Transport, method string, path string, body any, resourcePath string) (*Operation[T], error) {\n"
        + "\tresponse, err := transport.Send(ctx, &Request{Method: method, Path: path, Body: body})\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tif err := checkStatus(response); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\treturn newOperation[T](transport, response, resourcePath)\n"
        + "}\n"
        + "\n"
        + "func newOperation[T any](transport Transport, accepted *Response, resourcePath string) (*Operation[T], error) {\n"
        + "\tlocation := accepted.Header.Get(\"Azure-AsyncOperation\")\n"
        + "\tif location == \"\" {\n"
        + "\t\treturn nil, &RequestFailedError{StatusCode: accepted.StatusCode, Err: &Error{Code: \"InternalError\", Message: \"The 202 carried no Azure-AsyncOperation header, so the operation cannot be polled.\"}}\n"
        + "\t}\n"
        + "\tparsed, err := url.Parse(location)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\t// ⚠ The last segment as the id, never the URL itself: the poll goes to the transport's endpoint.\n"
        + "\tpath := strings.TrimRight(parsed.Path, \"/\")\n"
        + "\tid := path[strings.LastIndex(path, \"/\")+1:]\n"
        + "\tretryAfter, _ := accepted.RetryAfter()\n"
        + "\treturn &Operation[T]{transport: transport, id: id, resourcePath: resourcePath, retryAfter: retryAfter}, nil\n"
        + "}\n"
        + "\n"
        + "// ID is the operation id — the last segment of the Azure-AsyncOperation URL.\n"
        + "func (o *Operation[T]) ID() string {\n"
        + "\treturn o.id\n"
        + "}\n"
        + "\n"
        + "// Status is the last polled status, or nil before the first poll.\n"
        + "func (o *Operation[T]) Status() *OperationStatus {\n"
        + "\treturn o.status\n"
        + "}\n"
        + "\n"
        + "// Done reports whether the last poll saw a terminal status.\n"
        + "func (o *Operation[T]) Done() bool {\n"
        + "\treturn o.status != nil && (o.status.Status == \"Succeeded\" || o.status.Status == \"Failed\" || o.status.Status == \"Canceled\")\n"
        + "}\n"
        + "\n"
        + "// Poll reads the status once. ⚠ A poll that fails is not an operation that fails: a 429 is returned as itself.\n"
        + "func (o *Operation[T]) Poll(ctx context.Context) (*OperationStatus, error) {\n"
        + "\tresponse, err := o.transport.Send(ctx, &Request{Method: \"GET\", Path: \"/operations/\" + url.PathEscape(o.id)})\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tif err := checkStatus(response); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tvar status OperationStatus\n"
        + "\tif err := decode(response, &status); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\to.status = &status\n"
        + "\to.retryAfter, _ = response.RetryAfter()\n"
        + "\treturn &status, nil\n"
        + "}\n"
        + "\n"
        + "// Wait polls until the status is terminal, reporting each new progress entry to onProgress when it\n"
        + "// is not nil, then reads the resource. A delete resolves to an empty value.\n"
        + "func (o *Operation[T]) Wait(ctx context.Context, onProgress func(OperationProgress)) (*T, error) {\n"
        + "\tfor !o.Done() {\n"
        + "\t\tdelay := o.Interval\n"
        + "\t\tif delay == 0 {\n"
        + "\t\t\tdelay = o.retryAfter\n"
        + "\t\t}\n"
        + "\t\tif delay == 0 {\n"
        + "\t\t\tdelay = time.Second\n"
        + "\t\t}\n"
        + "\t\tselect {\n"
        + "\t\tcase <-ctx.Done():\n"
        + "\t\t\treturn nil, ctx.Err()\n"
        + "\t\tcase <-time.After(delay):\n"
        + "\t\t}\n"
        + "\t\tstatus, err := o.Poll(ctx)\n"
        + "\t\tif err != nil {\n"
        + "\t\t\treturn nil, err\n"
        + "\t\t}\n"
        + "\t\tif onProgress != nil {\n"
        + "\t\t\tfor _, entry := range status.Progress[min(o.reported, len(status.Progress)):] {\n"
        + "\t\t\t\tonProgress(entry)\n"
        + "\t\t\t}\n"
        + "\t\t}\n"
        + "\t\tif len(status.Progress) > o.reported {\n"
        + "\t\t\to.reported = len(status.Progress)\n"
        + "\t\t}\n"
        + "\t}\n"
        + "\tif o.status.Status != \"Succeeded\" {\n"
        + "\t\tfailure := o.status.Error\n"
        + "\t\tif failure == nil {\n"
        + "\t\t\tcode := ErrorCode(\"ProvisioningFailed\")\n"
        + "\t\t\tif o.status.Status == \"Canceled\" {\n"
        + "\t\t\t\tcode = \"OperationCanceled\"\n"
        + "\t\t\t}\n"
        + "\t\t\tfailure = &Error{Code: code, Message: \"The operation ended in state \" + string(o.status.Status) + \" without an error body.\"}\n"
        + "\t\t}\n"
        + "\t\treturn nil, &RequestFailedError{StatusCode: http.StatusOK, Err: failure}\n"
        + "\t}\n"
        + "\tvar result T\n"
        + "\tif o.resourcePath == \"\" {\n"
        + "\t\treturn &result, nil\n"
        + "\t}\n"
        + "\tif err := call(ctx, o.transport, \"GET\", o.resourcePath, nil, &result); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\treturn &result, nil\n"
        + "}\n"
        + "\n"
        + "// ListOptions is how many resources a listing may examine. ⚠ Top is a cap the platform clamps and not a\n"
        + "// promise: the filter runs once per member, so it bounds the work and not the number of results.\n"
        + "type ListOptions struct {\n"
        + "\t// Zero sends nothing.\n"
        + "\tTop int\n"
        + "}\n"
        + "\n"
        + "// Page is one page of a collection — docs/plan/08 § The read path.\n"
        + "type Page[T any] struct {\n"
        + "\t// The resources on this page, ordered by id.\n"
        + "\tValue []T `json:\"value\"`\n"
        + "\t// ⚠ Absent on the last page. Stop when it is absent, never when a page is smaller than you asked\n"
        + "\t// for: a listing runs a permission check per member and the page is clamped.\n"
        + "\tNextLink *string `json:\"nextLink,omitempty\"`\n"
        + "}\n"
        + "\n"
        + "// Pager walks a collection page by page: More says whether NextPage has anything left to fetch.\n"
        + "type Pager[T any] struct {\n"
        + "\ttransport Transport\n"
        + "\tnext      *Request\n"
        + "}\n"
        + "\n"
        + "func newPager[T any](transport Transport, path string, options *ListOptions) *Pager[T] {\n"
        + "\t// ⚠ $top carries its sigil, which is what the gateway reads; a gateway IGNORES a query parameter it\n"
        + "\t// does not recognise, so a misspelling here is a 200 holding page one, for ever. The next page's\n"
        + "\t// $skipToken comes back inside nextLink and is sent as the path and query of that link.\n"
        + "\tquery := url.Values{}\n"
        + "\tif options != nil && options.Top > 0 {\n"
        + "\t\tquery.Set(\"$top\", strconv.Itoa(options.Top))\n"
        + "\t}\n"
        + "\treturn &Pager[T]{transport: transport, next: &Request{Method: \"GET\", Path: path, Query: query}}\n"
        + "}\n"
        + "\n"
        + "// More reports whether a page remains to be fetched. True before the first page.\n"
        + "func (p *Pager[T]) More() bool {\n"
        + "\treturn p.next != nil\n"
        + "}\n"
        + "\n"
        + "// NextPage fetches the next page. ⚠ Calling it when More is false is a programming error and returns one.\n"
        + "func (p *Pager[T]) NextPage(ctx context.Context) (*Page[T], error) {\n"
        + "\tif p.next == nil {\n"
        + "\t\treturn nil, fmt.Errorf(\"the collection has no more pages\")\n"
        + "\t}\n"
        + "\tresponse, err := p.transport.Send(ctx, p.next)\n"
        + "\tif err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tif err := checkStatus(response); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tvar page Page[T]\n"
        + "\tif err := decode(response, &page); err != nil {\n"
        + "\t\treturn nil, err\n"
        + "\t}\n"
        + "\tp.next = nil\n"
        + "\tif page.NextLink != nil {\n"
        + "\t\tnext, err := relative(*page.NextLink)\n"
        + "\t\tif err != nil {\n"
        + "\t\t\treturn nil, err\n"
        + "\t\t}\n"
        + "\t\tp.next = next\n"
        + "\t}\n"
        + "\treturn &page, nil\n"
        + "}\n"
        + "\n"
        + "// All fetches every remaining page and returns the items in order.\n"
        + "func (p *Pager[T]) All(ctx context.Context) ([]T, error) {\n"
        + "\tvar items []T\n"
        + "\tfor p.More() {\n"
        + "\t\tpage, err := p.NextPage(ctx)\n"
        + "\t\tif err != nil {\n"
        + "\t\t\treturn nil, err\n"
        + "\t\t}\n"
        + "\t\titems = append(items, page.Value...)\n"
        + "\t}\n"
        + "\treturn items, nil\n"
        + "}\n";

    // ── Self-check ─────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     What this surface can get wrong, as one line per problem.
    /// </summary>
    /// <param name="files">The emitted files of one api-version.</param>
    /// <remarks>
    ///     ⚠ Narrower than a compiler, and honest about it: every type the client names in a
    ///     signature is one the package declares, no type is declared twice, and every file
    ///     carries its banner. The <c>Generated Go SDK compiles</c> gate is the compiler.
    /// </remarks>
    public static ImmutableArray<string> Problems(ImmutableSortedDictionary<string, string> files) {
        ArgumentNullException.ThrowIfNull(files);

        var problems = new List<string>();
        var models = files.FirstOrDefault(static x => x.Key.EndsWith("/models.go", StringComparison.Ordinal)).Value;
        var client = files.FirstOrDefault(static x => x.Key.EndsWith("/client.go", StringComparison.Ordinal)).Value;
        var runtime = files.FirstOrDefault(static x => x.Key.EndsWith("/runtime.go", StringComparison.Ordinal)).Value;

        if (models is null || client is null || runtime is null) {
            problems.Add(
                "the package is missing models.go, client.go or runtime.go, so the emitter produced something nobody can build."
            );
            return [.. problems];
        }

        var declared = new List<string>();

        foreach (var line in (models + "\n" + client + "\n" + runtime).Split('\n')) {
            if (line.StartsWith("type ", StringComparison.Ordinal)) {
                var name = line[5..].Split(' ', '[')[0];
                declared.Add(name);
            }
        }

        foreach (var duplicate in declared.GroupBy(static x => x, StringComparer.Ordinal)
                     .Where(static x => x.Count() > 1)) {
            problems.Add(
                $"the package declares the type '{duplicate.Key}' {duplicate.Count()} times; Go refuses the redeclaration."
            );
        }

        var exported = declared.ToHashSet(StringComparer.Ordinal);

        // A model reaches the client only through a signature — `(*XResource, error)`,
        // `data XData`, `content XContent`, `Operation[XResource]` — and each of those suffixes is
        // one the models file declares.
        foreach (var line in client.Split('\n')) {
            if (!line.StartsWith("func ", StringComparison.Ordinal)) {
                continue;
            }

            foreach (var token in line.Split(' ', '(', ')', '*', '[', ']', ',')) {
                if (token.Length > 0
                    && char.IsAsciiLetterUpper(token[0])
                    && (token.EndsWith("Resource", StringComparison.Ordinal)
                        || token.EndsWith("Data", StringComparison.Ordinal)
                        || token.EndsWith("Content", StringComparison.Ordinal)
                        || token.EndsWith("Result", StringComparison.Ordinal))
                    && !exported.Contains(token)) {
                    problems.Add(
                        $"client.go names '{token}' in a signature and the package does not declare it; the module fails to build."
                    );
                }
            }
        }

        foreach (var file in files) {
            if (!file.Value.Contains("DO NOT EDIT", StringComparison.Ordinal)) {
                problems.Add(
                    $"'{file.Key}' carries no generator banner; a reader who opens an unmarked file is a reader who edits it."
                );
            }
        }

        problems.Sort(StringComparer.Ordinal);
        return [.. problems.Distinct(StringComparer.Ordinal)];
    }

    // ── Small shared machinery ─────────────────────────────────────────────────────────────────

    static string Head(string version) =>
        Banner
        + "\n// @generated from the published OpenAPI document openapi/"
        + version
        + ".json — docs/plan/21 § Generation's one hop.\n"
        + "// ./build.sh Generate overwrites this file and ./build.sh Architecture fails on a difference.\n";

    static string ScopeContent(DocumentScope scope) => SdkEmitter.Pascal(scope.Kind) + "CreateContent";

    /// <summary>
    ///     The field a scope's client takes on <c>Client</c> — <c>Tenants</c>, <c>Subscriptions</c>,
    ///     <c>ResourceGroups</c>.
    /// </summary>
    static string ScopeClientField(DocumentScope scope) => SdkEmitter.Pascal(scope.Kind) + "s";

    /// <summary>
    ///     A type's one-sentence summary as a sentence that follows another, or nothing — never a trailing space gofmt
    ///     would strip.
    /// </summary>
    static string Summary(DocumentType type) => type.Summary.Length > 0 ? " " + Comment(type.Summary) : string.Empty;

    /// <summary>The field a resource type takes on its provider's group — <c>ManagedClustersAgentPools</c>.</summary>
    static string TypeField(string typePath) => string.Concat(typePath.Split('/').Select(SdkEmitter.Pascal));

    /// <summary>A placeholder as a Go parameter — <c>tenantID</c>.</summary>
    static string Parameter(string placeholder) {
        var name = GoName(placeholder);

        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    /// <summary>A wire name as an exported Go identifier, with Go's spelling of a trailing <c>Id</c>.</summary>
    static string GoName(string wireName) {
        var pascal = SdkEmitter.Pascal(wireName);

        return pascal.EndsWith("Id", StringComparison.Ordinal) ? pascal[..^2] + "ID" : pascal;
    }

    /// <summary>A Go interpreted string literal.</summary>
    static string Quote(string value) =>
        "\""
        + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
        + "\"";

    /// <summary>Text that is safe after <c>//</c>, on one line.</summary>
    static string Comment(string value) =>
        value.Replace("\r\n", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
}
