using CyberCloud.ResourceManager.Contracts.Registry;
using System.Collections.Immutable;
using System.Globalization;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>What one emitted file did.</summary>
/// <param name="FileName">The file, relative to the output directory. Never an absolute path.</param>
/// <param name="ApiVersion">
///     The api-version it describes, or <c>""</c> for <see cref="OpenApiEmitter.IndexFileName" />.
/// </param>
/// <param name="Published">Whether a file of that name was already checked in.</param>
/// <param name="Drifted">
///     Whether the regenerated bytes differ from the checked-in ones. ⚠ This is the whole of
///     docs/plan/23 § The architecture gates' "regenerate byte-identically" row.
/// </param>
/// <param name="StructuralProblems">What <see cref="OpenApiStructure" /> found. Normally empty.</param>
/// <param name="BreakingChanges">
///     What <see cref="OpenApiCompatibility" /> found against the published file. Empty when there
///     was no published file, because a version that was never published cannot be broken.
/// </param>
public sealed record GeneratedDocument(
    string FileName,
    string ApiVersion,
    bool Published,
    bool Drifted,
    ImmutableArray<string> StructuralProblems,
    ImmutableArray<BreakingChange> BreakingChanges
);

/// <summary>
///     What one <c>Generate</c> run inspected and produced. The build's two gates are read off this.
/// </summary>
/// <param name="Providers">How many provider namespaces the registry held.</param>
/// <param name="ResourceTypes">How many resource types.</param>
/// <param name="Documents">One entry per file, ordered by name.</param>
/// <param name="Stale">
///     Checked-in <c>.json</c> files this run did not produce, ordered by name.
///     <para>
///         ⚠ <b>This is the only place a <i>vanished</i> api-version is visible.</b>
///         <see cref="OpenApiCompatibility" /> compares two documents and therefore cannot see a
///         version whose file it was never handed. docs/plan/08 § The provider registry requires that
///         removing a version take a 12-month notice window and a build gate; this is not that gate,
///         but it is the tripwire that stops a version from disappearing without anyone noticing.
///     </para>
/// </param>
public sealed record GenerationReport(
    int Providers,
    int ResourceTypes,
    ImmutableArray<GeneratedDocument> Documents,
    ImmutableArray<string> Stale
) {
    /// <summary>How many api-versions were emitted. The index does not count as one.</summary>
    public int ApiVersions => Documents.Count(x => x.ApiVersion.Length > 0);

    /// <summary>Whether anything at all is wrong.</summary>
    public bool IsClean =>
        Stale.IsEmpty
        && Documents.All(x => !x.Drifted && x.StructuralProblems.IsEmpty && x.BreakingChanges.IsEmpty);
}

/// <summary>
///     Writes ADR-012's OpenAPI surface to a directory and says what changed.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>It writes and then reports drift, rather than refusing to write.</b> The alternative —
///         compare, fail, write nothing — makes a contributor hand-copy the generator's output out of
///         a log. Writing first means the fix for a red <c>Generate</c> is <c>git add</c>, while CI,
///         where the checked-in files are the ones under test, still goes red on the run that
///         produced the difference. Both properties are needed and only this order has both.
///     </para>
///     <para>
///         ⚠ <b>Nothing is ever deleted.</b> A checked-in document this run did not produce is
///         reported as <see cref="GenerationReport.Stale" /> and left alone. Deleting it would be a
///         published contract disappearing in a build step, which is the failure
///         docs/plan/08 § The provider registry's 12-month notice window exists to prevent.
///     </para>
/// </remarks>
public static class OpenApiArtifacts {
    /// <summary>The directory, relative to the repository root, the surface is checked in at.</summary>
    /// <remarks>
    ///     docs/plan/10 § Shape gives the gateway <c>/openapi</c> — "the generated document, per
    ///     api-version" — and this is the same tree on disk, so the gateway serves files rather than
    ///     re-deriving them. ⚠ It is not under <c>artifacts/</c>: that directory is gitignored, and a
    ///     build artifact that is <i>diffed</i> (docs/plan/21 § OpenAPI) has to be tracked to be
    ///     diffable.
    /// </remarks>
    public const string DirectoryName = "openapi";

    /// <summary>
    ///     Emits every document, compares each against what is checked in, and optionally writes.
    /// </summary>
    /// <param name="registry">The built provider registry — the single source.</param>
    /// <param name="directory">Where the documents are checked in.</param>
    /// <param name="write">
    ///     Whether to write the files. <see langword="false" /> is the check-only mode the
    ///     <c>Architecture</c> target uses, so that a gate never has a side effect on the tree it is
    ///     inspecting.
    /// </param>
    /// <returns>What was inspected and what is wrong with it.</returns>
    public static GenerationReport Generate(IProviderRegistry registry, string directory, bool write) {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentException.ThrowIfNullOrEmpty(directory);

        var documents = new List<GeneratedDocument>();
        var produced = new HashSet<string>(StringComparer.Ordinal);

        if (write) {
            Directory.CreateDirectory(directory);
        }

        // The index first, so that a run against an empty registry still writes exactly one valid
        // document rather than nothing at all — see OpenApiEmitter.EmitIndex.
        documents.Add(
            Emit(
                OpenApiEmitter.IndexFileName,
                string.Empty,
                OpenApiEmitter.EmitIndex(registry),
                directory,
                write,
                // The index lists which versions exist, so it changes whenever one is added. Diffing it
                // for compatibility would report every new api-version as a breaking change.
                compareForCompatibility: false
            )
        );

        produced.Add(OpenApiEmitter.IndexFileName);

        foreach (var version in OpenApiEmitter.ApiVersionsOf(registry)) {
            var fileName = OpenApiEmitter.FileNameOf(version);
            produced.Add(fileName);

            documents.Add(
                Emit(
                    fileName,
                    version.Value,
                    OpenApiEmitter.Emit(registry, version),
                    directory,
                    write,
                    compareForCompatibility: true
                )
            );
        }

        var stale = Directory.Exists(directory)
            ? Directory.EnumerateFiles(directory, "*.json")
                .Select(Path.GetFileName)
                .Where(x => x is not null && !produced.Contains(x))
                .Select(x => x!)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToImmutableArray()
            : [];

        return new(
            registry.Namespaces.Length,
            registry.Types.Length,
            [.. documents.OrderBy(x => x.FileName, StringComparer.Ordinal)],
            stale
        );
    }

    /// <summary>
    ///     The emitted documents, keyed by api-version — the input <see cref="DerivedSurfaces" />
    ///     reads.
    /// </summary>
    /// <param name="registry">The built registry.</param>
    /// <remarks>
    ///     ⚠ <b>Emitted afresh rather than read back off disk, and the difference is a failure mode.</b>
    ///     docs/plan/21 § Generation makes the three derived surfaces read the OpenAPI document; if
    ///     they read the <i>checked-in</i> file, a drifted document would silently seed three more
    ///     drifted files and the CLI would describe an API nobody had generated. This is the same
    ///     bytes <see cref="Generate" /> writes, from the same registry, in the same process.
    /// </remarks>
    public static IReadOnlyDictionary<string, JsonObject> Documents(IProviderRegistry registry) {
        ArgumentNullException.ThrowIfNull(registry);

        var byVersion = new Dictionary<string, JsonObject>(StringComparer.Ordinal);

        foreach (var version in OpenApiEmitter.ApiVersionsOf(registry)) {
            byVersion[version.Value] = OpenApiEmitter.Emit(registry, version);
        }

        return byVersion;
    }

    static GeneratedDocument Emit(
        string fileName,
        string apiVersion,
        JsonNode document,
        string directory,
        bool write,
        bool compareForCompatibility
    ) {
        var bytes = DeterministicJson.ToBytes(document);
        var path = Path.Combine(directory, fileName);
        var published = File.Exists(path) ? File.ReadAllBytes(path) : null;

        var breaking = ImmutableArray<BreakingChange>.Empty;

        if (published is not null && compareForCompatibility) {
            var parsed = DeterministicJson.TryParse(published);

            breaking = parsed is null
                ? [
                    new BreakingChange(
                        "",
                        OpenApiCompatibility.Unreadable,
                        $"'{fileName}' is checked in and does not parse as JSON, so the compatibility of "
                        + "this change cannot be established. Restore it from git rather than "
                        + "regenerating over it."
                    )
                ]
                : OpenApiCompatibility.Diff(parsed, document);
        }

        var drifted = published is null || !published.AsSpan().SequenceEqual(bytes);

        if (write && drifted) {
            File.WriteAllBytes(path, bytes);
        }

        return new(
            fileName,
            apiVersion,
            published is not null,
            drifted,
            OpenApiStructure.Validate(document),
            breaking
        );
    }

    /// <summary>
    ///     The report as one line per document, for a build log.
    /// </summary>
    /// <param name="report">The report.</param>
    public static ImmutableArray<string> Describe(GenerationReport report) {
        ArgumentNullException.ThrowIfNull(report);

        var lines = new List<string> {
            string.Create(
                CultureInfo.InvariantCulture,
                $"{report.Providers} provider namespace(s), {report.ResourceTypes} resource type(s), "
                + $"{report.ApiVersions} api-version(s)"
            )
        };

        foreach (var document in report.Documents) {
            lines.Add(string.Create(
                CultureInfo.InvariantCulture,
                // "differs" rather than "rewritten": this line is printed by the check-only run too,
                // where nothing was written and claiming otherwise would be a lie in a build log.
                $"  {(document.Drifted ? "±" : "=")} {document.FileName} — "
                + $"{(document.Published ? document.Drifted ? "differs from the registry" : "unchanged" : "new")}, "
                + $"{document.StructuralProblems.Length} structural problem(s), "
                + $"{document.BreakingChanges.Length} breaking change(s)"
            ));
        }

        foreach (var stale in report.Stale) {
            lines.Add($"  ! {stale} — checked in and not produced by this run");
        }

        return [.. lines];
    }
}
