using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>
///     ADR-012's third surface: the .NET SDK's models, collections, resources and
///     <c>Operation&lt;T&gt;</c> pollers.
/// </summary>
/// <remarks>
///     <para>
///         docs/plan/21 § The .NET SDK fixes the shape — <c>{Type}Resource</c> /
///         <c>{Type}Collection</c> / <c>{Type}Data</c> from <c>Azure.ResourceManager</c>,
///         <c>Operation&lt;T&gt;</c> + <c>WaitUntil</c> from <c>Azure.Core</c>, and
///         <c>GetProgressAsync()</c>, which is ours because <i>"Azure's LROs expose no progress; ours
///         do and the SDK should not hide it"</i>.
///     </para>
///     <para>
///         ⚠ <b>Half of the SDK is hand-written and none of it is here.</b> docs/plan/21 § Generation:
///         <i>"Hand-written on top: the credential types, the pipeline policies, the convenience
///         methods … and the tests. Everything else is regenerated per release and never edited."</i>
///         This emitter produces the "everything else" and produces <c>partial</c> types throughout,
///         so the hand-written half extends the generated one in the same type rather than wrapping
///         it — a wrapper is a second surface with a second set of names.
///     </para>
///     <para>
///         ⚠ <b>The output is checked in and is not in a <c>.csproj</c> yet, and that is a stated
///         limitation rather than an oversight.</b> The clients reference <c>Azure.Core</c>'s
///         <c>Operation&lt;T&gt;</c>, <c>Response&lt;T&gt;</c> and <c>WaitUntil</c>, which arrive with
///         the hand-written half; compiling this file before that exists would fail for reasons that
///         have nothing to do with the generator. The models below depend on nothing but the BCL. The
///         drift gate does not care either way — it compares bytes — so the contract this surface owes
///         is enforced from the day it is generated rather than from the day it compiles.
///     </para>
///     <para>
///         ⚠ <b>Determinism, in a language rather than in JSON.</b> No timestamp, no machine name, no
///         path, no <c>GeneratedCodeAttribute</c> version stamp — every one of those is a file that
///         differs on two machines. Members are emitted in the document's own sorted order, and every
///         number is formatted with <see cref="CultureInfo.InvariantCulture" />.
///     </para>
/// </remarks>
public static class SdkEmitter {
    /// <summary>The directory, under the generated root, this surface is written to.</summary>
    public const string DirectoryName = "sdk";

    /// <summary>The namespace the generated types live in.</summary>
    public const string Namespace = "CyberCloud.Sdk.Generated";

    /// <summary>Emits the SDK source for one api-version's document.</summary>
    /// <param name="document">An emitted OpenAPI document.</param>
    /// <returns>One C# compilation unit, as text.</returns>
    public static string Emit(JsonObject document) {
        ArgumentNullException.ThrowIfNull(document);

        var version = DocumentReader.VersionOf(document);
        var types = DocumentReader.TypesOf(document);
        var names = ModelNames(types);

        var built = new StringBuilder();

        built.Append("// <auto-generated />\n")
            .Append("//\n")
            .Append("// The Cyber Cloud .NET SDK at api-version ")
            .Append(version)
            .Append(".\n")
            .Append("//\n")
            .Append("// Generated from ")
            .Append(OpenApiArtifacts.DirectoryName)
            .Append('/')
            .Append(version)
            .Append(".json by CyberCloud.ResourceManager.Contracts.Generation.SdkEmitter —\n")
            .Append("// docs/plan/02 § ADR-012 and docs/plan/21 § Generation. Hand edits are overwritten by\n")
            .Append("// ./build.sh Generate and fail the Generated surfaces gate.\n")
            .Append("//\n")
            .Append("// ⚠ Every type is partial. The credential types, the pipeline policies and the\n")
            .Append("// convenience methods are hand-written on top and extend these in place —\n")
            .Append("// docs/plan/21 § Generation.\n")
            .Append('\n')
            .Append("#nullable enable\n")
            .Append('\n')
            .Append("using System;\n")
            .Append("using System.Collections.Generic;\n")
            .Append("using System.Text.Json.Serialization;\n")
            .Append("using System.Threading;\n")
            .Append("using System.Threading.Tasks;\n")
            .Append('\n')
            .Append("namespace ")
            .Append(Namespace)
            .Append(";\n");

        built.Append("\n/// <summary>The api-version every client in this file sends.</summary>\n")
            .Append("public static class GeneratedApiVersion {\n")
            .Append("    /// <summary>⚠ A date, immutable, and there is no 'latest' — docs/plan/10 § API versioning.</summary>\n")
            .Append("    public const string Value = ")
            .Append(Quote(version))
            .Append(";\n}\n");

        foreach (var type in types) {
            AppendType(built, type, names[type.ResourceType], version);
        }

        return built.ToString();
    }

    /// <summary>The file one api-version's SDK is written to.</summary>
    /// <param name="apiVersion">The api-version.</param>
    public static string FileNameOf(string apiVersion) => apiVersion + ".cs";

    // ── Model naming ───────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     One model name per resource type, unique across the document.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         ⚠ <b>Built from the declared display name, not pluralised down from the type path.</b>
    ///         English pluralisation is not computable — the same reason
    ///         <c>GroupVersionKind.Plural</c> is carried rather than derived — so <c>servers</c> to
    ///         <c>Server</c> is a guess that works until <c>addresses</c> or <c>indices</c>. When a
    ///         type declares no display name the path segment is used verbatim and the resulting
    ///         <c>DatabasesResource</c> is ugly on purpose: it is visible pressure to declare one.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>Collisions are resolved by prefixing the provider, and only for the colliding
    ///         types.</b> docs/plan/03 § Providers plans a <c>DBforPostgreSQL/servers</c> and a
    ///         <c>DBforMySQL/servers</c>; prefixing every type would give the other eighteen providers
    ///         names nobody wants to type, and prefixing none would give two types one class.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>The provider prefix cannot separate two colliding types in the <i>same</i>
    ///         namespace, so the result is checked rather than assumed.</b> A
    ///         <c>Streaming/kafkaClusters/topics</c> and a <c>Streaming/kafkaTopics</c> that both
    ///         declare the display name <c>Topic</c> both resolve to <c>StreamingTopic</c> — the
    ///         prefix is the same because the namespace is. That produced two C# classes with one
    ///         name in a generated file, which is a compiler error in whatever consumes the SDK
    ///         rather than in this build, arriving with no hint of where it came from. The second
    ///         pass falls back to the type path, which is unique by construction — the registry keys
    ///         on it — and throwing is the last resort for the case where even that collides.
    ///     </para>
    /// </remarks>
    static ImmutableDictionary<string, string> ModelNames(ImmutableArray<DocumentType> types) {
        var bare = new Dictionary<string, string>(StringComparer.Ordinal);
        var counts = new Dictionary<string, int>(StringComparer.Ordinal);

        foreach (var type in types) {
            var name = Pascal(type.DisplayName.Length > 0 ? type.DisplayName : type.TypePath);
            bare[type.ResourceType] = name;
            counts[name] = counts.GetValueOrDefault(name) + 1;
        }

        var resolved = ImmutableDictionary.CreateBuilder<string, string>(StringComparer.Ordinal);
        var taken = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var type in types) {
            var name = bare[type.ResourceType];
            var segments = type.ProviderNamespace.Split('.');

            if (counts[name] > 1) {
                name = Pascal(segments[^1]) + name;
            }

            // The prefix separates namespaces and nothing else. Two types in one namespace that
            // still agree fall back to the type path, whose uniqueness the registry already
            // guarantees — `kafkaClusters/topics` gives `KafkaClustersTopics`.
            if (taken.ContainsKey(name)) {
                name = Pascal(segments[^1]) + Pascal(type.TypePath);
            }

            if (taken.TryGetValue(name, out var owner)) {
                throw new InvalidOperationException(
                    $"'{type.ResourceType}' and '{owner}' both generate the SDK model name "
                    + $"'{name}'. Two classes with one name do not compile, and the error would "
                    + "surface in whatever consumes the SDK rather than here. Give one of them a "
                    + "distinct IResourceTypeBuilder.Display."
                );
            }

            taken[name] = type.ResourceType;
            resolved[type.ResourceType] = name;
        }

        return resolved.ToImmutable();
    }

    // ── One resource type ──────────────────────────────────────────────────────────────────────

    static void AppendType(StringBuilder built, DocumentType type, string model, string version) {
        var leaves = DocumentReader.LeavesOf(type.Body);

        AppendEnums(built, model, leaves);
        AppendData(built, type, model, leaves);
        AppendResource(built, type, model);
        AppendCollection(built, type, model, version);
    }

    /// <summary>
    ///     One C# enum per closed set, so a caller cannot pass a value the API refuses.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>This is the enum gap's whole payoff on this surface.</b> Without
    ///     <c>SchemaProperty.AllowedValues</c> every one of these was a <c>string</c>, the compiler
    ///     could not catch a typo, and a caller learned the four values from a <c>400</c>.
    ///     <para>
    ///         ⚠ A <c>Unknown = 0</c> member, per this repository's convention and for a sharper
    ///         reason here: a <c>default(T)</c> that named a real sku would silently send one.
    ///     </para>
    /// </remarks>
    static void AppendEnums(StringBuilder built, string model, ImmutableArray<SchemaLeaf> leaves) {
        foreach (var leaf in leaves) {
            var values = DocumentReader.EnumOf(leaf.Schema);

            if (values.IsEmpty) {
                continue;
            }

            built.Append("\n/// <summary>The values ")
                .Append(Escape(leaf.JsonPointer))
                .Append(" accepts. ⚠ Closed: the write path refuses anything else.</summary>\n")
                .Append("public enum ")
                .Append(EnumName(model, leaf))
                .Append(" {\n")
                .Append("    /// <summary>Never assigned. Not a value the API accepts.</summary>\n")
                .Append("    Unknown = 0")
                .Append(values.IsEmpty ? "\n" : ",\n");

            for (var i = 0; i < values.Length; i++) {
                built.Append("\n    /// <summary>")
                    .Append(Escape(values[i]))
                    .Append("</summary>\n")
                    .Append("    [JsonStringEnumMemberName(")
                    .Append(Quote(values[i]))
                    .Append(")]\n")
                    .Append("    ")
                    .Append(Pascal(values[i]))
                    .Append(" = ")
                    .Append((i + 1).ToString(CultureInfo.InvariantCulture))
                    .Append(i == values.Length - 1 ? "\n" : ",\n");
            }

            built.Append("}\n");
        }
    }

    static string EnumName(string model, SchemaLeaf leaf) => model + Pascal(leaf.Name);

    static void AppendData(
        StringBuilder built,
        DocumentType type,
        string model,
        ImmutableArray<SchemaLeaf> leaves
    ) {
        built.Append("\n/// <summary>The body of a ")
            .Append(Escape(type.ResourceType))
            .Append(".</summary>\n")
            .Append("/// <remarks>")
            .Append(Escape(type.Summary.Length > 0 ? type.Summary : type.DisplayName))
            .Append("</remarks>\n")
            .Append("public sealed partial class ")
            .Append(model)
            .Append("Data {\n");

        foreach (var leaf in leaves) {
            // A container is a nested object in the wire body; it is flattened onto this class with
            // a JsonPropertyName that carries the nesting, so a caller sets one property rather than
            // building the envelope by hand.
            if (leaf.IsObject) {
                continue;
            }

            AppendMember(built, model, leaf);
        }

        // ⚠ No special case for tags, and that is the tag fix paying off on this surface. The bag is
        // a property of the emitted body schema now, so it arrives as a leaf like everything else. A
        // branch here would be this emitter knowing a platform fact the document did not carry — which
        // is exactly the arrangement that let the document under-describe the API in the first place.
        built.Append("}\n");
    }

    static void AppendMember(StringBuilder built, string model, SchemaLeaf leaf) {
        var schema = leaf.Schema;
        var description = DocumentReader.Text(schema["description"]);

        built.Append("\n    /// <summary>")
            .Append(Escape(description.Length > 0 ? description : leaf.Name))
            .Append("</summary>\n");

        var notes = new List<string>();

        if (leaf.Required) {
            notes.Add("Required on a create.");
        }

        if (DocumentReader.Flag(schema["readOnly"])) {
            notes.Add("⚠ The server owns this: a body that sets it is refused rather than ignored.");
        }

        if (DocumentReader.Flag(schema["x-cybercloud-secret"])) {
            notes.Add("⚠ Secret. It is never returned — a read leaves this null whatever was set.");
        }

        if (DocumentReader.Flag(schema["x-cybercloud-immutable"])) {
            notes.Add("⚠ Cannot change after create.");
        }

        if (schema["default"] is { } fallback) {
            notes.Add("Defaults to " + fallback.ToJsonString() + " when left unset.");
        }

        if (notes.Count > 0) {
            built.Append("    /// <remarks>").Append(Escape(string.Join(" ", notes))).Append("</remarks>\n");
        }

        built.Append("    [JsonPropertyName(")
            .Append(Quote(leaf.Name))
            .Append(")]\n")
            .Append("    public ")
            // ⚠ `required` rather than a nullable type or `= null!`. A required property that is not
            // set is a body the API refuses, and C#'s own `required` makes that a compile error at the
            // object initialiser rather than a 400 at run time — which is the whole reason the SDK is
            // generated from the same schema the validator reads.
            .Append(Required(leaf) ? "required " : string.Empty)
            .Append(ClrType(model, leaf))
            .Append(' ')
            .Append(Pascal(leaf.Name))
            .Append(" { get; set; }")
            .Append(Initialiser(model, leaf))
            .Append('\n');
    }

    /// <summary>
    ///     Whether a member takes C#'s <c>required</c> modifier.
    /// </summary>
    /// <remarks>
    ///     ⚠ A read-only property is never <c>required</c>: the server sets it and a caller may not,
    ///     so demanding it at the object initialiser would make the model unusable for a create.
    ///     A collection is never <c>required</c> either — it is initialised empty, which is the same
    ///     thing an omitted array means.
    /// </remarks>
    static bool Required(SchemaLeaf leaf) =>
        leaf.Required
        && !DocumentReader.Flag(leaf.Schema["readOnly"])
        && DocumentReader.TypeOf(leaf.Schema) is not ("array" or "object");

    /// <summary>
    ///     The CLR type of one leaf.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>An array's element type is real, and this is where gap 2 pays off.</b> Before
    ///     <c>SchemaProperty.ElementKind</c> an array reached the document as <c>items: {}</c> and the
    ///     only honest rendering was <c>IList&lt;object&gt;</c> — a member no caller could use without
    ///     casting and no compiler could check.
    /// </remarks>
    static string ClrType(string model, SchemaLeaf leaf) {
        var schema = leaf.Schema;
        var nullable = DocumentReader.IsNullable(schema) || !leaf.Required;

        if (!DocumentReader.EnumOf(schema).IsEmpty && DocumentReader.TypeOf(schema) != "array") {
            return EnumName(model, leaf) + (nullable ? "?" : string.Empty);
        }

        return DocumentReader.TypeOf(schema) switch {
            "array" => "IList<" + Scalar(schema["items"] as JsonObject ?? [], model, leaf) + ">",
            "object" => "IDictionary<string, string>",
            var scalar => Suffix(Scalar(schema, model, leaf), scalar, nullable)
        };
    }

    static string Scalar(JsonObject schema, string model, SchemaLeaf leaf) {
        if (!DocumentReader.EnumOf(schema).IsEmpty) {
            return EnumName(model, leaf);
        }

        return DocumentReader.TypeOf(schema) switch {
            // ⚠ The formats become the CLR types a caller expects rather than strings they have to
            // parse. `Guid` and `DateTimeOffset` are checked by the server too — see SchemaFormat.
            "string" when DocumentReader.Text(schema["format"]) == "uuid" => "Guid",
            "string" when DocumentReader.Text(schema["format"]) == "date-time" => "DateTimeOffset",
            "string" when DocumentReader.Text(schema["format"]) == "uri" => "Uri",
            "string" => "string",
            // long rather than int: an integer in JSON has no width, and a storage size in bytes
            // overflows an int before it overflows anything real.
            "integer" => "long",
            "number" => "double",
            "boolean" => "bool",
            _ => "string"
        };
    }

    static string Suffix(string clr, string jsonType, bool nullable) {
        if (!nullable) {
            return clr;
        }

        // A reference type takes `?` from the nullable context; a value type takes Nullable<T>. Both
        // are spelled `?` and both are correct — this method exists so the reason is written down.
        _ = jsonType;
        return clr + "?";
    }

    static string Initialiser(string model, SchemaLeaf leaf) =>
        DocumentReader.TypeOf(leaf.Schema) switch {
            // ⚠ Initialised, because a null collection is the member a caller has to new up before
            // using and forgets to. It stays settable so a caller can assign one wholesale.
            "array" => " = new List<" + Scalar(leaf.Schema["items"] as JsonObject ?? [], model, leaf) + ">();",
            "object" => " = new Dictionary<string, string>(StringComparer.Ordinal);",
            _ => string.Empty
        };

    static void AppendResource(StringBuilder built, DocumentType type, string model) {
        built.Append("\n/// <summary>One ")
            .Append(Escape(type.DisplayName))
            .Append(", and the operations on it.</summary>\n")
            .Append("public sealed partial class ")
            .Append(model)
            .Append("Resource {\n")
            .Append("    /// <summary>The resource's fully qualified id.</summary>\n")
            .Append("    public string Id { get; init; } = string.Empty;\n")
            .Append("\n    /// <summary>The body, projected at this api-version.</summary>\n")
            .Append("    public ")
            .Append(model)
            .Append("Data Data { get; init; } = new();\n")
            .Append("\n    /// <summary>Re-reads the resource.</summary>\n")
            .Append("    public partial Task<Response<")
            .Append(model)
            .Append("Resource>> GetAsync(CancellationToken cancellationToken = default);\n")
            .Append("\n    /// <summary>Amends the resource. A merge patch: what is not set is not changed.</summary>\n")
            .Append("    public partial Task<Operation<")
            .Append(model)
            .Append("Resource>> UpdateAsync(\n        WaitUntil waitUntil,\n        ")
            .Append(model)
            .Append("Data data,\n        CancellationToken cancellationToken = default);\n")
            .Append("\n    /// <summary>Deletes the resource.")
            .Append(
                type.SoftDeleteDays > 0
                    ? " ⚠ Recoverable for "
                      + DocumentReader.Count(type.SoftDeleteDays)
                      + " day(s) — docs/plan/06 § Tags, locks."
                    : " ⚠ Permanent: this type declares no soft-delete window."
            )
            .Append("</summary>\n")
            .Append("    public partial Task<Operation> DeleteAsync(\n        WaitUntil waitUntil,\n")
            .Append("        CancellationToken cancellationToken = default);\n");

        foreach (var action in type.Actions) {
            AppendAction(built, model, action);
        }

        built.Append("}\n");
    }

    static void AppendAction(StringBuilder built, string model, DocumentAction action) {
        var name = Pascal(action.Name);

        // ⚠ THE ACTION-SCHEMA GAP, CASHED IN. With no declared response an action could only return a
        // JsonElement and the caller had to know its shape from documentation. With one it returns a
        // class, and a secret action's return type is the reviewable list of what leaves the platform.
        // Nested inside the resource, so the names need no model prefix and read as what they are at
        // the call site: `WidgetResource.PingResult`.
        var result = action.Response is null ? "System.Text.Json.JsonElement" : name + "Result";
        var request = action.Request is null ? null : name + "Content";

        if (action.Request is { } requestSchema) {
            AppendPayload(built, request!, requestSchema, "The parameters of " + action.Name + ".");
        }

        if (action.Response is { } responseSchema) {
            AppendPayload(
                built,
                result,
                responseSchema,
                "What " + action.Name + " returns."
                + (action.Secret ? " ⚠ Secret material: never log or cache this." : string.Empty)
            );
        }

        built.Append("\n    /// <summary>")
            .Append(Escape(name))
            .Append(". ⚠ An action never creates — a POST to a name that does not exist is a 404.")
            .Append(action.Secret ? " ⚠ The response carries secret material and is always audited." : string.Empty)
            .Append("</summary>\n")
            .Append("    public partial Task<")
            .Append(action.LongRunning ? "Operation<" + result + ">" : "Response<" + result + ">")
            .Append("> ")
            .Append(name)
            .Append("Async(\n");

        if (action.LongRunning) {
            built.Append("        WaitUntil waitUntil,\n");
        }

        if (request is { }) {
            built.Append("        ").Append(request).Append(" content,\n");
        }

        built.Append("        CancellationToken cancellationToken = default);\n");
    }

    /// <summary>
    ///     An action's request or response, as a nested class on the resource.
    /// </summary>
    /// <remarks>
    ///     Nested rather than top-level, so <c>listKeys</c> on two resource types cannot collide and
    ///     so the type reads as what it is at the call site: <c>ServerResource.ListKeysResult</c>.
    /// </remarks>
    static void AppendPayload(StringBuilder built, string name, JsonObject schema, string summary) {
        built.Append("\n    /// <summary>").Append(Escape(summary)).Append("</summary>\n")
            .Append("    public sealed partial class ")
            .Append(name)
            .Append(" {\n");

        foreach (var leaf in DocumentReader.LeavesOf(schema)) {
            if (leaf.IsObject) {
                continue;
            }

            built.Append("\n        /// <summary>")
                .Append(Escape(DocumentReader.Text(leaf.Schema["description"]) is { Length: > 0 } text
                    ? text
                    : leaf.Name))
                .Append("</summary>\n")
                .Append("        [JsonPropertyName(")
                .Append(Quote(leaf.Name))
                .Append(")]\n")
                .Append("        public ")
                .Append(Required(leaf) ? "required " : string.Empty)
                .Append(ClrType(name, leaf))
                .Append(' ')
                .Append(Pascal(leaf.Name))
                .Append(" { get; set; }")
                .Append(Initialiser(name, leaf))
                .Append('\n');
        }

        built.Append("    }\n");
    }

    /// <summary>
    ///     The ancestor parameters a nested type's collection takes, as C# parameter declarations.
    /// </summary>
    /// <param name="type">The resource type.</param>
    /// <remarks>
    ///     <para>
    ///         ⚠ <b>Until 2026-08-12 this was nothing, and the loss was silent in exactly the way the
    ///         CLI's was.</b> A collection for <c>servers/databases</c> emitted
    ///         <c>CreateOrUpdateAsync(WaitUntil, string name, Data, CancellationToken)</c> — a
    ///         signature that compiles, reads perfectly, and cannot build the URL its own
    ///         <c>PathTemplate</c> declares, because <c>{serversName}</c> has no argument. Nothing
    ///         complained: an absent parameter is not a diagnostic anywhere, and the hand-written half
    ///         of the SDK is <c>partial</c>, so the missing piece looked like something a human was
    ///         going to supply.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>Ancestors come FIRST, outermost first, which is the order the URL reads in.</b> A
    ///         caller writing <c>GetAsync(serversName, name)</c> is writing the path left to right;
    ///         any other order makes two strings of the same type swappable at the call site with no
    ///         compile error and a 404 at run time.
    ///     </para>
    ///     <para>
    ///         ⚠ Named for the placeholder rather than singularised, for
    ///         <c>CliEmitter.AncestorFlagName</c>'s reason: nothing here knows the singular of a
    ///         provider's own segment.
    ///     </para>
    /// </remarks>
    static ImmutableArray<string> AncestorParametersOf(DocumentType type) {
        var placeholders = DocumentReader.AncestorPlaceholdersOf(type.Path);
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var placeholder in placeholders) {
            // ⚠ A type path whose segments repeat — `a/a/b` — would emit `string aName, string aName`,
            // which is CS0100 in a file nothing compiles until a consumer does. Thrown here so the
            // failure names the type rather than arriving as a compiler error in generated code.
            if (!seen.Add(Camel(placeholder))) {
                throw new InvalidOperationException(
                    $"'{type.ResourceType}' has two ancestors whose placeholder is '{placeholder}', so "
                    + "the generated collection would declare one parameter name twice and the SDK "
                    + "would not compile. Give the type path distinct segments — docs/plan/12 "
                    + "§ Child resources."
                );
            }
        }

        return [.. placeholders.Select(x => "string " + Camel(x))];
    }

    /// <summary>An identifier as <c>camelCase</c>, invariantly.</summary>
    static string Camel(string value) {
        var pascal = Pascal(value);
        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    static void AppendCollection(StringBuilder built, DocumentType type, string model, string version) {
        var ancestors = AncestorParametersOf(type);
        var leading = ancestors.IsEmpty ? string.Empty : string.Join(", ", ancestors) + ", ";

        built.Append("\n/// <summary>The ")
            .Append(Escape(type.DisplayPlural))
            .Append(
                ancestors.IsEmpty
                    ? " in one resource group.</summary>\n"
                    : " in one parent.</summary>\n"
            )
            .Append("/// <remarks>⚠ Every write is long-running: docs/plan/08 § The write path, end to end\n")
            .Append("/// ends in a 202 for every verb, so there is no synchronous overload to offer.")
            .Append(
                ancestors.IsEmpty
                    ? "</remarks>\n"
                    : "\n/// ⚠ The leading parameter(s) name the ancestors this type nests inside —\n"
                    + "/// docs/plan/12 § Child resources addresses a child\n"
                    + "/// '…/{parentType}/{parentName}/{childType}/{childName}', so the parent's name is\n"
                    + "/// part of the address rather than part of the body.</remarks>\n"
            )
            .Append("public sealed partial class ")
            .Append(model)
            .Append("Collection {\n")
            .Append("    /// <summary>The resource type these address.</summary>\n")
            .Append("    public const string ResourceType = ")
            .Append(Quote(type.ResourceType))
            .Append(";\n")
            .Append("\n    /// <summary>The URL template, with the api-version this file was generated at.</summary>\n")
            .Append("    public const string PathTemplate = ")
            .Append(Quote(type.Path))
            .Append(";\n")
            .Append("\n    /// <inheritdoc cref=\"GeneratedApiVersion.Value\" />\n")
            .Append("    public const string ApiVersion = ")
            .Append(Quote(version))
            .Append(";\n")
            .Append("\n    /// <summary>Creates or replaces one ")
            .Append(Escape(type.DisplayName))
            .Append(".</summary>\n")
            .Append("    /// <remarks>⚠ Poll with GetProgressAsync() rather than only WaitForCompletionAsync():\n")
            .Append("    /// docs/plan/21 § The .NET SDK — \"Azure's LROs expose no progress; ours do and the\n")
            .Append("    /// SDK should not hide it\".</remarks>\n")
            .Append("    public partial Task<Operation<")
            .Append(model)
            .Append("Resource>> CreateOrUpdateAsync(\n        WaitUntil waitUntil,\n        ")
            .Append(leading)
            .Append("string name,\n        ")
            .Append(model)
            .Append("Data data,\n        CancellationToken cancellationToken = default);\n")
            .Append("\n    /// <summary>Reads one ")
            .Append(Escape(type.DisplayName))
            .Append(" by name.</summary>\n")
            .Append("    public partial Task<Response<")
            .Append(model)
            .Append("Resource>> GetAsync(")
            .Append(leading)
            .Append("string name, CancellationToken cancellationToken = default);\n")
            .Append("\n    /// <summary>The ")
            .Append(Escape(type.DisplayPlural))
            .Append(ancestors.IsEmpty ? " in this group, paged.</summary>\n" : " in one parent, paged.</summary>\n")
            .Append("    public partial AsyncPageable<")
            .Append(model)
            .Append("Resource> GetAllAsync(")
            // ⚠ The listing takes the ancestors too. A child collection with no ancestor parameter
            // could only list "every database in the group", which is not a scope the API serves —
            // the URL it would GET is the interleaved one with a placeholder left in it.
            .Append(ancestors.IsEmpty ? string.Empty : string.Join(", ", ancestors) + ", ")
            .Append("CancellationToken cancellationToken = default);\n")
            .Append("}\n");
    }

    // ── Small shared machinery ─────────────────────────────────────────────────────────────────

    /// <summary>
    ///     Any identifier-ish string as <c>PascalCase</c>, invariantly.
    /// </summary>
    /// <remarks>
    ///     ⚠ <see cref="char.ToUpperInvariant(char)" /> throughout: under <c>tr-TR</c> a culture-aware
    ///     upper of <c>i</c> is <c>İ</c>, which would emit a different — and uncompilable — identifier
    ///     than the one CI checked in. A leading digit is prefixed rather than dropped, because
    ///     <c>1x</c> and <c>x</c> would otherwise be one member.
    /// </remarks>
    internal static string Pascal(string value) {
        var built = new StringBuilder(value.Length);
        var upper = true;

        foreach (var current in value) {
            if (!char.IsLetterOrDigit(current)) {
                upper = true;
                continue;
            }

            built.Append(upper ? char.ToUpperInvariant(current) : current);
            upper = false;
        }

        if (built.Length == 0) {
            return "Value";
        }

        return char.IsAsciiDigit(built[0]) ? "N" + built : built.ToString();
    }

    /// <summary>A C# string literal. ⚠ Verbatim-free, so a backslash cannot end the literal early.</summary>
    static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    /// <summary>
    ///     Text that is safe inside an XML doc comment, on one line.
    /// </summary>
    /// <remarks>
    ///     ⚠ A newline in a description would end the <c>///</c> and turn the rest of the sentence
    ///     into a syntax error, so it is folded rather than escaped.
    /// </remarks>
    static string Escape(string value) =>
        value.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal)
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
}
