using System.Collections.Immutable;
using System.Text;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>
///     The portal's typed client: ADR-012's surfaces, one language over.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>THE DECISION ISSUE #21 ASKED FOR: THIS READS THE PUBLISHED OPENAPI DOCUMENT, NOT THE
///         REGISTRY.</b> docs/plan/21 § Generation's one hop is what makes the compatibility diff over
///         that document cover the CLI, the SDK and the forms at once; a client generated from the
///         registry instead would sit outside that guarantee — it could describe a field the published
///         contract does not have, and no gate would notice. <see cref="ChartAnnotationEmitter" /> is
///         the one surface that had to read the registry, and its reason does not apply here: a
///         chart pairing is <c>ResourceTypeRegistration.Chart</c>, which appears in no emitted
///         document, whereas every fact a TypeScript client needs is in one.
///     </para>
///     <para>
///         ⚠ <b>Nothing here talks to the network, and that is the seam.</b> The client takes an
///         <c>ApiTransport</c> and calls it; the portal supplies one over Angular's
///         <c>HttpClient</c>, with its interceptors, its bearer token and its error handling.
///         Generating the fetch would put authentication in a file that is overwritten on every
///         build, and would make the portal's transport a second HTTP client beside the one the app
///         already has — portal/README.md § Rules: <i>"The portal has no privileged path. It calls
///         the same public REST API as the CLI, with the same token."</i>
///     </para>
///     <para>
///         ⚠ <b>Every file carries a banner in its first 2 KB, including <c>package.json</c>.</b>
///         <c>Build.Architecture</c>'s rule 6 reads the head of every file under
///         <c>portal/libs/api</c> and fails on one that does not say it is generated. JSON cannot
///         hold a comment, so the manifest carries a <c>"//"</c> key — which is what
///         <c>portal/libs/api/README.md</c> asks for.
///     </para>
///     <para>
///         ⚠ <b>What this cannot check, said plainly.</b> Nothing in the .NET build compiles
///         TypeScript, and <c>portal/eslint.config.mjs</c> ignores <c>libs/api/**</c> — so a
///         generated file that does not type-check is caught by the portal's own <c>ng build</c>,
///         one target later, and only once something imports it. <see cref="Problems" /> is the
///         cheap check that stands in the gap: it asserts that every type this emitter references is
///         one it also declares, which is the failure the .NET SDK emitter shipped and nothing
///         caught.
///     </para>
/// </remarks>
public static class TypeScriptEmitter {
    /// <summary>The package name the portal imports.</summary>
    /// <remarks>⚠ <c>portal/libs/api/README.md</c>'s, and <c>portal/tsconfig.base.json</c> maps it.</remarks>
    public const string PackageName = "@cybercloud/api";

    /// <summary>The schema version of the client's own shape.</summary>
    public const string FormatVersion = "1";

    /// <summary>The banner every emitted file carries, as a line comment.</summary>
    const string Banner =
        "// @generated by CyberCloud.ResourceManager.Contracts.Generation.TypeScriptEmitter — DO NOT EDIT.";

    /// <summary>
    ///     Emits the whole package: one entry per file, keyed by its path under
    ///     <c>portal/libs/api</c>.
    /// </summary>
    /// <param name="document">An emitted OpenAPI document.</param>
    /// <returns>The files, ordered by path.</returns>
    /// <remarks>
    ///     ⚠ <b>One api-version per package rather than one file per version, which is where this
    ///     surface differs from the other three.</b> The CLI carries every version it was built with
    ///     and selects between them at run time (<c>--api-version</c>); a portal build is deployed
    ///     against one platform and its bundle budget is measured in kilobytes — docs/plan/23's
    ///     row — so shipping N versions of every model to every browser to use one of them is a cost
    ///     with no reader. The version is a constant in the client, and a portal that needs an older
    ///     one is a portal built from an older commit.
    /// </remarks>
    public static ImmutableSortedDictionary<string, string> Emit(JsonObject document) {
        ArgumentNullException.ThrowIfNull(document);

        var version = DocumentReader.VersionOf(document);
        var types = DocumentReader.TypesOf(document);
        var scopes = DocumentReader.ScopesOf(document);

        return ImmutableSortedDictionary.CreateRange(
            StringComparer.Ordinal,
            new Dictionary<string, string>(StringComparer.Ordinal) {
                ["package.json"] = Manifest(version),
                ["tsconfig.json"] = ProjectFile(),
                ["src/index.ts"] = Index(),
                ["src/transport.ts"] = Transport(version),
                ["src/models.ts"] = Models(document, types, scopes),
                ["src/client.ts"] = Client(version, types, scopes)
            }
        );
    }

    // ── package.json ───────────────────────────────────────────────────────────────────────────

    static string Manifest(string version) {
        var manifest = new JsonObject {
            // ⚠ First member, because the architecture gate reads the first 2 KB and a manifest
            // whose banner sat after a long dependency list would fail a check it satisfies.
            ["//"] = "@generated — DO NOT EDIT. Emitted by ./build.sh Generate from openapi/"
                + version + ".json; docs/plan/03 § Assembly graph rules, rule 6.",
            ["name"] = PackageName,
            ["version"] = "0.0.0",
            // ⚠ Private: this package is a workspace library, not something published to a registry.
            // docs/plan/21 § Other SDKs is where a published TypeScript SDK would be decided, and it
            // has not been.
            ["private"] = true,
            ["type"] = "module",
            ["main"] = "src/index.ts",
            ["types"] = "src/index.ts",
            ["apiVersion"] = version,
            ["format"] = FormatVersion
        };

        return Encoding.UTF8.GetString(DeterministicJson.ToBytes(manifest)).TrimEnd('\n');
    }

    // ── tsconfig.json ──────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The project file <c>pnpm typecheck:api</c> compiles.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         ⚠ <b>THE CHECK THIS SURFACE WOULD OTHERWISE NOT HAVE.</b> <c>ng build</c> compiles
    ///         what the app reaches, so a generated file nothing imports yet is a file nothing
    ///         type-checks — and <c>portal/eslint.config.mjs</c> ignores this directory on purpose.
    ///         The .NET SDK emitter has shipped two defects of exactly that shape into a checked-in
    ///         artifact (a duplicate enum and an undeclared one), green under every gate, because
    ///         nothing in this repository compiles <c>generated/sdk/*.cs</c>. This project file is
    ///         what stops the same thing happening one language over.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>A JSONC comment rather than a <c>"//"</c> key.</b> <c>tsc</c> parses a tsconfig
    ///         as JSONC, so a real comment works and is what a reader expects; the <c>"//"</c> key in
    ///         <c>package.json</c> exists only because <c>package.json</c> is strict JSON. Both
    ///         satisfy the architecture gate, which reads the first 2 KB either way.
    ///     </para>
    /// </remarks>
    static string ProjectFile() =>
        Banner + "\n"
        + "// ./build.sh Generate overwrites this file. docs/plan/03 § Assembly graph rules, rule 6.\n"
        + """
        {
          "extends": "../../tsconfig.base.json",
          "compilerOptions": {
            "noEmit": true,
            "types": []
          },
          "include": ["src/**/*.ts"]
        }
        """;

    // ── src/index.ts ───────────────────────────────────────────────────────────────────────────

    static string Index() =>
        Head()
        + "\nexport * from './models';\n"
        + "export * from './transport';\n"
        + "export * from './client';\n";

    // ── src/transport.ts ───────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The seam the portal fills in.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Generated even though it varies with nothing, because everything under
    ///     <c>libs/api</c> is generated.</b> docs/plan/03 § Assembly graph rules, rule 6: the
    ///     generator owns the directory. A hand-written file here would be the one file in the
    ///     package a regeneration does not overwrite, and the gate would fail it.
    /// </remarks>
    static string Transport(string version) =>
        Head()
        + """

        /** One request the client wants made. */
        export interface ApiRequest {
          /** The HTTP method. */
          readonly method: 'GET' | 'PUT' | 'PATCH' | 'POST' | 'DELETE';

          /**
           * The path, relative to the platform endpoint, with every placeholder already filled and
           * every segment already encoded.
           */
          readonly path: string;

          /**
           * The query parameters, unencoded. ⚠ `api-version` is NOT here: the transport puts it on
           * every request, exactly as the .NET SDK's ApiVersionHandler does, so no call site can
           * forget it and no two call sites can disagree about it.
           */
          readonly query?: Readonly<Record<string, string>>;

          /** The request body, already a plain object. Absent on a read. */
          readonly body?: unknown;
        }

        /** What came back. */
        export interface ApiResponse<T> {
          /** The HTTP status. ⚠ A scope PUT answers 201 the first time and 200 on a repeat. */
          readonly status: number;

          /** The parsed body. */
          readonly value: T;

          /**
           * The operation URL a 202 returned, from the Azure-AsyncOperation header, or undefined.
           * docs/plan/10 § Long-running operations, over HTTP.
           */
          readonly operationUrl?: string;
        }

        /**
         * How the client reaches the platform.
         *
         * ⚠ Supplied by the portal rather than generated. The portal calls the same public REST API
         * as `cyc`, with the same token (portal/README.md § Rules), and its bearer token, its
         * interceptors and its error handling belong to the app rather than to a file that is
         * overwritten on every build. Generating the fetch here would put authentication in
         * generated code and give the portal a second HTTP client beside the one it already has.
         */
        export interface ApiTransport {
          /** Makes one request. */
          send<T>(request: ApiRequest): Promise<ApiResponse<T>>;
        }

        /** One page of a collection — docs/plan/08 § The read path. */
        export interface Page<T> {
          /** The resources on this page, ordered by id. */
          readonly value: readonly T[];

          /**
           * The absolute URL of the next page, absent on the last one.
           *
           * ⚠ A short page never means "that is all there is". A listing runs a permission check per
           * member and the page is clamped, and the envelope deliberately carries no count — a total
           * would say how many resources exist that the caller may not see. Stop when `nextLink` is
           * absent, never when a page is smaller than you asked for.
           */
          readonly nextLink?: string;
        }

        /** How many resources a listing may examine, and where to resume. */
        export interface PageRequest {
          /**
           * ⚠ A cap the platform clamps and not a promise: the filter runs once per member, so this
           * bounds the work and not the number of results.
           */
          readonly top?: number;

          /** Take it from the previous page's `nextLink` rather than constructing one. */
          readonly skipToken?: string;
        }

        """
        + "/** The api-version every request this client makes is sent at. */\n"
        + "export const apiVersion = " + Quote(version) + " as const;\n";

    // ── src/models.ts ──────────────────────────────────────────────────────────────────────────

    static string Models(
        JsonObject document,
        ImmutableArray<DocumentType> types,
        ImmutableArray<DocumentScope> scopes
    ) {
        var built = new StringBuilder(Head());

        // ⚠ The error body is one shape for the whole API — docs/plan/08 § Errors — and the portal
        // highlights the field `target` names, which is why it is typed rather than left as unknown.
        built.Append("\n/** A stable, documented, greppable identifier. ⚠ Part of the API contract. */\n")
            .Append("export type CyberCloudErrorCode =\n");

        var codes = DocumentReader.EnumOf(
            document["components"]?["schemas"]?["ErrorCode"] as JsonObject ?? []
        );

        if (codes.IsEmpty) {
            built.Append("  string;\n");
        } else {
            for (var i = 0; i < codes.Length; i++) {
                built.Append("  | ").Append(Quote(codes[i])).Append(i == codes.Length - 1 ? ";\n" : "\n");
            }
        }

        built.Append("\n/** One error. docs/plan/08 § Errors. */\n")
            .Append("export interface CyberCloudError {\n")
            .Append("  readonly code: CyberCloudErrorCode;\n")
            .Append("  readonly message: string;\n")
            .Append("  /** ⚠ A JSON Pointer into the request body, so the portal can highlight the field. */\n")
            .Append("  readonly target?: string;\n")
            .Append("  readonly details?: readonly CyberCloudError[];\n")
            .Append("}\n");

        foreach (var scope in scopes) {
            AppendScopeModels(built, scope);
        }

        // ⚠ Once for all three scopes, because the document declares one response schema for all
        // three. A type per kind would be three identical interfaces whose only difference is the
        // value of one string literal.
        AppendScopeResource(built, document, scopes);

        foreach (var type in types) {
            AppendTypeModels(built, type);
        }

        return built.ToString();
    }

    static void AppendScopeResource(
        StringBuilder built,
        JsonObject document,
        ImmutableArray<DocumentScope> scopes
    ) {
        if (scopes.IsEmpty) {
            return;
        }

        var schema = document["components"]?["schemas"]?[OpenApiEmitter.ScopeSchema] as JsonObject ?? [];

        built.Append("\n/** A tenant, a subscription or a resource group, as the API renders it. */\n")
            .Append("/** ⚠ There is no provisioningState: a scope converges before the call returns. */\n")
            .Append("export interface ScopeResource {\n");

        foreach (var leaf in DocumentReader.LeavesOf(schema)) {
            if (leaf.IsObject) {
                continue;
            }

            AppendMember(built, "  ", leaf);
        }

        built.Append("}\n");
    }

    static void AppendScopeModels(StringBuilder built, DocumentScope scope) {
        if (!scope.Creatable) {
            return;
        }

        built.Append("\n/** The body of a PUT that creates a ")
            .Append(scope.DisplayName.ToLowerInvariant())
            .Append(". */\n")
            .Append("export interface ")
            .Append(ScopeInterface(scope))
            .Append(" {\n");

        foreach (var leaf in DocumentReader.LeavesOf(scope.Body)) {
            if (leaf.IsObject) {
                continue;
            }

            AppendMember(built, "  ", leaf);
        }

        built.Append("}\n");
    }

    static void AppendTypeModels(StringBuilder built, DocumentType type) {
        var model = ModelOf(type);
        var leaves = DocumentReader.LeavesOf(type.Body);

        AppendUnions(built, model, leaves);

        built.Append("\n/** ").Append(Comment(type.DisplayName)).Append(". ")
            .Append(Comment(type.Summary))
            .Append(" */\n")
            .Append("export interface ")
            .Append(model)
            .Append("Data {\n");

        AppendObject(built, "  ", EnumNaming.For(model, leaves), type.Body);

        built.Append("}\n")
            .Append("\n/** One ").Append(Comment(type.DisplayName)).Append(", as the API returns it. */\n")
            .Append("export interface ").Append(model).Append("Resource {\n")
            .Append("  /** The resource's fully qualified id. */\n")
            .Append("  readonly id: string;\n")
            .Append("  readonly name: string;\n")
            .Append("  readonly type: ").Append(Quote(type.ResourceType)).Append(";\n")
            .Append("  readonly properties?: ").Append(model).Append("Data['properties'];\n")
            .Append("}\n");

        foreach (var action in type.Actions) {
            AppendActionModels(built, model, action);
        }
    }

    static void AppendActionModels(StringBuilder built, string model, DocumentAction action) {
        if (action.Request is { } request) {
            var name = model + Pascal(action.Name) + "Content";

            AppendUnions(built, name, DocumentReader.LeavesOf(request));

            built.Append("\n/** The parameters of ").Append(Comment(action.Name)).Append(". */\n")
                .Append("export interface ").Append(name).Append(" {\n");

            AppendObject(built, "  ", EnumNaming.For(name, DocumentReader.LeavesOf(request)), request);

            built.Append("}\n");
        }

        if (action.Response is { } response) {
            var name = model + Pascal(action.Name) + "Result";

            // ⚠ AN ACTION'S OWN CLOSED SETS, AND LEAVING THEM OUT IS A FILE THAT DOES NOT COMPILE.
            // The first version of this emitter declared unions only for a type's body, so
            // CyberCloud.Messaging/kafkaClusters' listKeys response referred to
            // MessagingKafkaClustersListKeysResultSecurityProtocol and nothing declared it. `tsc`
            // said so in one line; the .NET SDK emitter has had the same defect, unnoticed, for as
            // long as it has existed — CS0246 in a file nothing in this repository compiles.
            AppendUnions(built, name, DocumentReader.LeavesOf(response));

            built.Append("\n/** What ").Append(Comment(action.Name)).Append(" returns.")
                .Append(action.Secret ? " ⚠ Secret material — never log or persist this." : string.Empty)
                .Append(" */\n")
                .Append("export interface ").Append(name).Append(" {\n");

            AppendObject(built, "  ", EnumNaming.For(name, DocumentReader.LeavesOf(response)), response);

            built.Append("}\n");
        }
    }

    /// <summary>
    ///     One string-literal union per closed set, before the interface that names them.
    /// </summary>
    /// <remarks>
    ///     ⚠ A union rather than a TypeScript <c>enum</c>: a TS enum is a runtime object, so it
    ///     survives into the bundle the portal ships and every value costs bytes against a budget
    ///     docs/plan/23 measures. A union is erased entirely and still refuses a typo at compile time.
    /// </remarks>
    static void AppendUnions(StringBuilder built, string model, ImmutableArray<SchemaLeaf> leaves) {
        var naming = EnumNaming.For(model, leaves);

        foreach (var leaf in leaves) {
            var values = DocumentReader.EnumOf(leaf.Schema);

            if (leaf.IsObject || values.IsEmpty) {
                continue;
            }

            built.Append("\n/** The values ")
                .Append(leaf.JsonPointer)
                .Append(" accepts. ⚠ Closed: the write path refuses anything else. */\n")
                .Append("export type ")
                .Append(naming.NameOf(leaf))
                .Append(" =\n");

            for (var i = 0; i < values.Length; i++) {
                built.Append("  | ").Append(Quote(values[i])).Append(i == values.Length - 1 ? ";\n" : "\n");
            }
        }
    }

    /// <summary>
    ///     How one model's union types are named, and which of them need their nesting to stay apart.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b><see cref="SdkEmitter" />'s rule, reached the same way and for the same defect.</b>
    ///     <c>CyberCloud.Cache/redis</c> declares <c>mode</c> at <c>/properties/mode</c> and again at
    ///     <c>/properties/persistence/mode</c>, and both are closed sets — so a bare
    ///     <c>model + Pascal(name)</c> declares one identifier twice. <c>tsc</c> calls that
    ///     <c>TS2300</c>; C# calls it <c>CS0101</c>; the C# one was checked in.
    /// </remarks>
    readonly record struct EnumNaming(string Model, ImmutableHashSet<string> Ambiguous) {
        /// <summary>The naming for one model's leaves.</summary>
        /// <param name="model">The model name.</param>
        /// <param name="leaves">Its leaves.</param>
        public static EnumNaming For(string model, ImmutableArray<SchemaLeaf> leaves) {
            var counts = new Dictionary<string, int>(StringComparer.Ordinal);

            foreach (var leaf in leaves) {
                if (leaf.IsObject || DocumentReader.EnumOf(leaf.Schema).IsEmpty) {
                    continue;
                }

                counts[leaf.Name] = counts.GetValueOrDefault(leaf.Name) + 1;
            }

            return new(model, [.. counts.Where(x => x.Value > 1).Select(x => x.Key)]);
        }

        /// <summary>The union name one enum leaf takes.</summary>
        /// <param name="leaf">The leaf.</param>
        public string NameOf(SchemaLeaf leaf) =>
            Model + (Ambiguous.Contains(leaf.Name) ? NestedName(leaf.JsonPointer) : Pascal(leaf.Name));
    }

    /// <summary>The dotted path under <c>/properties</c>, Pascal-cased.</summary>
    static string NestedName(string jsonPointer) {
        var segments = jsonPointer.Split('/', StringSplitOptions.RemoveEmptyEntries);

        if (segments.Length > 1 && string.Equals(segments[0], "properties", StringComparison.Ordinal)) {
            segments = segments[1..];
        }

        return string.Concat(segments.Select(Pascal));
    }

    /// <summary>
    ///     One object schema's own members, nested inline.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Nested inline rather than flattened into a dotted name, which is the opposite of what
    ///     <c>CliEmitter</c> does — and both are right for their surface.</b> A command line has no
    ///     nesting, so a flag has to be <c>--sku-name</c>; a JSON body does, and a portal that
    ///     assembled <c>{ properties: { sku: { name } } }</c> out of flat fields would be
    ///     re-deriving the shape the document already states.
    /// </remarks>
    /// <param name="built">The buffer.</param>
    /// <param name="indent">The current indentation.</param>
    /// <param name="naming">How this model's unions are named.</param>
    /// <param name="schema">The object schema.</param>
    /// <param name="pointer">
    ///     This object's own pointer within the body, so a nested leaf's is the whole of it.
    ///     <para>
    ///         ⚠ <b>Carried rather than rebuilt from the member name, and the first version did
    ///         rebuild it.</b> A leaf under <c>/properties/persistence</c> arrived with the pointer
    ///         <c>/mode</c>, so the nested form of a colliding union name — which is derived from the
    ///         pointer — would have been <c>Mode</c> for both members of the pair, and the collision
    ///         would have survived the fix for it.
    ///     </para>
    /// </param>
    static void AppendObject(
        StringBuilder built,
        string indent,
        EnumNaming naming,
        JsonObject schema,
        string pointer = ""
    ) {
        if (schema["properties"] is not JsonObject properties) {
            return;
        }

        var required = schema["required"] is JsonArray names
            ? names.Select(DocumentReader.Text).ToHashSet(StringComparer.Ordinal)
            : [];

        foreach (var member in properties.ToList().OrderBy(x => x.Key, StringComparer.Ordinal)) {
            if (member.Value is not JsonObject child) {
                continue;
            }

            var isObject = DocumentReader.TypeOf(child) == "object" && child["properties"] is JsonObject;

            var leaf = new SchemaLeaf(
                pointer + "/" + member.Key,
                member.Key,
                child,
                required.Contains(member.Key),
                isObject
            );

            if (!isObject) {
                AppendMember(built, indent, leaf, naming);
                continue;
            }

            AppendDoc(built, indent, child);

            built.Append(indent)
                .Append(Member(member.Key))
                .Append(leaf.Required ? "" : "?")
                .Append(": {\n");

            AppendObject(built, indent + "  ", naming, child, leaf.JsonPointer);

            built.Append(indent).Append("};\n");
        }
    }

    static void AppendMember(StringBuilder built, string indent, SchemaLeaf leaf, EnumNaming naming = default) {
        AppendDoc(built, indent, leaf.Schema);

        built.Append(indent)
            .Append(DocumentReader.Flag(leaf.Schema["readOnly"]) ? "readonly " : string.Empty)
            .Append(Member(leaf.Name))
            .Append(leaf.Required ? "" : "?")
            .Append(": ")
            .Append(TsType(leaf, naming))
            .Append(";\n");
    }

    static void AppendDoc(StringBuilder built, string indent, JsonObject schema) {
        if (DocumentReader.Text(schema["description"]) is not { Length: > 0 } text) {
            return;
        }

        built.Append(indent).Append("/** ").Append(Comment(text)).Append(" */\n");
    }

    /// <summary>The TypeScript type of one leaf.</summary>
    /// <remarks>
    ///     ⚠ An enum is a union of string literals rather than a TypeScript <c>enum</c>. A TS enum is
    ///     a runtime object, so it survives into the bundle the portal ships and every value costs
    ///     bytes in a budget docs/plan/23 measures; a union is erased entirely and still refuses a
    ///     typo at compile time.
    /// </remarks>
    static string TsType(SchemaLeaf leaf, EnumNaming naming) {
        var schema = leaf.Schema;
        var values = DocumentReader.EnumOf(schema);
        var nullable = DocumentReader.IsNullable(schema);

        var bare = !values.IsEmpty && naming.Model is { Length: > 0 } && DocumentReader.TypeOf(schema) != "array"
            ? naming.NameOf(leaf)
            : DocumentReader.TypeOf(schema) switch {
                "array" => Scalar(schema["items"] as JsonObject ?? [], naming, leaf) + "[]",
                "object" => "Record<string, string>",
                var scalar => Scalar(schema, naming, leaf, scalar)
            };

        return nullable ? bare + " | null" : bare;
    }

    static string Scalar(JsonObject schema, EnumNaming naming, SchemaLeaf leaf, string? declared = null) {
        var values = DocumentReader.EnumOf(schema);

        if (!values.IsEmpty && naming.Model is { Length: > 0 } && DocumentReader.TypeOf(leaf.Schema) == "array") {
            return naming.NameOf(leaf);
        }

        return (declared ?? DocumentReader.TypeOf(schema)) switch {
            "integer" or "number" => "number",
            "boolean" => "boolean",
            "string" => "string",
            // ⚠ `unknown` rather than `any`: an undeclared shape is one the caller has to narrow,
            // and `any` would let it be used as anything with no error at all.
            _ => "unknown"
        };
    }

    // ── src/client.ts ──────────────────────────────────────────────────────────────────────────

    static string Client(
        string version,
        ImmutableArray<DocumentType> types,
        ImmutableArray<DocumentScope> scopes
    ) {
        var built = new StringBuilder(Head());

        built.Append("\nimport type { ApiResponse, ApiTransport, Page, PageRequest } from './transport';\n")
            .Append("import type {\n");

        var imported = new SortedSet<string>(StringComparer.Ordinal) { "ScopeResource" };

        foreach (var scope in scopes.Where(x => x.Creatable)) {
            imported.Add(ScopeInterface(scope));
        }

        foreach (var type in types) {
            var model = ModelOf(type);
            imported.Add(model + "Data");
            imported.Add(model + "Resource");

            foreach (var action in type.Actions) {
                if (action.Request is not null) {
                    imported.Add(model + Pascal(action.Name) + "Content");
                }

                if (action.Response is not null) {
                    imported.Add(model + Pascal(action.Name) + "Result");
                }
            }
        }

        foreach (var name in imported) {
            built.Append("  ").Append(name).Append(",\n");
        }

        built.Append("} from './models';\n")
            .Append("\n/** The api-version this client was generated at. */\n")
            .Append("export const generatedApiVersion = ").Append(Quote(version)).Append(" as const;\n");

        built.Append("""

            /**
             * The public REST API, typed.
             *
             * ⚠ Every method builds a path and hands it to the transport. Authentication, retries and
             * error mapping are the transport's, which is the portal's — portal/README.md § Rules:
             * "The portal has no privileged path. It calls the same public REST API as the CLI, with
             * the same token."
             */
            export class CyberCloudApi {
              constructor(private readonly transport: ApiTransport) {}

            """);

        foreach (var scope in scopes) {
            AppendScopeMethods(built, scope);
        }

        foreach (var type in types) {
            AppendTypeMethods(built, type);
        }

        built.Append("""
              /** Percent-encodes one path segment. ⚠ A name is caller data and a '/' in one would forge a path. */
              private static segment(value: string): string {
                return encodeURIComponent(value);
              }

              /**
               * The paging query, with only what the caller actually set.
               *
               * ⚠ The names carry their `$`, which is what the gateway reads. A gateway IGNORES a
               * query parameter it does not recognise, so a misspelling here is not an error
               * anywhere — it is a 200 holding page one, for ever.
               */
              private static pageQuery(page: PageRequest): Record<string, string> {
                const query: Record<string, string> = {};

                if (page.top !== undefined) {
                  query['$top'] = String(page.top);
                }

                if (page.skipToken !== undefined) {
                  query['$skipToken'] = page.skipToken;
                }

                return query;
              }
            }

            """);

        return built.ToString();
    }

    static void AppendScopeMethods(StringBuilder built, DocumentScope scope) {
        var name = Pascal(scope.Kind);
        var placeholders = DocumentReader.PlaceholdersOf(scope.Path);
        var parameters = string.Join(", ", placeholders.Select(x => Camel(x) + ": string"));

        built.Append("  /** Reads one ").Append(Comment(scope.DisplayName.ToLowerInvariant())).Append(". */\n")
            .Append("  get").Append(name).Append('(').Append(parameters)
            .Append("): Promise<ApiResponse<ScopeResource>> {\n")
            .Append("    return this.transport.send<ScopeResource>({ method: 'GET', path: ")
            .Append(PathExpression(scope.Path))
            .Append(" });\n  }\n\n");

        if (!scope.Creatable) {
            // ⚠ Said in the generated file, because a class with one method reads the same whether
            // the create was decided against or forgotten.
            built.Append("  // ⚠ There is no create").Append(name)
                .Append(", and the absence is the contract. A request's tenant\n")
                .Append("  // is resolved from its token, so a call creating another tenant carries a token\n")
                .Append("  // that is not that tenant's and is refused before routing runs.\n\n");

            return;
        }

        built.Append("  /** Creates one ").Append(Comment(scope.DisplayName.ToLowerInvariant()))
            .Append(", or returns the existing one unchanged. */\n")
            .Append("  /** ⚠ 201 the first time and 200 on a repeat, and no operation to poll. */\n")
            .Append("  create").Append(name).Append('(')
            .Append(parameters)
            .Append(placeholders.IsEmpty ? string.Empty : ", ")
            .Append("content: ").Append(ScopeInterface(scope))
            .Append("): Promise<ApiResponse<ScopeResource>> {\n")
            .Append("    return this.transport.send<ScopeResource>({ method: 'PUT', path: ")
            .Append(PathExpression(scope.Path))
            .Append(", body: content });\n  }\n\n");
    }

    static void AppendTypeMethods(StringBuilder built, DocumentType type) {
        var model = ModelOf(type);
        var placeholders = DocumentReader.PlaceholdersOf(type.Path);
        var parameters = string.Join(", ", placeholders.Select(x => Camel(x) + ": string"));
        var verb = Pascal(type.DisplayName is { Length: > 0 } ? type.DisplayName : type.TypePath);

        built.Append("  /** Reads one ").Append(Comment(type.DisplayName)).Append(". */\n")
            .Append("  get").Append(verb).Append('(').Append(parameters)
            .Append("): Promise<ApiResponse<").Append(model).Append("Resource>> {\n")
            .Append("    return this.transport.send<").Append(model).Append("Resource>({ method: 'GET', path: ")
            .Append(PathExpression(type.Path))
            .Append(" });\n  }\n\n");

        built.Append("  /** Creates or replaces one ").Append(Comment(type.DisplayName))
            .Append(". ⚠ Long-running: the response is a 202 carrying operationUrl. */\n")
            .Append("  createOrUpdate").Append(verb).Append('(').Append(parameters)
            .Append(placeholders.IsEmpty ? string.Empty : ", ")
            .Append("data: ").Append(model).Append("Data")
            .Append("): Promise<ApiResponse<").Append(model).Append("Resource>> {\n")
            .Append("    return this.transport.send<").Append(model).Append("Resource>({ method: 'PUT', path: ")
            .Append(PathExpression(type.Path))
            .Append(", body: data });\n  }\n\n");

        built.Append("  /** Amends one ").Append(Comment(type.DisplayName))
            .Append(". A merge patch: what is not set is not changed. */\n")
            .Append("  update").Append(verb).Append('(').Append(parameters)
            .Append(placeholders.IsEmpty ? string.Empty : ", ")
            .Append("data: Partial<").Append(model).Append("Data>")
            .Append("): Promise<ApiResponse<").Append(model).Append("Resource>> {\n")
            .Append("    return this.transport.send<").Append(model).Append("Resource>({ method: 'PATCH', path: ")
            .Append(PathExpression(type.Path))
            .Append(", body: data });\n  }\n\n");

        built.Append("  /** Deletes one ").Append(Comment(type.DisplayName)).Append('.')
            .Append(
                type.SoftDeleteDays > 0
                    ? " ⚠ Recoverable for " + DocumentReader.Count(type.SoftDeleteDays) + " day(s)."
                    : " ⚠ Permanent: this type declares no soft-delete window."
            )
            .Append(" */\n")
            .Append("  delete").Append(verb).Append('(').Append(parameters)
            .Append("): Promise<ApiResponse<void>> {\n")
            .Append("    return this.transport.send<void>({ method: 'DELETE', path: ")
            .Append(PathExpression(type.Path))
            .Append(" });\n  }\n\n");

        if (type.CollectionPath.Length > 0) {
            var collectionPlaceholders = DocumentReader.PlaceholdersOf(type.CollectionPath);

            built.Append("  /** One page of the ").Append(Comment(type.DisplayPlural))
                .Append(" in a resource group. ⚠ A short page never means \"that is all there is\". */\n")
                .Append("  list").Append(verb).Append('(')
                .Append(string.Join(", ", collectionPlaceholders.Select(x => Camel(x) + ": string")))
                .Append(collectionPlaceholders.IsEmpty ? string.Empty : ", ")
                .Append("page: PageRequest = {}")
                .Append("): Promise<ApiResponse<Page<").Append(model).Append("Resource>>> {\n")
                .Append("    return this.transport.send<Page<").Append(model)
                .Append("Resource>>({ method: 'GET', path: ")
                .Append(PathExpression(type.CollectionPath))
                .Append(", query: CyberCloudApi.pageQuery(page) });\n  }\n\n");
        }

        foreach (var action in type.Actions) {
            var result = action.Response is null ? "unknown" : model + Pascal(action.Name) + "Result";

            built.Append("  /** ").Append(Comment(action.Name)).Append(" — permission '")
                .Append(Comment(action.Permission)).Append("'.")
                .Append(action.Secret ? " ⚠ The response carries secret material." : string.Empty)
                .Append(action.LongRunning ? " ⚠ Long-running." : string.Empty)
                .Append(" */\n")
                .Append("  ").Append(Camel(action.Name)).Append(verb).Append('(').Append(parameters);

            if (action.Request is not null) {
                built.Append(placeholders.IsEmpty ? string.Empty : ", ")
                    .Append("content: ").Append(model).Append(Pascal(action.Name)).Append("Content");
            }

            built.Append("): Promise<ApiResponse<").Append(result).Append(">> {\n")
                .Append("    return this.transport.send<").Append(result).Append(">({ method: 'POST', path: ")
                .Append(PathExpression(type.Path + "/" + action.Name))
                .Append(action.Request is null ? string.Empty : ", body: content")
                .Append(" });\n  }\n\n");
        }
    }

    /// <summary>
    ///     A path template as a TypeScript template literal with each placeholder encoded.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Every substitution goes through <c>segment()</c>.</b> A resource name is caller data
    ///     and a <c>/</c> in one would forge a path — the portal would address a different resource,
    ///     or a scope, and the gateway would answer about whatever the forged URL named.
    /// </remarks>
    static string PathExpression(string path) {
        var built = new StringBuilder("`");

        for (var i = 0; i < path.Length; i++) {
            if (path[i] != '{') {
                if (path[i] is '`' or '\\') {
                    built.Append('\\');
                }

                built.Append(path[i]);
                continue;
            }

            var close = path.IndexOf('}', i + 1);

            if (close < 0) {
                built.Append(path[i]);
                continue;
            }

            built.Append("${CyberCloudApi.segment(").Append(Camel(path[(i + 1)..close])).Append(")}");
            i = close;
        }

        return built.Append('`').ToString();
    }

    // ── Self-check ─────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     What this surface can get wrong, as one line per problem.
    /// </summary>
    /// <param name="files">The emitted files.</param>
    /// <returns>Empty when the package is sound.</returns>
    /// <remarks>
    ///     ⚠ <b>This exists because nothing in the .NET build type-checks TypeScript and
    ///     <c>portal/eslint.config.mjs</c> ignores this directory.</b> The .NET SDK emitter shipped a
    ///     property typed with a name it never declared, in a file no build in this repository
    ///     compiled — issue #73 has since given that file a compiler too, and this check is what
    ///     found the shape in the first place; the same mistake here would reach the portal's
    ///     <c>ng build</c>, one target
    ///     later, and only once something imported the client. So every name the client imports has
    ///     to be a name the models export — which is the cheapest check that would have caught it,
    ///     and it is honest about being narrower than a compiler.
    /// </remarks>
    public static ImmutableArray<string> Problems(ImmutableSortedDictionary<string, string> files) {
        ArgumentNullException.ThrowIfNull(files);

        var problems = new List<string>();

        if (!files.TryGetValue("src/models.ts", out var models)
            || !files.TryGetValue("src/client.ts", out var client)) {
            problems.Add(
                "the package is missing src/models.ts or src/client.ts, so the emitter produced "
                + "something no portal can import."
            );

            return [.. problems];
        }

        var exported = models.Split('\n')
            .Select(x => x.Trim())
            .Where(x => x.StartsWith("export interface ", StringComparison.Ordinal)
                        || x.StartsWith("export type ", StringComparison.Ordinal))
            .Select(x => x.Split(' ')[2].TrimEnd('{', ' ', '='))
            .ToHashSet(StringComparer.Ordinal);

        foreach (var line in client.Split('\n')) {
            var trimmed = line.Trim().TrimEnd(',');

            // The import block is one name per line, which is the only place client.ts names a model.
            if (trimmed.Length == 0
                || trimmed.Contains(' ', StringComparison.Ordinal)
                || !char.IsAsciiLetterUpper(trimmed[0])
                || exported.Contains(trimmed)) {
                continue;
            }

            problems.Add(
                $"src/client.ts imports '{trimmed}' from './models' and src/models.ts does not export "
                + "it. The portal's build would fail on an import of a type that is not there, one "
                + "target after this one — which is the failure the .NET SDK emitter shipped, in a "
                + "file nothing in this repository compiles."
            );
        }

        foreach (var file in files) {
            if (!file.Value.Contains("@generated", StringComparison.Ordinal)) {
                problems.Add(
                    $"'{file.Key}' carries no generator banner in its first line. "
                    + "Build.Architecture's rule 6 reads the first 2 KB of every file under "
                    + "portal/libs/api and fails on one that does not say it is generated — and a "
                    + "reader who opens an unmarked file is a reader who edits it."
                );
            }
        }

        problems.Sort(StringComparer.Ordinal);
        return [.. problems];
    }

    // ── Small shared machinery ─────────────────────────────────────────────────────────────────

    static string Head() =>
        Banner + "\n"
        + "// Generated from the published OpenAPI document — docs/plan/21 § Generation's one hop.\n"
        + "// ./build.sh Generate overwrites this file and ./build.sh Architecture fails on a\n"
        + "// difference. docs/plan/03 § Assembly graph rules, rule 6.\n";

    /// <summary>The interface name a scope's create body takes.</summary>
    static string ScopeInterface(DocumentScope scope) => Pascal(scope.Kind) + "CreateContent";

    /// <summary>The union name one enum leaf takes.</summary>
    /// <summary>
    ///     The model name a resource type takes — its display name, or its type path.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Not <c>SdkEmitter</c>'s, and the difference is deliberate.</b> That emitter resolves
    ///     collisions by prefixing the provider, because two providers will both have a
    ///     <c>servers</c>. This one keys on the fully qualified type path instead, which is unique by
    ///     construction — the registry keys on it — so there is no collision to resolve and no
    ///     second-pass rule that could disagree with the first.
    /// </remarks>
    static string ModelOf(DocumentType type) =>
        Pascal(type.ProviderNamespace.Split('.')[^1]) + Pascal(type.TypePath);

    static string Member(string name) =>
        name.Length > 0 && (char.IsAsciiLetter(name[0]) || name[0] is '_' or '$')
        && name.All(x => char.IsAsciiLetterOrDigit(x) || x is '_' or '$')
            ? name
            : Quote(name);

    /// <summary>A TypeScript single-quoted string literal.</summary>
    static string Quote(string value) =>
        "'" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("'", "\\'", StringComparison.Ordinal)
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal) + "'";

    /// <summary>
    ///     Text that is safe inside a <c>/** … */</c> comment, on one line.
    /// </summary>
    /// <remarks>
    ///     ⚠ <c>*/</c> in a description would end the comment and turn the rest of the sentence into
    ///     a syntax error, exactly as a newline does in <c>SdkEmitter.Escape</c>'s <c>///</c>.
    /// </remarks>
    static string Comment(string value) =>
        value.Replace("*/", "* /", StringComparison.Ordinal)
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    /// <summary>Any identifier-ish string as <c>PascalCase</c>, invariantly.</summary>
    /// <remarks>⚠ <see cref="SdkEmitter.Pascal" />'s, so the two surfaces name a type the same way.</remarks>
    static string Pascal(string value) => SdkEmitter.Pascal(value);

    /// <summary>Any identifier-ish string as <c>camelCase</c>, invariantly.</summary>
    static string Camel(string value) {
        var pascal = Pascal(value);

        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }
}
