using System.Collections.Immutable;
using System.Text;
using System.Text.Json.Nodes;

namespace CyberCloud.ResourceManager.Contracts.Generation;

/// <summary>One file of the generated TypeScript client.</summary>
/// <param name="File">The path under <c>portal/libs/api</c>. ⚠ Never an absolute path.</param>
/// <param name="ApiVersion">The api-version it was generated at.</param>
/// <param name="Published">Whether a file of that name was already checked in.</param>
/// <param name="Drifted">Whether the regenerated bytes differ from the checked-in ones.</param>
public sealed record TypeScriptFile(string File, string ApiVersion, bool Published, bool Drifted);

/// <summary>What one TypeScript-client run produced.</summary>
/// <param name="Files">One entry per file, ordered by path.</param>
/// <param name="Stale">Checked-in files this run did not produce, ordered by path.</param>
/// <param name="Problems">What the surface's own self-check found.</param>
public sealed record TypeScriptReport(
    ImmutableArray<TypeScriptFile> Files,
    ImmutableArray<string> Stale,
    ImmutableArray<string> Problems
) {
    /// <summary>Whether anything at all is wrong.</summary>
    public bool IsClean => Stale.IsEmpty && Problems.IsEmpty && Files.All(x => !x.Drifted);

    /// <summary>
    ///     Whether the run had nothing to emit — the vacuous pass a caller must read rather than
    ///     mistake for a clean one.
    /// </summary>
    public bool IsVacuous => Files.IsEmpty;
}

/// <summary>
///     Writes the portal's TypeScript client and says what changed.
/// </summary>
/// <remarks>
///     <para>
///         ⚠ <b>A separate output root from <c>generated/</c>, and the reason is rule 6 rather than
///         taste.</b> docs/plan/03 § Assembly graph rules says <c>portal/libs/api</c> has no
///         hand-written files and the generator owns the directory, and
///         <c>build/Build.Architecture.cs</c> enforces it by reading the head of every file there. A
///         client written under <c>generated/</c> and copied across would make that gate inspect a
///         copy — and the copy step would be the one part of the chain nothing checked.
///     </para>
///     <para>
///         ⚠ <b>ONE api-version, unlike every other derived surface.</b> The CLI, the SDK and the
///         forms are written once per version because a <c>cyc</c> binary selects between versions at
///         run time. A portal build is deployed against one platform and its bundle is measured
///         against a budget (docs/plan/23), so shipping every version's models to a browser to use
///         one of them is a cost with no reader. The newest version wins, which is what
///         <see cref="Generate" />'s ordering makes true.
///     </para>
///     <para>
///         ⚠ <b>Stale files are reported and never deleted</b>, exactly as
///         <see cref="DerivedSurfaces" /> and <c>OpenApiArtifacts</c> report and never delete. A
///         generator that removes what it did not produce is one bad run away from removing a file
///         somebody needed, and the message costs nothing.
///     </para>
/// </remarks>
public static class TypeScriptSurfaces {
    /// <summary>The directory, relative to the repository root, the client is checked in at.</summary>
    public const string DirectoryName = "portal/libs/api";

    /// <summary>
    ///     Files under the client's root that this generator does not produce and does not report as
    ///     stale.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>The README is the one hand-written file in a directory whose rule is that it has
    ///     none, and it survives because it is what tells a reader that.</b> It carries the same
    ///     generator banner every emitted file does — which is what
    ///     <c>build/Build.Architecture.cs</c>'s rule 6 actually checks — and
    ///     <see cref="DerivedSurfaces" /> exempts <c>.md</c> from its own stale check for the same
    ///     reason.
    /// </remarks>
    static bool IsExempt(string relative) => relative.EndsWith(".md", StringComparison.Ordinal);

    /// <summary>
    ///     Emits the client for the newest document, compares against what is checked in, and
    ///     optionally writes.
    /// </summary>
    /// <param name="documents">The emitted per-version OpenAPI documents, keyed by api-version.</param>
    /// <param name="directory">The client's root — <c>portal/libs/api</c>.</param>
    /// <param name="write">
    ///     Whether to write. <see langword="false" /> is the check-only mode the <c>Architecture</c>
    ///     gate uses, so a gate never has a side effect on the tree it is inspecting.
    /// </param>
    public static TypeScriptReport Generate(
        IReadOnlyDictionary<string, JsonObject> documents,
        string directory,
        bool write
    ) {
        ArgumentNullException.ThrowIfNull(documents);
        ArgumentException.ThrowIfNullOrEmpty(directory);

        if (documents.Count == 0) {
            return new([], [], []);
        }

        // ⚠ The newest, and ordinal ordering is chronological because a version is a date —
        // docs/plan/10 § API versioning. The same ordering ApiVersionsOf relies on.
        var version = documents.Keys.OrderBy(x => x, StringComparer.Ordinal).Last();
        var files = TypeScriptEmitter.Emit(documents[version]);
        var produced = new List<TypeScriptFile>();
        var expected = new HashSet<string>(StringComparer.Ordinal);

        foreach (var file in files) {
            expected.Add(file.Key);

            var path = Path.Combine(directory, file.Key.Replace('/', Path.DirectorySeparatorChar));
            var bytes = Text(file.Value);
            var published = File.Exists(path) ? File.ReadAllBytes(path) : null;
            var drifted = published is null || !published.AsSpan().SequenceEqual(bytes);

            if (write && drifted) {
                var parent = Path.GetDirectoryName(path);

                if (!string.IsNullOrEmpty(parent)) {
                    Directory.CreateDirectory(parent);
                }

                File.WriteAllBytes(path, bytes);
            }

            produced.Add(new(file.Key, version, published is not null, drifted));
        }

        var root = new DirectoryInfo(directory);

        var stale = root.Exists
            ? root.EnumerateFiles("*", SearchOption.AllDirectories)
                .Select(x => Relative(directory, x.FullName))
                .Where(x => !expected.Contains(x) && !IsExempt(x))
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToImmutableArray()
            : [];

        return new(
            [.. produced.OrderBy(x => x.File, StringComparer.Ordinal)],
            stale,
            TypeScriptEmitter.Problems(files)
        );
    }

    /// <summary>The report as one line per file, for a build log.</summary>
    /// <param name="report">The report.</param>
    public static ImmutableArray<string> Describe(TypeScriptReport report) {
        ArgumentNullException.ThrowIfNull(report);

        var lines = new List<string>();

        foreach (var file in report.Files) {
            lines.Add(
                $"  {(file.Drifted ? "±" : "=")} {DirectoryName}/{file.File} — "
                + (file.Published ? file.Drifted ? "differs from the document" : "unchanged" : "new")
            );
        }

        foreach (var stale in report.Stale) {
            lines.Add($"  ! {DirectoryName}/{stale} — checked in and not produced by this run");
        }

        foreach (var problem in report.Problems) {
            lines.Add($"  ✗ {DirectoryName} — {problem}");
        }

        return [.. lines];
    }

    /// <summary>
    ///     The one way generated source text becomes bytes — UTF-8 with no BOM, LF, one trailing
    ///     newline.
    /// </summary>
    /// <remarks>
    ///     ⚠ <see cref="DerivedSurfaces" />' rule, for the reason it gives: a CRLF from
    ///     <c>Environment.NewLine</c> would make CI red on Windows and green on the author's machine.
    /// </remarks>
    static byte[] Text(string source) {
        var normalised = source.Replace("\r\n", "\n", StringComparison.Ordinal);

        if (!normalised.EndsWith('\n')) {
            normalised += "\n";
        }

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(normalised);
    }

    static string Relative(string directory, string full) =>
        Path.GetRelativePath(directory, full).Replace(Path.DirectorySeparatorChar, '/');
}
