using System.Reflection;
using System.Text.RegularExpressions;

namespace CyberCloud.Providers.Compute.Tests;

/// <summary>
///     The two tables this family spells twice — once in C#, once in a chart — held together.
/// </summary>
/// <remarks>
///     ⚠ A Helm template is not a schema and nothing generates it — <c>ChartSurfaces</c> filters
///     <c>templates/</c> out of the chart tree on purpose — so <c>VirtualMachines.Sizes</c> and the
///     <c>_helpers.tpl</c> dictionaries are two hand-maintained copies of one table, as are
///     <c>Images.Catalogue</c> and the image chart's <c>image.catalogue</c> dictionary. A rung that
///     drifted would be a machine billed at one size and booted at another; a digest that drifted
///     would be two platforms disagreeing about what an image name means. The files are embedded by
///     the <c>.csproj</c> so the comparison runs wherever the tests do.
/// </remarks>
public sealed partial class ComputeChartDriftTests {
    [Theory]
    [InlineData("virtual-machine.helpers.tpl")]
    [InlineData("virtual-machine-scale-set.helpers.tpl")]
    public void TheChartsSizeTableIsTheCSharpOne(string chart) {
        // ⚠ Two charts, one C# table: the scale set's helpers spell the machine's sizes a third time,
        // because a Helm chart cannot include another chart's helpers without a dependency.
        var helpers = Embedded(chart);

        var cores = Dictionary(helpers, "$cores");
        var memory = Dictionary(helpers, "$memory");

        cores.Keys.OrderBy(static x => x, StringComparer.Ordinal)
            .ShouldBe(
                VirtualMachines.SizeNames,
                Case.Sensitive,
                "the chart offers sizes the schema does not, or the other way round"
            );
        memory.Keys.OrderBy(static x => x, StringComparer.Ordinal).ShouldBe(VirtualMachines.SizeNames);

        foreach (var (name, (expectedCores, expectedMemory)) in VirtualMachines.Sizes) {
            cores[name].ShouldBe(expectedCores.ToString(System.Globalization.CultureInfo.InvariantCulture), name);
            memory[name].ShouldBe(expectedMemory, name);
        }
    }

    [Fact]
    public void TheChartsCatalogueIsTheCSharpOne() {
        var helpers = Embedded("image.helpers.tpl");

        var rows = CatalogueRow().Matches(helpers)
            .ToDictionary(
                static x => x.Groups["name"].Value,
                static x => x.Groups["url"].Value,
                StringComparer.Ordinal
            );

        rows.Keys.OrderBy(static x => x, StringComparer.Ordinal)
            .ShouldBe(
                Images.CatalogueNames,
                Case.Sensitive,
                "the chart's catalogue names a different set of images than Images.Catalogue"
            );

        foreach (var (name, image) in Images.Catalogue) {
            rows[name].ShouldBe(image.Url, $"{name} is pinned to different bytes in the chart and in C#");
        }
    }

    [Fact]
    public void TheChartsEnumForSizeIsTheClosedSet() {
        // ⚠ The @enum line is GENERATED by ./build.sh Charts, so this catches a chart that was not
        // regenerated after the C# table moved — the failure the Charts target would report later and
        // slower. The line is read out of the embedded helpers' sibling values.yaml by the Charts
        // target itself; here the helpers' own dictionaries are the subject.
        VirtualMachines.SizeNames.ShouldBe(["s1.large", "s1.medium", "s1.small", "s1.xlarge"]);
        VirtualMachines.Sizes[VirtualMachines.DefaultSize].ShouldBe((1, "4Gi"));
    }

    /// <summary>The <c>dict "k" v "k" v …</c> literal a helper assigns to a variable, as a map.</summary>
    static Dictionary<string, string> Dictionary(string helpers, string variable) {
        var line = helpers.Split('\n').Single(x => x.Contains(variable + " := dict", StringComparison.Ordinal));
        var pairs = DictionaryPair().Matches(line);

        pairs.Count.ShouldBeGreaterThan(0, $"no `{variable} := dict` line with pairs in _helpers.tpl");

        return pairs.ToDictionary(
            static x => x.Groups["key"].Value,
            static x => x.Groups["value"].Value,
            StringComparer.Ordinal
        );
    }

    static string Embedded(string name) {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name)
            ?? throw new InvalidOperationException($"'{name}' is not embedded; see the .csproj");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    [GeneratedRegex("\"(?<key>[a-z0-9.]+)\" \"?(?<value>[A-Za-z0-9]+)\"?")]
    private static partial Regex DictionaryPair();

    [GeneratedRegex(@"^\s*""(?<name>[a-z0-9.-]+)"" ""(?<url>docker://[^""]+)""", RegexOptions.Multiline)]
    private static partial Regex CatalogueRow();
}
